### ISSUE TITLE
TUN/TAP support

### ISSUE THREAD

**Issue by 2senel** [osmc/osmc#106]
Please add tun tap kernel modules. Thanks!

**Comment by samnazarko** [comment]
Do you have the exact CONFIG_ options?

Sam

**Comment by 2senel** [comment]
Nope, or at least, I don`t think so. I need tun/tap support just for OpenVPN and ZeroTier.

**Comment by samnazarko** [comment]
I'll see what I can do. Will leave this open for now.

**Comment by diogocp** [comment]
CONFIG_TUN should be enough for OpenVPN.

**Comment by diogocp** [comment]
Looks like this is already enabled. Tested OpenVPN and it works.

https://github.com/samnazarko/osmc/search?q=CONFIG_TUN&type=Code
