### ISSUE TITLE
Possible bug when calculating "show ends at ..."

### ISSUE THREAD

**Issue by sonst-was** [osmc/osmc#144]
Hi,

recently I've seen a strange thing while watching a series. In the info screen (press i) it states the current time and the time when the current episode will be finished.

So I was watching the episode and looked at the info screen and saw, that the "show ends at ..." time was switching between 20:16 and 20:17 constantly. I dont know what may have caused that miscalculation but I think there might be an rounding error.

I'm running OSMC Kodi (compiled Mar 14 2015) on an Raspberry Pi 2.

**Comment by samnazarko** [comment]
Hi

Can you provide some more background here:

>time was switching between 20:16 and 20:17 constantly

Was this during playback or when the video was paused?

What is the duration of the video (exact duration)

S

**Comment by sonst-was** [comment]
This occured during playback. Once I've paused for a second or so it stopped switching and constantly showed 20:17.

I cant provide the duration of that specific episode because I dont know which episode it was exactly (I watched multiple episodes that evening). But here the durations of (probably) all the episodes I've watched that evening:
42:34
42:56
42:51
39:03

**Comment by HitcherUK** [comment]
One thing's for sure - it's not a skinning problem and must be Kodi related.

**Comment by sonst-was** [comment]
I have encountered this bug again. Again during playback.

I managed to make a short video of it: http://sonst-was.de/owncloud/index.php/s/9VOiejG0H33WetH (password is osmcbugreport).

The duration of this video would be 42:30.

**Comment by samnazarko** [comment]
Is this still an issue?

**Comment by sonst-was** [comment]
> Is this still an issue?

I've moved a few weeks ago and have currently no TV avaible. So my Pi is sadly sitting in a box waiting for me.

Therefore, its currently not possible for me to say whether this still occurs or not. Sorry about that.
