### ISSUE TITLE
Chinese Character is not displaying (Working around is disabled on OSMC)

### ISSUE THREAD

**Issue by CharlesCai930** [osmc/osmc#146]
I have found out that the new OSMC is not able to display the language in Chinese with the default skin (font), the previous XBMC(Kodi) can get work around by change the fonts to "Ariel Based" instead of the skin default font. 

but OSMC is not able to change the skin default fonts.  so, what we see is all square boxes. 

Thank you

**Comment by sbilly** [comment]
+1

**Comment by hardvk0** [comment]
+1
