### ISSUE TITLE
IPv6 DNS display in GUI

### ISSUE THREAD

**Issue by npd6** [osmc/osmc#147]
The specific bug here is that the GUI displays an IPv6 Secondary DNS is a manner which is formatted such that you cannot read it. Please see attached - self-explanatory.

However: it also raises the question of IPv6 "visibility". OSMC has working v6 without user intervention. If it sees advertised v6, it will happily grab it and use it dual-stack along with v4. This is excellent! However, apart from the badly formatted DNS string as per this bug's primary report, it's pretty much invisible via the GUI. I would hope this could change! cli is perfect: v6 looks 100%. But the GUI is lacking!! 
![img_20150406_194046](https://cloud.githubusercontent.com/assets/8194785/7008831/3f81b3a0-dc96-11e4-9209-a786c1d91f5a.jpg)

**Comment by samnazarko** [comment]
This is planned for the future.
