### ISSUE TITLE
Japanese characters

### ISSUE THREAD

**Issue by ceesvanegmond** [osmc/osmc#158]
Hi all,

I'm using OSMC since today. I do have a few series/movies that do have Japanese characters in the name. Those characters aren't in the font set what OSMC using. When switching to Confluence I can change the font to Arial, where the characters are in.

Are there solutions for this?

**Comment by ceesvanegmond** [comment]
All the unknown characters are not displayed correctly. Any idea how to solve this?
![img_3838](https://cloud.githubusercontent.com/assets/883497/7543870/596bfbb8-f5c8-11e4-9695-32c4766aecf5.JPG)

**Comment by jorenverspeurt** [comment]
Same here. I'd guess changing the default font or installing a new one that does include those characters would solve it but I don't know how to do that yet.

**Comment by jorenverspeurt** [comment]
Even in the default theme you can change the font to Arial, in Settings - Appearance - Skin - Fonts there's default and Arial. I do think it would be better if the default font for the skin was one that was a little more complete...

**Comment by superkhau** [comment]
Changing the font in Settings, Appearance, Skin, Fonts from `Default` to `Arial` worked for me.

Thanks @jorenverspeurt. 👍
