### ISSUE TITLE
Enable joystick support

### ISSUE THREAD

**Issue by el-Salmon** [osmc/osmc#162]
To get Kodi control from my gamepad in Raspberry Pi 1, I need Kodi be compiled with joystick support in OSMC. The osmc/package/mediacenter-next-osmc/build.sh script is using:  --disable-sdl --disable-joystick. Is is possible to remove these lines?

**Comment by samnazarko** [comment]
SDL is going to get ripped soon from Kodi I believe. I think there is work on a unified input system.

**Comment by el-Salmon** [comment]
I don't know how to compile Kodi in OSMC. Is just run the build.sh script?

**Comment by Sebubu** [comment]
+1

Similar issue in RecalBox: https://github.com/digitalLumberjack/recalbox-os/issues/12

**Comment by casperklein** [comment]
+1

**Comment by Relys** [comment]
Any progress on this issue? I really don't want to emulate keyboard in sixad because I want to be able to use the joysticks for Luna (moonlight-embedded plugin) and RetroPIE. :/

**Comment by samnazarko** [comment]
I do not have a joystick to test functionality.

Kodi 17 test builds are available. RetroPlayer will be merged soon and may remedy this. I still do not know if the original author of this issue resolved actually resolved his situation removing --disable-joystick. Does it work for you?

**Comment by samnazarko** [comment]
Support for controllers / joysticks will land in Kodi Krypton, and this is not an OSMC issue.
