### ISSUE TITLE
Kernel Header missing architecture mach include files

### ISSUE THREAD

**Issue by mometto** [osmc/osmc#167]
Tevii's DVB drivers fails to build (with headers installed) with error:
> ./arch/arm/include/asm/barrier.h:41:27: fatal error: mach/barriers.h: No such file or directory

Copying the architecture specifc folder from source fixes it:
> sudo cp -r /usr/src/rbp2-source-3.18.10-1-osmc/arch/arm/mach-bcm2709/include/mach/ /usr/src/rbp2-headers-3.18.10-1-osmc/include/.

I've documented the workaround in https://discourse.osmc.tv/t/tevii-dvb-s2-662/1424 but it would be nice to have it fixed in the headers!

I've also confirmed the issue and the workaround for rbp1 and rbp2

Thanks!

**Comment by samnazarko** [comment]
Debian sources are packaged in the official manner (make-kpkg). I have had issues myself building modules after installing header or source packages that have not presented when building against the vanilla source tree itself. 

Can you take a look at package/kernel-osmc and let me know if you can spot any obvious packaging error? As I say, we're following the upstream (Debian) method of packaging the kernel, but I have also seen firsthand it's not quite right.

**Comment by mometto** [comment]
Yes the issue might well be upstream as I've seen online very similar issues on other debian based dist and different ARM hardware.. Or perhaps something missing in make-kpkg options or config (trying to dig further...).. 

What about unpacking/add missing folder/repack the same way you do for the image?

**Comment by samnazarko** [comment]
>What about unpacking/add missing folder/repack the same way you do for the image?

I'm surprised someone spotted that. It's possibly a better idea to use make modules install MODULE_PATH= and package it that way. Will keep this open.

S

**Comment by mometto** [comment]
Not sure if it helps as they build in another way but the archlinuxarm kernel had the same issue as described here: https://www.raspberrypi.org/forums/viewtopic.php?f=53&t=98743

And it seems it got fixed by this commit (which effectively copy the right folder): https://github.com/archlinuxarm/PKGBUILDs/commit/b6581fbae225ccdf6661c4bbafbf738de7a54c45

**Comment by samnazarko** [comment]
Not really because this is a PKGBUILD.
