### ISSUE TITLE
[Request] OSMC in Berryboot

### ISSUE THREAD

**Issue by C-Fu** [osmc/osmc#189]
Good day,

I'm not exactly sure if this is better to be done via OSMC itself, or via berryboot, but it would be wonderful (to me at least) if OSMC is available in BerryBoot via a squashfs file. I have no idea how to do that, so I have to ask and wait till someone in osmc or berryboot is able to spend a few mins converting and uploading it to berryboot sourceforge site :dancer: 

Cheers!

**Comment by samnazarko** [comment]
BerryBoot requires a shared kernel which has some implications..

SquashFS is read-only I believe? This would have implications for our update system

**Comment by C-Fu** [comment]
Yeah, I read somewhere that it's slightly different than NOOBS.

I personally prefer berryboot solely for the ability to add any OS at any time without emptying the SD card for each OS installation.

And AFAIK, while squashfs is readonly, I believe it's like

1. Download the OS .image128 / .image256 squashfs image to your sd card (read-only)
2. "install" the OS to your sd card (read-write)

There's an OpenELEC image for it as well which I use, and I can write to it after installation no problem. 

OS list: http://sourceforge.net/projects/berryboot/files/os_images/

**Comment by samnazarko** [comment]
This isn't achievable without a shared kernel and significant changes to our root filesystem.
