### ISSUE TITLE
Installer not working on OS X "El Capitan"

### ISSUE THREAD

**Issue by jbaanus** [osmc/osmc#194]
The output format of diskutil seems to have changed in El Capitan (OS X 10.11) to following format:

```
/dev/disk5 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *16.0 GB    disk5
   1:             Windows_FAT_32 NO NAME                 254.8 MB   disk5s1
   2:                      Linux                         15.8 GB    disk5s2
```

Seems like the expected format does not have the whitespace at the beginning of lines?

**Comment by samnazarko** [comment]
Thanks. Will fix shortly.

CC @srmo 

We also need to move to Qt 5 for modern OS X builds
