### ISSUE TITLE
[Request] Add "divider" item type for the home menu configuration tools.

### ISSUE THREAD

**Issue by jsgrant** [osmc/osmc#205]
It'd be nice to have a "divider" type or similar, so one can have a nice non-selectable way to divide menu and sub-menu items. My current 'solution' for this is to add a menu entry that is soley a series of underscores; It works okay, but by no means is the preferable option.

**Comment by samnazarko** [comment]
GitHub is for reporting bugs rather than feature requests. Please start a post on our forum.
