### ISSUE TITLE
OSMC July update: Cannot change timezone (list selection impossible)

### ISSUE THREAD

**Issue by zilexa** [osmc/osmc#207]
Raspberry Pi 2 with latest image from homepage installed (today), updated to latest via My OSMC (today). 

Reproduce:
1. go to Settings > Appearance>International
2. select Region
3. a popup with black background appears with all region options. You can hear the UI clicking sound but no color change and when you hit OK, it seems nothing was selected: you are stuck in the default region (USA).

It is hard to know what has been selected (yellow) but in this particular case, nothing is yellow.

**Comment by samnazarko** [comment]
Is this still an issue?

**Comment by zilexa** [comment]
This is no longer an issue.
