### ISSUE TITLE
How does USB gigabit adapter work for crystalbuntu2?

### ISSUE THREAD

**Issue by t2man79** [osmc/osmc#209]
I connected USB ethernet adapter to my ATV1 (crystalbuntu 2 / kodi 14.2), but it doesn't work. I think kernel doesn't support the driver. I tried to install its driver from the official website, but it didn't make success. The driver is ASIX88178. Any comments are greatly appreciated! (the driver comes from http://plugable.com/2010/10/18/howto-asix-88178-usb-ethernet-adapter-on-ubuntu-10-10-linux/)

**Comment by samnazarko** [comment]
This is not an OSMC issue, so I have closed this. You may have more luck on the forum.
