### ISSUE TITLE
Run apt-get autoremove periodically

### ISSUE THREAD

**Issue by ranisalt** [osmc/osmc#210]
Sometimes with upgrades or removals, packages are left behind that do not need to keep installed. It notably happens always after kernel upgrades. It would be nice if this space was freed, as eventually (even after a very long time) it will fill up the entire space of the SD card.

I suggest it is run after an update of the sources list, but I'm not sure where you would prefer it, so I chose not to fork.

Thanks!

**Comment by samnazarko** [comment]
This is already planned when we revamp the way upgrades are displayed. 

This will be added for updates conducted via My OSMC, but not invocation of dist-upgrade via the CLI. I am of the opinion that command line upgrades inform the user of deprecated packages and as such those upgrading via the command line should be comfortable enough to run autoremove, but I would be interested in your thoughts.

**Comment by ranisalt** [comment]
Good, because every old kernel installed occupies a good 60 megabytes and I use a 4G card. I figured it could also be run on a cleaning script.

I am a command line user, but maybe someone that does not can have problems with this.

**Comment by samnazarko** [comment]
I believe this is addressed in

https://github.com/osmc/osmc/commit/9ac9304b596efbbcf0fa09c0ddccf22efbd6c546
https://github.com/osmc/osmc/commit/5e04186bcbfd4130e86594df6f6f62a31b545c56

Please close if happy. This will auto-remove kernels by default after upgrade. This won't work for dist-upgrade via command line, but we assume they are power users anyway.
