### ISSUE TITLE
equivalent package of libraspberrypi-doc?

### ISSUE THREAD

**Issue by joolswills** [osmc/osmc#219]
Does pi2 / debian based OSMC have a libraspberrypi-doc equivalent - it has its own package opt/vc development headers/libs (rbp-userland-dev-osmc) but this doesn't include /opt/vc/src which is included on raspbian as libraspberrypi-doc

The emulator xrorar requires /opt/vc/src/hello_pi/libs/ilclient/ - it would save us having to include this manually in RetroPie if osmc had a package.

(I have added support so retropie now compiles correctly on OSMC)

**Comment by samnazarko** [comment]
Hi

I have seen https://github.com/RetroPie/RetroPie-Setup/commit/abfe84a80eaa951e8d03b28a64daac134b46839f. I have now added a 'rbp-userland-src-osmc' package for you. It won't be available in the OSMC APT repository just yet however.

RetroPie looks to be proving quite popular with OSMC and we would like to add this to our App Store. Should I look at the 'RetroPie-Setup' repository for guidance on this? 

Keep up the good work

**Comment by joolswills** [comment]
Thanks! I shall keep an eye, and once the package is available, will switch to using that package.

Feel free to dig around.

Regarding the way our project is distributed - we don't have any prebuilt binaries archives for jessie yet, but will do in the future- so everything has to be built from source from the retropie-setup script. That can take a while to build everything (unless people selectively install stuff).

**Comment by samnazarko** [comment]
The package will be available later this afternoon

Sam
