### ISSUE TITLE
Graphics - menu render problem

### ISSUE THREAD

**Issue by asaljaz** [osmc/osmc#220]
Hi
I've tried to install the OSMC skin on Kodi 14.2 and 15.1 (fresh, clean install) on two different machines, yet I always encounter a graphics bug which causes the screen to render improperly (see the picture), but this only occurs on the main screen, while screens like 'Settings' are rendered normaly and can be worked with. In every case there is a black background, for which I'm unsure if it's supposed to be that color.
I've made sure that each system has the latest drivers for its graphics card.

![osmc_graphics_bug](https://cloud.githubusercontent.com/assets/14282724/9878948/791a63c4-5bc5-11e5-84d8-a231594d8fa0.png)

**Comment by samnazarko** [comment]
Hi

I can confirm we are seeing weird artifacts on the skin as well. We will take a look at this

Cheers

Sam

**Comment by KODeKarnage** [comment]
Was a case of a single missing file.

Fixed with a commit last night.
