### ISSUE TITLE
Can't cancel BT pairing 

### ISSUE THREAD

**Issue by myappleguy** [osmc/osmc#221]
I tried pairing my iPhone to OSMC running on RPI2 and on the iPhone I got a failure to pair and on the Pi  I get a circular loading animation that I can not get to stop. Is there a key sequence that can cancel this action?

**Comment by samnazarko** [comment]
Is this still an issue?

**Comment by myappleguy** [comment]
Sorry I flashed to something else and am no longer using this software because I could not get it to work right for me.

**Comment by samnazarko** [comment]
Cool -- we've improved BT support significantly over the last couple of months, so hopefully this is resolved.
