### ISSUE TITLE
Saltstack

### ISSUE THREAD

**Issue by jangregor** [osmc/osmc#222]
Current os-release breaks os-detection as Debian for saltstack:
salt '*' grains.items
...
    os:
        OSMC
    os_family:
        OSMC

By results of this all debian-based features of saltstack are not working. Please fix distribution os-release to reflect that OSMC is a debian-based OS.

**Comment by jSherz** [comment]
I think the following would act as a workaround:

`salt -G 'os:Debian.*' grains.items`

**Comment by samnazarko** [comment]
If this is still an issue, please suggest an appropriate fix for OSMC.

**Comment by nkuttler** [comment]
Fwiw, I've created a PR to fix this in salt, which seems to be the preferred approach. https://github.com/saltstack/salt/issues/62198

**Comment by samnazarko** [comment]
Thanks. Can you let me know the current use case with OSMC?

Sam

**Comment by nkuttler** [comment]
@samnazarko nothing apt related works with saltstack on OSMC. If you look at my pull request it's trivial, it simply maps "OSMC" to "Debian" for an internal saltstack value, that fixes the problem and is the same mechanism that is used for other distros.

**Comment by nkuttler** [comment]
Btw, this was fixed now in salt, https://github.com/saltstack/salt/pull/62199#issuecomment-1250351128, should probably be in the next release.

**Comment by samnazarko** [comment]
Thanks for confirming
