### ISSUE TITLE
Installer should ask "are-you-sure" before starting to download

### ISSUE THREAD

**Issue by sasoiliev** [osmc/osmc#224]
The "Do you want to image the device you selected previously? OSMC is not responsible for loss of personal data" message appears after OSMC has been downloaded.

On slow connections this might take some time, so IMO it makes more sense to ask for confirmation first and only then if confirmed to start downloading and then proceed to install on the selected device.

**Comment by samnazarko** [comment]
Agreed,

Can you submit a patch to change this?

**Comment by sasoiliev** [comment]
I could try to, but I can't commit to it.

**Comment by samnazarko** [comment]
You can fork OSMC and submit a pull request of any changes.

We are redesigning the host installer so there may be some delays in implementing this

Sam

**Comment by sasoiliev** [comment]
Sorry, I guess I wasn't quite clear. I'm aware that I can submit a pull request, what I meant was that I'm not sure that I'll have the time/skill/energy to come up with a patch.

Regards
