### ISSUE TITLE
KODI: Default debug level set to DEBUG so it is impossible to disable logging or set it to reasonable level

### ISSUE THREAD

**Issue by lexa2** [osmc/osmc#227]
Kodi is coded in a way so you can't decrease debug level using advancedsettings.xml. It seems that Kodi as shipped with OSMC have default log level set to debug at the build time. Having my RPi2-based mediacender up and running for some weeks I found that 4GB SD card is full having /home/osmc/.kodi/temp/kodi.log occupy 2.7Gb. Cleaned, added advancedsettings.xml setting loglevel to 0, restarted kodi, made sure that logging is turned off in UI - and still have all debug level infos dumped into kodi.log.

As a short-term fix I redirect kodi.log to /dev/null but it would be good if OSMC would fix this properly by building Kodi with default log level set to -1 or 0. That way it won't fill up all the space on the SD card while it would still be possible to increase it in case it's needed using GUI or advancedsettings.xml.

**Comment by KODeKarnage** [comment]
fixed in latest build

update
