### ISSUE TITLE
Is 'wheezy' supported?

### ISSUE THREAD

**Issue by trajano** [osmc/osmc#235]
I am trying to set this project up to run on Travis, but it seems to be hardcoded to use "jessie" even though 'wheezy' is supported according to the common.sh script.

**Comment by samnazarko** [comment]
OSMC is based on Debian Jessie, and that's expected for root filesystem on target. You can use wheezy for building, but obviously buildfs and target filesystem is Jessie.

Never tested with Travis -- but we use Jenkins here.

**Comment by trajano** [comment]
do you have your jenkins set up for building pull requests?

**Comment by samnazarko** [comment]
No -- as OSMC consists of several smaller internal projects and cannot be built in a single build step.

I'm going to close this as it's not an issue, rather a query. Questions are best asked on our forum at https://discourse.osmc.tv.

**Comment by trajano** [comment]
NP thanks for the link to the forum.  I'll see what is needed for building this from scratch, I can't find the instructions anywhere anyway.

**Comment by trajano** [comment]
I think there may be something needed on the build scripts to force it to download a version of deboostrap with jessie then.

https://travis-ci.org/trajano/osmc/builds/89370970#L291 shows what was retrieved.  Unless wheezy should not be considered a proper build system.

**Comment by samnazarko** [comment]
One reason I started using Jessie is that QEMU (which can be used to build ARM packages on x64 without CC) was very out of date, so I went for latest and greatest at the time. 

Just download 'debootstrap' Deb from Jessie repo and use dpkg -X debootstrap.deb / to extract to / and replace the wheezy one.

**Comment by trajano** [comment]
Ok let me figure out what you mean by that.  I haven't built a system like this before.

**Comment by samnazarko** [comment]
This is best discussed on our forum and other users may benefit from this. I am happy to show you how to 'build' different parts of OSMC, but I would not recommend plugging in to a CI like Travis or Jenkins until you are familiar with how it all fits together.

**Comment by trajano** [comment]
No probs.  Do you mind creating one in https://discourse.osmc.tv/c/development-testing I can't seem to create a new topic 

"How to build OSMC"

**Comment by samnazarko** [comment]
Posting in the General Discussion section is fine for now.

________________________________

**Comment by samnazarko** [comment]
Just saw your post about MINIX. Will reply now

________________________________

**Comment by trajano** [comment]
Thanks.
