### ISSUE TITLE
Default apt configuration breaks some third party repositories

### ISSUE THREAD

**Issue by remydavid** [osmc/osmc#236]
I had trouble installing openHAB on OSMC using apt-get.
Turns out the default OSMC apt configuration has a problem with some third party repos (bintray in openHAB case).
In short, the custom OSMC user agent is rejected by the repo server. I commented the user agent line in /etc/apt/apt.conf.d/00-osmc-user-agent, and everything is fine now.

More info here : https://github.com/openhab/openhab/issues/3407

**Comment by DBMandrake** [comment]
I don't think this is a bug in OSMC, I would think that this is an issue with the configuration of openHAB's APT repo servers - they should not be rejecting a connection based on the http user agent.

We have not seen reports of this issue with any other 3rd party Repos. I would contact them to see why they are rejecting a connection based on user agent.

**Comment by remydavid** [comment]
openHAB package is hosted on bintray, I agree this is probably an issue with bintray server configuration. However since a lot of third party repos are hosted on bintray this could impact a lot of users. I will contact bintray support to see if they can help, however, it is probably simpler and more standard to just remove the custom OSMC user agent from the apt conf.

**Comment by remydavid** [comment]
The bintray support published a fix yesterday, less than 8 hours after I contacted them, they are incredible !

The problem was on their side, here is their answer :

"Thank you for contacting us, and for providing this information. We believe we have isolated and fixed the issue you were experiencing. The fact that you weren't able to use wget to resolve the debian file was that the URL you were using was malformed, which is also the reason you received a 403 with apt-get. The problem has indeed originated from the custom user-agent used by the apt client, and is related to the way the debian client follows redirection to our CDN.

We have uploaded a fix, and you should now be able to install debian packages using apt-get"

**Comment by DBMandrake** [comment]
Thanks for letting them know about the issue - that's a pretty quick turnaround time.

**Comment by samnazarko** [comment]
+1

Thanks!
