### ISSUE TITLE
OSMC Skin support for PleXBMC

### ISSUE THREAD

**Issue by ralin3** [osmc/osmc#237]
Hi,
Would it be possible to add support for PleXBMC to the default skin?
As seen here
hippojay/plugin.video.plexbmc#95

**Comment by samnazarko** [comment]
Hello

What would adding support for PleXBMC involved? i.e. what happens currently?

**Comment by ralin3** [comment]
Take a look at this thread for more info regarding how and why:
http://kodi.wiki/view/Add-on%3aPleXBMC#PleXBMC_Skins
http://forum.kodi.tv/showthread.php?tid=175995

Basically, you're missing info from plex's library, and with added support you can get it all native in Kodi.
