### ISSUE TITLE
Unable to boot with PARTUUID

### ISSUE THREAD

**Issue by fonini** [osmc/osmc#241]
Hi, after the November update, I'm no longer able to boot with ````PARTUUID=xxxx```` on my ````cmdline.txt````.
Changing it to ````/dev/sda1```` works fine.

Is there a fix for this problem?
Thanks

**Comment by DBMandrake** [comment]
PARTUUID is no longer supported. Use UUID instead.

Unfortunately there is a bug in the current November kernel that is preventing UUID support from working as well. If your device is a Pi 2 or Vero there is a workaround you can use here until we put out an update:

https://discourse.osmc.tv/t/rpi2-initrd-corruption-after-november-updating/10435/17?u=dbmandrake

**Comment by fonini** [comment]
I'm using a PI 1. I'll wait for the update then.
Thanks for the awesome work!

**Comment by DBMandrake** [comment]
I have now built a working version of the Pi 1 external initramfs, if you would like to test it and it's UUID support please check the thread I linked to above. Thanks.

**Comment by fonini** [comment]
I'll test when I get home and I let you know. Thanks!
