### ISSUE TITLE
VERSION OSMC

### ISSUE THREAD

**Issue by lavvy** [osmc/osmc#243]
Please won't it be nice to version osmc.  I am thinking that osmc has actually come to the level it should be versioned.  It will help track development.

**Comment by samnazarko** [comment]
OSMC has a version in /etc/os-release; and trackable in base-files-osmc. If you wish, I can 'tag' releases on GitHub in the future.

**Comment by lavvy** [comment]
Yeah,  sam please it will be nice to tag the releases in github

**Comment by samnazarko** [comment]
From now on, I will tag our releases.

Sam
