### ISSUE TITLE
[wish] Shutdown when movie is played (done) 

### ISSUE THREAD

**Issue by LipkeGu** [osmc/osmc#245]
It would be nice to have an option where i can enable via "power off" icon in the main menu "shutdown when done". for example

we play a movie in the night when going to sleep, enable this option after starting the movie... the movie is done and im dreaming (sleeping) and the device is shutding down ... :) Maybe this option can be configureable to restrict this to a specifid time range (night) 10pm - 6am ...:)

**Comment by jackmawer** [comment]
I believe in the power menu there is actually a 'Shutdown Timer' which you can set to auto-shutdown after a time period.
Hope that helped!
