### ISSUE TITLE
CEC stopped working of RBPI2

### ISSUE THREAD

**Issue by vmorilla** [osmc/osmc#247]
Hi, tonight my remote suddenly stopped working. I've tried with different HDMI cables with no success. When I tried to run the cec-client I found that cec libraries cannot be found. The content of the /etc/ld.so.conf.d is as follows: arm-linux-gnueabihf.conf, libc.conf, rbp.conf

None of these files include the path to /usr/osmc/lib where libcec files can be found. So, I added a new file to the /etc/ld.so.conf.d dir with the path to /usr/osmc/lib and ran ldconfig. Now, I can run cec-client but still, kodi does not react to the remote. The output of cec-client -m is as follows:

starting a monitor-only client. use 'mon 0' to switch to normal mode
No device type given. Using 'recording device'
CEC Parser created - libCEC version 3.0.1
no serial port given. trying autodetect:
 path:     Raspberry Pi
 com port: RPI

opening a connection to the CEC adapter...
DEBUG:   [              71]     Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [              71]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [              71]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [              71]     InitHostCEC - vchi_connect succeeded
DEBUG:   [              72]     Open - vc_cec initialised
DEBUG:   [              72]     logical address changed to Free use (e)
NOTICE:  [              73]     connection opened
waiting for input
DEBUG:   [              73]     processor thread started
WARNING: [            2526]     unhandled response received: opcode=0 initiator=e destination=0 response=1
WARNING: [            2526]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            2527]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            2527]     unhandled response received: opcode=0 initiator=
e destination=0 response=f
WARNING: [            2528]     unhandled response received: opcode=82 initiator=e destination=f response=f
WARNING: [            4029]     unhandled response received: opcode=82 initiator=e destination=f response=f
WARNING: [            5530]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            5531]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            6531]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            6532]     unhandled response received: opcode=0 initiator=e destination=0 response=f
WARNING: [            6533]     unhandled response received: opcode=82 initiator=e destination=f response=f

Thanks in advance!!!

**Comment by samnazarko** [comment]
The issue is unrelated. cec-client needs to be compiled to use the OSMC lib path. Adjusting /etc/ld.so.conf.d as you did will have undesirable effects in the future.

While cec-client can be problematic, libCEC within Kodi is confirmed working by other users. I recommend you power off the TV from the mains for 10 minutes. If the issue persist, I would start a forum post unless you find a bug that needs addressing.
