### ISSUE TITLE
[Feature Request] add a graphical Remote control button allocator

### ISSUE THREAD

**Issue by Mannshoch** [osmc/osmc#248]
RetroPie has a nice tool to allocate buttons to functions.

Please add something alike this OSMC to allow correcting miss located buttons.

At moment i have to use the remote from TV and from my USB DVB-C tuner to get me all needed function. Some only work on the TV remote and some only work on the remote from my USB tuner.  I tried to get through this lirc thing but I do not understand how it works and how I have to correct something with that on my USB remote control.

**Comment by Mannshoch** [comment]
Was a bit creative and created an example how it could look like
 :-) 

![kodi-remote](https://cloud.githubusercontent.com/assets/7795891/11959785/939d70a4-a8cf-11e5-89d1-4dc9af7d6023.png)

**Comment by samnazarko** [comment]
At the moment, this is not trivial, because not every remote goes through LIRC. Remote learning is a feature I would like to see, but for now we can't think of a good way to achieve this.

**Comment by Mannshoch** [comment]
How does the tool from RetroPie work? 
If I think over it, it work without lirc. because all of their remote goes through USB.

The hope never die

**Comment by samnazarko** [comment]
I haven't used RetroPie, but my guess would be it is managing it at a HID level and there is in fact a sense of uniformity (e.g. XPad/XboxDrv). The reason this is challenging is because:

* Some remote signals come via USB
* Some remote signals come via GPIO

Then, some remotes use different RC6/RC5/NEC protocols. Then we have repeat filters to handle etc. If we achieve this, we've effectively re-developed LIRC. Remember that Kodi listens to an LIRC socket, our eventlircd one (which is a uinput aggregator), so we would need to perform button configuration at an LIRC or eventlircd level (depending on the remote). This is very difficult to automate. 

I don't think this can be achieved in the near future given the state of HID in Linux.

**Comment by Mannshoch** [comment]
That seems to be really complicated. 

While browsing through Web I got on some pages hints for a new HID tool named libinput which is in development. Could that be the new tool we wait for?

**Comment by cricket007** [comment]
I think this can be closed. 

Upcoming in Kodi v17 - [Configure Controllers](http://kodi.wiki/view/HOW-TO:Configure_controllers)

![controller](http://kodi.wiki/images/thumb/8/8d/Controllers_8.png/800px-Controllers_8.png)

**Comment by Mannshoch** [comment]
Thanks for the Work. but the trigger for this Idea where problems with my Remotecontroler vor the DVB-T USB-Stick (the OK button had to be remapped to ENTER, what a hell) . I thougth only a bit further to get an overall-remote-solution. But at moment there are only game-controler to set up (If I could see it right, could not test it).

**Comment by cricket007** [comment]
As long as your remote is detected as a lirc device, you can use the first link to the keymap editor addon

**Comment by Mannshoch** [comment]
But  in this Keymap thing im only able to map a button to specific events. I was not able to replace all events which use ENTER with OK.

**Comment by cricket007** [comment]
> I was not able to replace all events which use ENTER with OK

Not in one command or input, no. You would have to go through every menu to edit all mapped buttons that correspond to the remote. 

You may be able to use that addon, hit save without editing anything, that generates  `~/.kodi/userdata/keymaps/gen.xml`, and you can edit that by hand, but you'll need to know the event codes for your remote buttons.

**Comment by Mannshoch** [comment]
If config file editing is a proper Solution, this "Configure Controlers" tool isn't also needed
 :-)

**Comment by cricket007** [comment]
To many people having a somewhat automated GUI is more preferred than hunting down key-codes and edit config files by hand. I haven't tried a test build of Kodi v17, so I can't speak to it's functionality.
