### ISSUE TITLE
start signing with gpg, stop using md5

### ISSUE THREAD

**Issue by ThomasWaldmann** [osmc/osmc#251]
as you may know, md5 is not secure any more since years (there are hash collisions and it is not very difficult to find them).

On https://osmc.tv/download/ only md5sums are given, so you only offer a insecure way to verify your images.

There are 2 ways to fix this:

a) just use sha256sum - same mechanism, just another hash that is still secure. sha1 is broken since recently also, don't use sha1. This still has the problem that if you can tamper the binary you can just re-compute the hash for the bad binary and tamper the wiki page also.

b) sign your images with GPG and publish your key fingerprint on a trusted location.
This would be the preferable way as there is no way to forge a GPG signature without having the secret key.

**Comment by samnazarko** [comment]
Hi there,

Another user has already pointed out that MD5 is insecure on Twitter. As such, I have made plans to replace the image listing with SHA256 sums. I plan to keep MD5 however as some people still use it, and while predictable, it is better than nothing.

I'd appreciate a PR to adjust our buildsystem to produce the new sums.

**Comment by ThomasWaldmann** [comment]
Well, continuing to use md5 just means you give users a method to "check" the image that is known to be unable to detect tampered images. Think about it.

**Comment by samnazarko** [comment]
Could you link to a demonstration where a disk image has been tampered to "match" a known good MD5 as mentioned in your original issue? 

Remember that Downloads are geographically distributed, so this should serve as an element of verification as well. 

I have suggested we continue to offer MD5 alongside a more secure checksum, SHA256, but you seem to not agree with this. I'm not sure what more can be done than this for verification purposes. Checksums and images are regionally distributed, and while there could theoretically be tampering, an element of trust always has to be placed in the image vendor.

**Comment by KODeKarnage** [comment]
I dont get this sort of halfway paranoia. If someone is in a position to tamper with the disk image, surely they would very often be in a position to change the md5 OR sha256 at the same time?  Seems a very specific type of infiltration to be concerned about. I mean, really THINK about it.

**Comment by alistair-broomhead** [comment]
I've been watching this discussion, and the need to add my own $0.02 has become overwhelming. MD5 is not cryptographically secure any more. This is well known, you can relatively easily add padding to get a matching checksum, and so it doesn't really act as proof against tampering.

With that in mind, the checksum on a download page is not really a measure against tampering. To prevent tampering you would cryptographically sign the download and the page, probably but serving everything over https. The point of a checksum is therefore to detect random corruption. For this md5 is fine, so I'd keep it, maybe offer sha too, but mainly look at serving over https to get the benefits of SSL.

**Comment by samnazarko** [comment]
+1

>For this md5 is fine, so I'd keep it, maybe offer sha too, but mainly look at serving over https to get the benefits of SSL.

We are not offering MD5 checksums as a form of security, but rather as a quick way of checking if your browser has corrupted the Download or you have an incomplete image.

**Comment by ThomasWaldmann** [comment]
ok, so I suggest you read b) in my original post.

it is known there are parties who tamper stuff, so we do not only need a measure against accidential corruption, but a measure against tampering.

offering a md5 is giving people a potential wrong feeling of "yes, I made sure i got the right thing".

**Comment by samnazarko** [comment]
>offering a md5 is giving people a potential wrong feeling of "yes, I made sure i got the right thing".

No it is not. We recommend that it is only used to verify file integrity, not authenticity.

I will explore the option to use GPG signing in the future, but I am still uncertain how this will improve security as:

* Files are available via HTTPS
* Files are distributed from a build server. If the build server distributes a GPG key to a 'trusted' location this does not indicate the manufacturer of the image has not been compromised nor does it prevent forgery.

Your issue title is misnamed: the deprecation of MD5 checksum is not related to the issue you have just described and migrating to another checksum algorithm will not help address this.

**Comment by ThomasWaldmann** [comment]
https is nice to avoid tampering on the wire (if implemented correctly, which is problematic due to all the weaknesses in the CA system, in DNS, ...), but ONLY for that. if somebody hacks into your server and modifies the binary (and the md5/shaXXX), https does not help you.

the whole point of using gpg is that the signature can only be generated by the release signing person who has the secret key and unlocks it with his secret/secure passphrase at release time. so even if somebody hacks into your server and would be able to modify binary and signature, he can not create a new signature with the release signing key.

of course, the release signing should be done on a very much trusted machine by a very much trusted person. And I think it should be done manually, not fully automated by a build server.

The meaning of the signature is that the release signer is confident that the release is as it should be and the signature assures integrity as well as authenticity. As long as your private key is not compromised, you can simple check even years later that all releases are still as they should be.

A hash can always be re-computed to match a tampered binary and you have no way to check who/what computed that hash value and when...

Just have a look at projects like "Tails" or the Debian package system, they are highly security aware and also aware of what adversaries can do. And they sign their stuff with gpg because they know a hash is not enough.

**Comment by samnazarko** [comment]
>if somebody hacks into your server and modifies the binary (and the md5/shaXXX), https does not help you.

Agreed.

>And I think it should be done manually, not fully automated by a build server.

This is problematic. This would slow down development and update cycles. There is also a question of how far the signature process should go: disk image, or filesystem, or even source tarballs? 

>the Debian package system, they are highly security aware and also aware of what adversaries can do

The Debian packaging system performs automatic signing of packages on import. This is not a manual step. The keyserver is a distributed form of key retrieval for clients, but in effect, an APT server performing signing operations could be compromised, rendering this useless until the key was revoked. I can offer signed images in the future, but this will have to be an automatic process. 

We do not have the man hours to manually sign every image and package produced. http://jenkins.osmc.tv/view/All/builds should provide an insight in to the pace of OSMC development.

**Comment by ThomasWaldmann** [comment]
Well, if you trust your build server enough (e.g. it is considered secure, it is really your build server, meaning that you and no 3rd parties control it), I guess you can make it sign for you if the manual process is impracticable.

**Comment by samnazarko** [comment]
Yes, the build environment can be considered secure. I will add this to my list and get it done in the near future

On 24 Dec 2015, at 16:39, TW <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, if you trust your build server enough (e.g. it is considered secure, it is really your build server, meaning that you and no 3rd parties control it), I guess you can make it sign for you if the manual process is impracticable.

-

**Comment by samnazarko** [comment]
We have moved to a new mirror direction system which can provide users with SHA1/SHA256/MD5 checksums on the fly for any file we serve.

I'll talk to @marktheis about getting this changed on our Downloads page.

**Comment by d1b** [comment]
@samnazarko it seems like the page to the downloads page wasn't done?

**Comment by samnazarko** [comment]
SHA1, SHA256 and MD5 are provided via the Download service.

**Comment by samnazarko** [comment]
Just to clarify, you can pull a SHA256 from http://download.osmc.tv/installers/noobs/root-rbp2.tar.xz?sha256 for example. 

MD5 is mainly on our website for integrity, rather than authenticity. We host many files but don't provide a direct list of checksums. 

You can also grab from HTTPS.

**Comment by d1b** [comment]
Thank you for clarifying. In that case perhaps it would be useful to have https://download.osmc.tv respond with a certificate that is valid for download.osmc.tv .

**Comment by samnazarko** [comment]
Yes -- we'll do this soon.
We also need to ensure that our mirrors are HTTPS-ready first.
