### ISSUE TITLE
Freezing gui on pi

### ISSUE THREAD

**Issue by leentorenvliet** [osmc/osmc#252]
Is there anyway to strip down the gui (e.g., of rendering pictures) so that it can get some performance on the raspberry pi 2?  Everytime I'm down a few clicks in a row, or scroll too fast it completely freezes for a couple of minutes and then resumes action. I really don't need pretty pictures.

**Comment by samnazarko** [comment]
This is not normal behaviour. Please start a forum post so we can get a better idea of the problem.

**Comment by leentorenvliet** [comment]
On 26-12-2015 22:20, Sam Nazarko wrote:
>
> This is not normal behaviour. Please start a forum post so we can get 
> a better idea of the problem.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/osmc/osmc/issues/252#issuecomment-167364087>.
>
Thanks for your prompt reply Sam. I'm not sure what you mean by "this is 
not normal behavior." Isn't this section meant to report
issues? I've installed OSMC on a Raspberry Pi 2. It had the freezing 
problem I described. I ran all available updates yesterday. It still 
freezes up when
browsing through the items in particular in the files section, sometimes 
for more than a couple of minutes. I'd be happy to
give more details, if I would know what would help. I was actaully 
hoping that others experience the same problems.

Leen

**Comment by samnazarko** [comment]
>Isn't this section meant to report issues?

This section is for reporting confirmed OSMC bugs. Until we confirm you are experiencing an issue that is an OSMC bug, you should post in the forums, which are more equipped to providing help and support.

> I was actaully hoping that others experience the same problems.

We are not seeing other users experiencing this issue.

**Comment by leentorenvliet** [comment]
On 26-12-2015 22:37, Sam Nazarko wrote:
>
>     Isn't this section meant to report issues?
>
> This section is for reporting confirmed OSMC bugs. Until we confirm 
> you are experiencing an issue that is an OSMC bug, you should post in 
> the forums, which are more equipped to providing help and support.
>
>     I was actaully hoping that others experience the same problems.
>
> We are not seeing other users experiencing this issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/osmc/osmc/issues/252#issuecomment-167364548>.
>
OK. Thanks for your help. I'll try the forums then.

Leen
