### ISSUE TITLE
[OBS] Build error (Suse, Fedora...)

### ISSUE THREAD

**Issue by malkavi** [osmc/osmc#258]
There are 1 "error" into the file 
https://github.com/osmc/osmc/blob/master/installer/host/qt_host_installer/versionselection.cpp

The function
bool VersionSelection::enumerateBuilds(QByteArray buildline)
doesn't return a bool value outside the "if". Missing "return false;"??

**Comment by samnazarko** [comment]
Thanks. Fixed and version bumped. Let me know if OBS doesn't build it still. For some reason OpenSUSE Tumbleweed is checked, but this repository doesn't show up on the OBS Project page. I'm not sure why. Perhaps an older version will work fine?

**Comment by malkavi** [comment]
I can't see Tumbleweed.
Have you go to: https://build.opensuse.org/project/repositories/home:osmc and have you try adding a new repo?

Home Project -> Repositories -> Add repositories

**Comment by samnazarko** [comment]
Hi Ivan,

I can't see it either. I suspect I've not set it up properly, as we've had this issue before.

I don't see Tumbleweed under repositories, so I go to Add Repository. But the option is greyed out.
![screenshot from 2016-01-08 15 53 14](https://cloud.githubusercontent.com/assets/932652/12202119/1420eba4-b620-11e5-8ee8-7a95d0dae174.png)

I tried editing repositories for both the package and the home project (although the package inherits from Home project).

I am not sure what I am doing wrong.

**Comment by malkavi** [comment]
mmmmm
Can you see Tumbleweed in the previous page at least?
If yes, try then the package's config. "osmc-installer > Repositories"
Are "Build Flag", "Publish Flag" and "Use for Build Flag" enabled for Tumbleweed?

Anyway I have tried the version I have in my repo and it's working with the new code ;)

**Comment by samnazarko** [comment]
It's not in the Repositories bit, so no Build/Publish/Use for build.

TeamViewer?

**Comment by malkavi** [comment]
I'm at work... XD
I have asked for Maintainer role ;)

**Comment by samnazarko** [comment]
I've accepted that. Cheers.

**Comment by malkavi** [comment]
Sorry, I have asked role for the package, not the repo... Done.

**Comment by samnazarko** [comment]
Approved again

**Comment by samnazarko** [comment]
BTW, as an aside: this guy suggests [1] that we use packman for OpenSUSE. Not sure if this is worth looking in to for the new installer in the future.

[1]: https://discourse.osmc.tv/t/osmc-installer-update-prompt/11681/8?u=sam_nazarko.

**Comment by malkavi** [comment]
Added Tumbleweed. (using the advanced interface)
Thanks!

**Comment by samnazarko** [comment]
Why did it need adding via Advanced?

Looks like it's compiling now: https://build.opensuse.org/package/live_build_log/home:osmc/osmc-installer/openSUSE_Tumbleweed/x86_64.

**Comment by malkavi** [comment]
I don't know why. As you have said It was selected in grey and It can't be removed. I have readded with the same name and done.
