### ISSUE TITLE
imon-pad seems not supported

### ISSUE THREAD

**Issue by sajov** [osmc/osmc#265]
hi there,
i'am new in kodi/osmc and lost in reading threads about imon-pad and lirc.
i found at least [package/eventlircd-osmc/files/lib/udev/rc_keymaps/rc-imon-pad](https://github.com/osmc/osmc/blob/master/package/eventlircd-osmc/files/lib/udev/rc_keymaps/rc-imon-pad). I tried many different lirc.conf for imon-pad without success.
It seem imon is already part of lirc core but with missing features. Do i also need key maps or other xml rather than the lirc conf?

thanks for any suggestion

**Comment by samnazarko** [comment]
Please start a forum post -- this for confirmed bugs only
