### ISSUE TITLE
Do not prompt for reboot unless Pi Config settings were actually changed

### ISSUE THREAD

**Issue by beRto-** [osmc/osmc#266]
Every time a user exits My OSMC > Pi Config, there is a prompt: "Please Note change to Pi Config require a restart." This prompt is provided, regardless of whether or not any changes were actually made. (In other words, the prompt still comes up if you directly cancel and exit the menu.)

I think osmc should check status, and only prompt if any settings were actually changed.

I searched the code base, but could not find the actual file where this prompt is initiated. So not sure where to start for implementing such a change.

**Comment by samnazarko** [comment]
Agreed about this feature and suggested it a little while ago

If possible, let's go for it.

Perhaps use MD5 to check config.txt before and adapted and if it has changed then only prompt for reboot

**Comment by beRto-** [comment]
Hi Sam - can you point to the code location that would deal with config.txt?

**Comment by samnazarko** [comment]
Check package-osmc/mediacenter-addon-osmc/src/script.module.osmc.piconfig

**Comment by beRto-** [comment]
@samnazarko I made some changes, but am having a few difficulties, mostly with github processes and how to setup OSMC for dev / testing. The modified OSMCSetting.py is attached (changed extension to .txt to upload).

Problems are:
1. Not sure how to compile / test this. I validated the functions using a simple test script, but did not run it properly in osmc. For every little change, would you normally rebuild a package and deploy to a vero / Pi to check? There must be a way to emulate on a local PC?
2. Indenting seems off when viewed in GitHub (although looks fine in official Python IDLE IDE). Maybe this is what you meant about ongoing problems with Python indentation and robustness. As is, I worry the indentation in the version I uploaded would not work properly.
3. Not sure how to submit a separate pull request covering just this change. I am not yet too familiar with GitHub, but it seems to me the change got mixed up / embedded in another open pull request I had made "weather - add location and time of last update #262". I've read several GitHub tutorials, but obviously am still not getting it right. Anywhere you can direct me for a definitive tutorial?


package\mediacenter-addon-osmc\src\script.module.osmcsetting.pi\resources\osmc

[OSMCSetting.txt](https://github.com/osmc/osmc/files/111091/OSMCSetting.txt)

**Comment by beRto-** [comment]
Still not sure how to test this properly (#1) or why the indenting seems off (#2). But I think I figured out the "branching" needed to segregate different changes (#): new pull request submitted: #267

**Comment by samnazarko** [comment]
To test the add-on, you can build and install it:

cd package/mediacenter-addon-osmc
make

Then you will get a mediacenter-addon-osmc.deb which you can install with sudo dpkg -i mediacenter-addon-osmc.deb.

>2. Indenting seems off when viewed in GitHub (although looks fine in official Python IDLE IDE). Maybe this is what you meant about ongoing problems with Python indentation and robustness. As is, I worry the indentation in the version I uploaded would not work properly.

Ask @KODeKarnage about this. He does most of the work on the add-on. I just use a Terminal to edit.

>Not sure how to submit a separate pull request covering just this change. I am not yet too familiar with GitHub, but it seems to me the change got mixed up / embedded in another open pull request I had made "weather - add location and time of last update #262". I've read several GitHub tutorials, but obviously am still not getting it right. Anywhere you can direct me for a definitive tutorial?

Create a separate branch off master for each pull request.

**Comment by beRto-** [comment]
Thanks @samnazarko - so you do all your development in a Linux environment? I don't have one handy, and am working in Windows 7. Is there an equivalent approach that could work here?

@KODeKarnage - are you using a particular IDE for development? I usually use Eclipse for Python. Or sometimes just Python's IDLE, if it's just a single file script. But, as mentioned, the indenting seems off in the resulting file I uploaded. Do you know if the tabs you use are standard 4 spaces? I'll double-check on my end.

I created a new branch and resubmitted as pull request #267

**Comment by samnazarko** [comment]
Everything under Linux. You can clone OSMC sources and build on OSMC directly. A few team members use this approach.

Let us know if you need help etc in OSMC chat. We are around there more

Sam

Sent from a mobile device, so please excuse the brevity of this reply

On 31 Jan 2016, at 18:32, beRto- <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @samnazarko<https://github.com/samnazarko> - so you do all your development in a Linux environment? I don't have one handy, and am working in Windows 7. Is there an equivalent approach that could work here?

@KODeKarnage<https://github.com/KODeKarnage> - are you using a particular IDE for development? I usually use Eclipse for Python. Or sometimes just Python's IDLE, if it's just a single file script. But, as mentioned, the indenting seems off in the resulting file I uploaded. Do you know if the tabs you use are standard 4 spaces? I'll double-check on my end.

I created a new branch and resubmitted as pull request #267<https://github.com/osmc/osmc/pull/267>

-

**Comment by KODeKarnage** [comment]
@beRto, I use SublimeText exclusively. I prefer to use tabs than 4 spaces.

**Comment by beRto-** [comment]
@samnazarko @KODeKarnage  I think I got this sorted now: #268 

- cleaned up the spacing (used tabs, not spaces)
- started a separate branch, so this md5 change is isolated
- able to build / test locally on my RPi2, and it worked fine
