### ISSUE TITLE
WPA2 passphrase with special characters fails to associate

### ISSUE THREAD

**Issue by andrewjamesbrown** [osmc/osmc#270]
I have a problem with my wifi network not connecting with the latest OSMC update.  It works fine after multiple reboots subsequent to the initial install, but fails to connect after the OTA update has completed.  Immediately after the OTA update, things work, but wifi fails to connect after the first (and subsequent) reboot.

My wifi ssid contains a '-' character, but no spaces.
My wifi passphrase contains both special characters (/, |, \, !), and spaces.
I noticed in `/var/lib/connman/*/settings`, the `\` character is escaped, so it shows up as `\\`.

Any attempts to connect via GUI fail, as do manual connection attempts using `connmanctl` over ssh.  Purging the relevant directory in `/var/lib/connman/` also fails to kickstart things.

I've successfully added a wifi network without spaces or special characters in either SSID or passphrase to work around this for now.

**Comment by samnazarko** [comment]
Please start a forum post. This issue tracker is for confirmed problems
