### ISSUE TITLE
Add new remote lirc config (Dell Travel Remote)

### ISSUE THREAD

**Issue by hhromic** [osmc/osmc#275]
Hello,
I created a new lirc remote configuration file (```/etc/lirc/dell-travel-remote-lircd.conf```) for my Dell Travel Remote [1] and its corresponding PNG image file (```/etc/lirc/dell-travel-remote-lircd.png```). I tested them successfully on the latest version of OSMC and would like to contribute them to the main OSMC remotes collection.

What is the official way to contribute remote configuration files?

Cheers,
Hugo.

[1] http://www.redplanettrading.com/images/D/nu853_overview_800.jpg

**Comment by DBMandrake** [comment]
If you're comfortable using git, you could submit a pull request. The package that provides the files is remote-osmc:

https://github.com/osmc/osmc/tree/master/package/remote-osmc/files/etc/lirc

The image you've linked to is watermarked so to avoid any copyright infringements can you please take your own photo of your remote on a white background such as a piece of blank paper, and resample the image down to about 480 pixels wide.

If you're uncomfortable with using git then just post a link to the .conf and the png image (full res - we can resample it down) either here or on http://forum.osmc.tv

**Comment by hhromic** [comment]
Hello DBMandrake!
Great Info! I already made now a PR [1] to add this remote. Hope to see it upstream soon in the next update so I don't need to worry to keep custom-made files lying around =).

[1] https://github.com/osmc/osmc/pull/276

**Comment by hhromic** [comment]
The correct PR is now https://github.com/osmc/osmc/pull/277

**Comment by samnazarko** [comment]
Great. I'm afraid you missed this month's update but we should get it in for the March update

**Comment by hhromic** [comment]
Oh well, patience is a good virtue :).
Thanks for adding this, I have other small enhancements that I've beeing working out using my own setup that I believe can be useful for everyone. I'll be sending other PRs.
By the way TERRIFIC job you guys are doing with OSMC.. since I found it and put it into my RPI2 my media center life changed forever for the good.

**Comment by samnazarko** [comment]
Thanks for adding the travel remote

If you would like some guidance with how to contribute further to OSMC feel free to join http://chat.osmc.tv
