### ISSUE TITLE
[minor] Error notification time out too short

### ISSUE THREAD

**Issue by zilexa** [osmc/osmc#280]
When the system gives a notification about an error, the timeout is too short to read the full error. 
This screenshot is taken just before the notification disappears, making it impossible to read what went wrong exactly (though I can get it from logfile):
![screenshot003](https://cloud.githubusercontent.com/assets/3430004/13266008/40754374-da76-11e5-9ac9-dc63af3c37e3.png)

It is not a big deal, but perhaps the area can be a bit more wide and the notification timeout can be a bit longer.

**Comment by samnazarko** [comment]
The OSMC skin is being re-developed.

We will take this suggestion on board

Best

Sam
