### ISSUE TITLE
Image 20160130 cannot be upgraded after install (latest image, no mods)

### ISSUE THREAD

**Issue by zilexa** [osmc/osmc#284]
I wanted to perform a couple of tests since I am having trouble with Kodi since the latest 2016-02 update.

But I bumped into an issue right away. These are the steps to reproduce, my findings and full logs:

1. download the latest available image for RPi2 from osmc.tv. This will be:
OSMC_TGT_rbp2_20160130.img

2. Write image to SD.

3. boot up RPi

ERROR: before I get to the the startup wizard, I get the notification of an error. It was unexpected and happened too fast. 

4. Finish the OSMC wizard like this: location: Amsterdam, enable SSH, choose a custom name for the device, select Confluence as default skin).

5. Now wait a couple of minutes because it will do some first boot stuff: build menus, update some addons etc

6. Now go to MyOSMC and start the update process manually: 

ERROR: "Addon error. Check the log for more information".

7. Now enable UPNP, all options. Try again. Same result (I just wanted to make sure there was no bootloop).

Full log:
http://paste.osmc.io/rojonixupe

I am now running:
`sudo apt-get update && sudo apt-get dist-upgrade`

So it is not a big deal. But I thought I should post it anyway.

**Comment by samnazarko** [comment]
See 75a6648f1477aa49c2e55aa901aca31b72d8796b

**Comment by zilexa** [comment]
OMG I should have thought of this, I had a similar leap year issue with a completely different system, 4 years ago!

**Comment by samnazarko** [comment]
No worries -- make sure you update your Zune..

**Comment by zilexa** [comment]
Hah! ;)

Now unfortunately, the manual update also had a weird part, not sure if it is expected so I dont want to create a whole new report (this is just a snippet):

`Setting up rbp2-image-4.4.1-1-osmc (1) ...

 Hmm. There is a symbolic link /lib/modules/4.4.1-1-osmc/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/4.4.1-1-osmc/build


 Hmm. The package shipped with a symbolic link /lib/modules/4.4.1-1-osmc/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/4.4.1-1-osmc/source

Running depmod.`

**Comment by samnazarko** [comment]
That's not an error. It's been covered on the forum before.

**Comment by zilexa** [comment]
OK. thanks anyway!

**Comment by Karnage** [comment]
Hey! 

Have you  ever seen  something that awesome? You've got to take a look <http://solusithi.jewishpittsburgh.net/aennsbp>

Good wishes, haze

**Comment by ActionAdam** [comment]
Github compromised?
