### ISSUE TITLE
TV channel icons only appear on FTA channels

### ISSUE THREAD

**Issue by pepijn1978** [osmc/osmc#285]
17, 18, and 19 are FTA channels.
 
The icons from scrambled tv channels do show up in the lower left corner but do not show up in front of the channel name. See first attached picture.

When I change skin to confluence the icons do appear. See second picture.

Running the most recent version available on a RPi 2.

![20160302_000555](https://cloud.githubusercontent.com/assets/13928111/13445201/29ffcf5c-e00b-11e5-9897-8af1e4d59e73.jpg)

![20160302_001911](https://cloud.githubusercontent.com/assets/13928111/13445505/d6532dfc-e00c-11e5-9f75-4fc3f4f6efe6.jpg)

**Comment by samnazarko** [comment]
The OSMC skin is undergoing a redesign. This will be fixed in the next version.
