### ISSUE TITLE
Fresh Installation: Skin selection in setup wizard not saved.

### ISSUE THREAD

**Issue by casperklein** [osmc/osmc#286]
I've done a fresh installation of OSMC (OSMC_TGT_rbp2_20160130.img.gz) on my rpi2s sd card.

On the first start, the sd card is formatted etc. Next a setup wizard comes up asking for language, time zone and later for the skin to be used (confluence or osmc). When selecting confluence the setup is complete and the skin changes from osmc to confluence. Next you see the normal home screen.

But doing then the first reboot, osmc comes up with osmc skin and not confluence enabled. Changing the skin again to confluence seems to work (survives reboots).

I noticed that on my last two fresh installation, so its reproducible.

**Comment by samnazarko** [comment]
That suggests corruption, but needs investigation. Thanks for reporting. I'll let you know my findings.

**Comment by casperklein** [comment]
fyi: I tried it with different sd cards (16 and 32GB Sandisk) and also with different sd->usb adapters

**Comment by samnazarko** [comment]
I'll look at this in due course and fix the issue. Thanks for reporting.

**Comment by casperklein** [comment]
Seems to be fixed in 2016.02-02 :+1:
