### ISSUE TITLE
Issue when starting C++ applications: terminate called without an active exception

### ISSUE THREAD

**Issue by pfink** [osmc/osmc#291]
Hi all,

recently I had a very similar issue with starting two completely different C++ applications on OSMC + Raspberry Pi. Both applications are failing with the following error message:

```
pure virtual method called
terminate called without an active exception
```

So there are may some problems with specific C++ libraries? You can find the issues I raised for the concrete applications here:

50ButtonsEach/fliclib-linux-dist#22
badaix/snapcast#38

Both applications are working fine on Debian Jessie.

**Comment by samnazarko** [comment]
OSMC uses upstream libs.

Do you have a small, preferably single source file to reproduce this issue?

Which Raspberry Pi are you using? Pi 1 uses Raspbian as a base and Pi 2 uses upstream armv7hf.

**Comment by pfink** [comment]
I'm using Pi 2. Isolating this issue and providing a single source file would take me some time as I've nearly zero expierence with C++. Maybe @fabianbergmark or @badaix would be faster?

Fastest to reproduce with binaries is setting up snapcast which is very small and easy to install.  Quickstart:
```
wget https://github.com/badaix/snapcast/releases/download/v0.4.0/snapserver_0.4.0_armhf.deb
sudo dpkg -i snapserver_0.4.0_armhf.deb
sudo apt-get -f install
/usr/sbin/snapserver
```

I'll try to further examine and update you if I have something new. Thank you for your incredibly fast reaction.

**Comment by samnazarko** [comment]
```
sudo -s
>/etc/ld.so.preload
```

**Comment by badaix** [comment]
Hi,
please find snapserver with debug symbols (g++ -g, not stripped) here:
[snapserver_debug_v0.4.0.gz](https://github.com/osmc/osmc/files/170520/snapserver_debug_v0.4.0.gz)
It's compiled on a Raspberry 2 with Raspbian Jessie. Might this be due to avahi?
(these dependencies are needed: `libboost-dev libboost-system-dev libboost-program-options-dev libasound2-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon`)

From the [Makefile](https://github.com/badaix/snapcast/blob/master/Makefile):
```
CXX     = /usr/bin/g++
CFLAGS  = -std=c++0x -Wall -Wno-unused-function -g -pthread -DVERSION=\"$(VERSION)\" -I..
LDFLAGS = -lrt -lboost_system -lboost_program_options -lvorbis -lvorbisenc -logg -lFLAC -lavahi-client -lavahi-common
```

**Comment by samnazarko** [comment]
If you are compiling for OSMC, you should either:

* Compile using an OSMC system / the OSMC toolchain
* Build your binary statically.

**Comment by pfink** [comment]
Using static linked version provided by @baidax in badaix/snapcast#38 works fine! Thank you very much for your support, Sam! I think with fliclib it's exactly the same issue, so I'll tell them 50ButtonsEach/fliclib-linux-dist#22.
