### ISSUE TITLE
Please add support for the bcm2708-rng kernel module

### ISSUE THREAD

**Issue by CRCulver** [osmc/osmc#292]
On a fresh installation of OSMC on the Raspberry Pi 2, the bcm2708-rng module is missing. As a hardware RNG is one of the RP2's particular strengths, please build this module when compiling and packaging the kernel for OSMC.

**Comment by samnazarko** [comment]
I will try and get it in for this month's update

**Comment by CRCulver** [comment]
I see that this didn't make it into the OSMC update released on April 3. Any hope for next month?

**Comment by CRCulver** [comment]
Running dmesg on OSMC with kernel 4.4.6-3-osmc reveals the following:

"bcm2835-rng 3f104000.rng: hwrng registered"

So, it looks like support for the Raspberry PI 2 hardware RNG is already built, just compiled into the kernel instead of a module. However, other Broadcom-provided features on the Raspberry Pi 2 are built as modules, namely bcm2835_gpiomem, bcm2835_thermal, and bcm2835_wdt. So, perhaps it is worth compiling bcm2835-rng as a module too for the sake of consistency?

**Comment by samnazarko** [comment]
rng is built in for earlier loading, some utilities can benefit from loading it quickly and the earlier access to better entropy is good.

**Comment by CRCulver** [comment]
Alright, then. I got the hardware support I was looking for, so you could mark this as closed if you'd like.
