### ISSUE TITLE
Any chance we can get SocketCAN kernel driver support?

### ISSUE THREAD

**Issue by theburninator133** [osmc/osmc#293]
Specifically the mcp251x driver. 

My PiCan 2 board works fine with Rasbian Jessie, but it makes so much more sense to run OSMC in a Pi based car media player

**Comment by samnazarko** [comment]
What CONFIG_ options do you want set?

**Comment by theburninator133** [comment]
Sorry if I'm not understanding, I'm trying my best to wrap my head around all this-- but the additions to config.txt to make it work in Raspbian are :

> dtparam=spi=on
dtoverlay=mcp2515-can0-overlay,oscillator=16000000,interrupt=25
dtoverlay=spi-bcm2835-overlay

**Comment by samnazarko** [comment]
Okay. We can add the overlay and module for that.

**Comment by theburninator133** [comment]
thanks a ton

**Comment by samnazarko** [comment]
Closed as added.
