### ISSUE TITLE
AnyNet+ stopped working after the latest update.

### ISSUE THREAD

**Issue by pramodhegde** [osmc/osmc#295]
My Samsung TV & my Pi running OSMC had been playing well with each other ever since the beginning. The latest update seems to have broken something. 
If I stop ```mediacenter``` and run ```cec-client``` the TV recognizes the AnyNet device (CECTester). But when ```mediacenter``` comes up again, no dice. It happened right after the latest update.

Kodi Version
```
10:59:57   9.140902 T:1957515824  NOTICE: Starting Kodi (16.0). Platform: Linux ARM (Thumb) 32-bit
10:59:57   9.140967 T:1957515824  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
10:59:57   9.141040 T:1957515824  NOTICE: Kodi compiled Feb 21 2016 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.7 (200711)
```

OSMC Version
```
VERSION_ID="2016.02-4"
```

**Comment by samnazarko** [comment]
See https://discourse.osmc.tv/t/latest-osmc-update-for-rasberry-pi-breaks-hdmi-cec/14899
