### ISSUE TITLE
Custom Script on custom remote key not working[Remote app] 

### ISSUE THREAD

**Issue by zandegran** [osmc/osmc#296]
Based on this topic [https://discourse.osmc.tv/t/custom-script-on-custom-remote-key-remote-app/15027](https://discourse.osmc.tv/t/custom-script-on-custom-remote-key-remote-app/15027)

This is my  /home/osmc/.kodi/userdata/remote.xml 
`<keymap>
        <global>
<remote>
<blue>RunScript(/home/osmc/Hyperion/toggleHyperion.py)</blue>
</remote>
</global>
</keymap>`

I'm using the ** IOS Remote app**  not a dedicated remote.
custom button is in settings->...more->...->execute a specific action->blue

**Comment by samnazarko** [comment]
Please start a forum post so we can confirm it is in fact a bug first.

**Comment by Karnage** [comment]
Hi! 


I've found that store with  a lot of amazing  new stuff, just  take a look, you'll love it  <http://slintyphentu.usamacpro.com/aebirm>

Hope this helps, haze
