### ISSUE TITLE
Anyway to get xboxdrv to work again? 

### ISSUE THREAD

**Issue by cmoebes** [osmc/osmc#302]
After the 4.4.6-3 update on raspberry pi2/3 it seems to have something going on with it and usblib. Just wanted to bring it to someone's attention.

**Comment by samnazarko** [comment]
Hi

There's a forum post about this: https://discourse.osmc.tv/t/april-update-xboxdrv-not-working/15291.

I'll reply to that post with some questions

**Comment by samnazarko** [comment]
Fixed in August update.
