### ISSUE TITLE
OSM hangs after a while since Kodi 16

### ISSUE THREAD

**Issue by laoneo** [osmc/osmc#303]
Since osmc ships with Kodi 16 it randomly freezes on my Raspberry Pi 1. In the log file, the last entry is

> 16:04:09 1376.639282 T:2647651312   ERROR: COMXCoreComponent::WaitForOutputDone OMX.broadcom.audio_mixer wait event timeout
16:04:09 1376.639771 T:2647651312   ERROR: CActiveAEResamplePi::Resample m_omx_mixer.WaitForOutputDone result(0x80001011)

**Comment by popcornmix** [comment]
Try setting resample quality from GPU to low in system/audio settings.

**Comment by laoneo** [comment]
Thanks. Will try it out. What does change has for effects?

**Comment by samnazarko** [comment]
Check out this thread for some background: https://discourse.osmc.tv/t/april-update-causes-system-freezes/15361.

**Comment by laoneo** [comment]
It went better with the settings change. But the system sometimes hangs and then I can access it trough SSH and do need to reboot. The log shows then the following output:

```
20:00:01 112666.351562 T:2497704944  NOTICE: VideoInfoScanner: Starting scan ..
20:00:09 112674.562500 T:2610951152 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:00:10 112674.750000 T:2610951152 WARNING: Previous line repeats 1 times.
20:00:10 112674.750000 T:2610951152  NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/8XXFkcHWeGexeWTH66cFtgKo5FF.jpg
20:00:18 112683.156250 T:2610951152 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:00:18 112683.257812 T:2610951152 WARNING: Previous line repeats 1 times.
20:00:18 112683.265625 T:2610951152  NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/sjKpTRzX5fNaUwToVObmiWLCiHb.jpg
20:00:19 112684.007812 T:2610951152 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:00:19 112684.109375 T:2610951152 WARNING: Previous line repeats 1 times.
20:00:19 112684.117188 T:2610951152  NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/ibx1HFeo9hTq4hb3LvlccI3lv9S.jpg
20:00:20 112684.781250 T:2610951152 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:00:20 112684.898438 T:2610951152 WARNING: Previous line repeats 1 times.
20:00:20 112684.898438 T:2610951152  NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/u5zfClhWSwcDQ3AaAxi46F7AVYs.jpg
20:00:22 112687.109375 T:2497704944  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:20
20:32:57 114642.148438 T:3024507664  NOTICE: DVDPlayer: Opening: /data/Movies/my-movie.mkv
20:32:57 114642.148438 T:3024507664 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:32:57 114642.156250 T:2699031536  NOTICE: Creating InputStream
20:32:57 114642.171875 T:2699031536  NOTICE: Creating Demuxer
20:33:21 114665.812500 T:3024507664  NOTICE: CDVDPlayer::CloseFile()
20:33:21 114665.812500 T:3024507664  NOTICE: DVDPlayer: waiting for threads to exit
```

Any fix for that? This happens like any two or three days.

> Try setting resample quality from GPU to low in system/audio settings.

What does this change has for an effect?

**Comment by popcornmix** [comment]
I see no problem in log. The warnings about progressive images means hardware jpeg decode is not possibly, but that is quite common. It decodes them with software decode.

> What does this change has for an effect?

It is explained in the thread linked earlier.

**Comment by laoneo** [comment]
What else can I do ti identify the bug, when it is not written in the log file? I did not change anything except making applying the April updates.

**Comment by laoneo** [comment]
This issue has been solved in one of the latest updates. Good job.

**Comment by samnazarko** [comment]
Thanks for the feedback.
