### ISSUE TITLE
Can we upgrade the version of tvheadend in the appstore?

### ISSUE THREAD

**Issue by steverandy** [osmc/osmc#304]
tvheadend that comes installed from app store is version 4.0.5. I'm having issue with DVB-T2 stream, which uses HE-AAC for audio. Video shows perfectly but without any sound.

I have built tvheadend from github source and now the stream has both video and audio working.

Can we upgrade the version of tvheadend in the appstore to the latest, which is 4.1-1870?

**Comment by samnazarko** [comment]
Certainly

Can you PR a version bump (and test the build locally). Have a look at package/tvheadend-app-osmc and let me know if you need any pointers.

**Comment by steverandy** [comment]
I'm new to osmc project. Where can I find the documentation to run the package build?

I'm getting this error:
```
Package -toolchain-osmc is not found on the system, checking APT
E: The value 'oolchain-osmc' is invalid for APT::Default-Release as such a release is not available in the sources
E: You must give at least one search pattern
Can't find the package in APT repo. It needs to be built first or you need to wait for upstream to add it
```

**Comment by samnazarko** [comment]
What commands did you run?

I would do:

cd package/tvheadend-app-osmc
make armv7

**Comment by steverandy** [comment]
I did not use make.

It's running now with make armv7 but got this error:
```
Package installed successfully
/mnt/package/tvheadend-app-osmc/src/tvheadend-4.0.9 /mnt/package/tvheadend-app-osmc
Checking support/features
  checking for cc execinfo.h ...                    ok
  checking for cc -mmmx ...                         fail
  checking for cc -msse2 ...                        fail
  checking for cc getloadavg ...                    ok
  checking for cc atomic64 ...                      ok
  checking for cc lockowner ...                     ok
  checking for cc qsort_r ...                       ok
  checking for cc stime ...                         ok
  checking for cc recvmmsg ...                      ok
  checking for cc sendmmsg ...                      ok
  checking for cc libiconv ...                      fail
  checking for cc libdvben50221 ...                 ok
  checking for py module gzip ...                   fail
  checking for gzip ...                             ok
  checking for bzip2 ...                            ok
  checking for pkg openssl  ...                     ok (detected 1.0.1k)
  checking for cc linux/dvb/version.h ...           ok
  checking for pkg zlib  ...                        ok (detected 1.2.8)
  checking for pkg liburiparser  ...                ok (detected 0.8.0.1)
  checking for pkg avahi-client  ...                ok (detected 0.6.31)
  checking for ffmpeg libraries ...                 fail
  checking for pkg libavcodec >=55.34.1 ...         ok (detected 56.1.0)
  checking for pkg libavutil >=53.3.0 ...           ok (detected 54.3.0)
  checking for pkg libavformat >=55.12.0 ...        ok (detected 56.1.0)
  checking for pkg libswscale >=2.1.2 ...           ok (detected 3.0.0)
  checking for pkg libavresample >=1.1.0 ...        ok (detected 2.1.0)
  checking for cc sys/inotify.h ...                 ok
  fetching dvb-scan files ...                       fail
ERROR: Failed to fetch dvb-scan data (use --disable-dvbscan)
Makefile:23: .config.mk: No such file or directory
Makefile:475: /support/.mk: No such file or directory
make: *** No rule to make target '/support/.mk'.  Stop.
Makefile:23: .config.mk: No such file or directory
Makefile:475: /support/.mk: No such file or directory
make: *** No rule to make target '/support/.mk'.  Stop.
Error occured during build
Makefile:8: recipe for target 'armv7' failed
make: *** [armv7] Error 1
make: Leaving directory '/mnt/package/tvheadend-app-osmc'
Makefile:8: recipe for target 'armv7' failed
make: *** [armv7] Error 2
```
I tried adding dvb-apps as a dependency but no help.
Also it's using v4.0.9. I cannot find 4.1.x release on github.

**Comment by samnazarko** [comment]
Did you build this on an ARM system, or PC?

I believe that the fetching process uses Git, which uses pthreads. This is not guaranteed to work correctly if you are emulating the ISA

**Comment by steverandy** [comment]
I'm using a raspberry to build. Do I need a PC?

**Comment by samnazarko** [comment]
No a Pi should be Okay.

I'll try a build later and see if there are missing deps

**Comment by steverandy** [comment]
Seems to be an issue with SSL.
```
fatal: unable to access 'https://github.com/tvheadend/dtv-scan-tables.git/': Problem with the SSL CA cert (path? access rights?)
```
4.0.9 uses github repo https://github.com/tvheadend/dtv-scan-tables.git

**Comment by samnazarko** [comment]
try adding

handle_dep "ca-certificates" in build.sh

**Comment by steverandy** [comment]
I managed to build v4.0.9 and v4.1, thanks to the pointers from you.

However, the sound issue is only fixed in master branch and tvheadend has not made a 4.2 release yet.

For now, is there any action we can take?

**Comment by samnazarko** [comment]
Is the ca certificate dependency necessary?

I would wait for a stable release before bumping the version then.

Sent from a mobile device, so please excuse the brevity of this reply

On 14 Apr 2016, at 01:06, Steve Randy Tantra <notifications@github.com<mailto:notifications@github.com>> wrote:


I managed to build v4.0.9 and v4.1, thanks to the pointers from you.

However, the sound issue is only fixed in master branch and tvheadend has not made a 4.2 release yet.

For now, is there any action we can take?

-

**Comment by steverandy** [comment]
Yes, it was necessary for dvbscan step. Without it, the build always fails.

**Comment by samnazarko** [comment]
Bumped and fixed.
