### ISSUE TITLE
sys.stderr.isatty()

### ISSUE THREAD

**Issue by daineseh** [osmc/osmc#307]
Hi All,

I am write a Addon and I using [youtube-dl](https://github.com/ruuk/script.module.youtube.dl) module,

I get some message below:

> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-
>          - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>        Error Type: <type 'exceptions.AttributeError'>
>        Error Contents: xbmcout instance has no attribute 'isatty'
>         Traceback (most recent call last):
>           File "/home/osmc/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/YoutubeDL.py", line 669, in extract_info
>             ie_result = ie.extract(url)
>           File "/home/osmc/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py", line 321, in extract
>            return self._real_extract(url)
>          File "/home/osmc/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/googledrive.py", line 60, in _real_extract
>            reason = self._search_regex(r'"reason"\s*,\s*"([^"]+)', webpage, 'reason', default=None)
>          File "/home/osmc/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py", line 609, in _search_regex
>            if not self._downloader.params.get('no_color') and compat_os_name != 'nt' and **sys.stderr.isatty()**:
>        AttributeError: xbmcout instance has no attribute 'isatty'
>        -->End of Python script error report<--

Other thing I try **print(dir(sys.stderr))** , it return ['__doc__', '__init__', '__module__', 'close', 'flush', 'll', 'write'].

If possible to enhance the sys.stderr module? Thanks!

**Comment by joaovictor07** [comment]
How did you solved this ? Can you help me ? I am getting the same error

**Comment by samnazarko** [comment]
I suspect this module has moved on a little since the original commenter opened the issue. My first recommendation would be to contact the developer of this add-on directly. We're happy to look at it if this is localised to OSMC.

**Comment by joaovictor07** [comment]
Got it, thanks for your time
