### ISSUE TITLE
No hifiberry DAC sound

### ISSUE THREAD

**Issue by bartoszpierzchlewicz** [osmc/osmc#308]
After upgrading to latest version snd-hifiberry-dac not working.
Yesterday everyting was fine.
Details here https://discourse.osmc.tv/t/hifiberry-dac-stops-working-after-upgrade/

**Comment by samnazarko** [comment]
I think you posted in the forum earlier. GitHub is for confirmed issues

Please produce a log in your forum post. We are not aware of a widespread issue

Sent from a mobile device, so please excuse the brevity of this reply

On 2 May 2016, at 19:45, bartoszpierzchlewicz <notifications@github.com<mailto:notifications@github.com>> wrote:


After upgrading to latest version I can't load module snd_soc_bcm2708, so snd-hifiberry-dac not working.
Yesterday everyting was fine.

-

**Comment by samnazarko** [comment]
Closing, as now fixed.
