### ISSUE TITLE
Add Keyboard Repeat Setting or Fix kbdrate

### ISSUE THREAD

**Issue by estin1985** [osmc/osmc#309]
OSMC lacks the ability to modify keyboard key repeat rates and keyboard key repeat delay time.  I tested using kbdrate but OSMC mediacenter does not make use of the variables set.  

Now maybe I'' wrong and this control exists someplace, but I am fairly confident it does not exist in OSMC. Lirc controls / settings have no affect on keyboard repeat rates.

**Comment by samnazarko** [comment]
I think this is more of a Kodi specific request, in particular CLinuxInputDevices.
