### ISSUE TITLE
Can't play some DVD

### ISSUE THREAD

**Issue by nyanloutre** [osmc/osmc#317]
I have a Raspberry Pi B+ with a USB DVD drive (connected to a powered usb hub, so it has enough energy)
Sometimes when I put a DVD in the tray it is mounted automaticaly but for some DVD (always the sames) I have to manually run some commands until it play : 
udisks --mount /dev/dvd
then sometimes udisks --unmount /dev/dvd && udisks --mount /dev/dvd
After that I can play the DVD.
I don't know where the bug could come from, maybe a udev rule ?

**Comment by samnazarko** [comment]
Please start a forum post with some debug logs so we can confirm this is a known problem. Then we can reopen this issue
