### ISSUE TITLE
Music player starts and crash

### ISSUE THREAD

**Issue by nlamirault** [osmc/osmc#318]
Hi,
i use OSMc on RPI2 with a Synology NAS. Video player works fine (using NFS), but i've got an error using music player. I choose a song, it stats, after 5 seconds it crash.
Outputs logs are : 

```
15:39:59 713937.875000 T:1582298096   ERROR: COMXImageFile::ReadFile nfs://192.168.1.13/volume1/music/Adele/Rolling in the Deep/cover.jpg not found
15:39:59 713937.875000 T:1582298096   ERROR: Previous line repeats 1 times.
15:39:59 713937.875000 T:1582298096  NOTICE: LoadJpeg: unable to load nfs://192.168.1.13/volume1/music/Adele/Rolling in the Deep/cover.jpg
15:40:02 713941.562500 T:1546646512  NOTICE: [Artist Slideshow] script version 2.0.0 started
15:40:02 713941.562500 T:1546646512  NOTICE: [Artist Slideshow] debug logging set to false
```

Any idea ? how can i debug that ?
Thanks.

**Comment by nlamirault** [comment]
File cover.jpg exists. On NAS :

```
$ ls -alFrt /volume1/music/Adele/Rolling\ in\ the\ Deep/cover.jpg 
-rw-rw---- 1 nicolas users 27139 Mar 24  2015 /volume1/music/Adele/Rolling in the Deep/cover.jpg
```

**Comment by samnazarko** [comment]
Post a full log, and not just a small snippet.

Please confirm it on the forum first as a bug before opening an issue.

Sam

Sent from a mobile device, so please excuse the brevity of this reply

On 12 Jul 2016, at 15:42, Nicolas Lamirault <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
i use OSMc on RPI2 with a Synology NAS. Video player works fine (using NFS), but i've got an error using music player. I choose a song, it stats, after 5 seconds it crash.
Outputs logs are :

15:39:59 713937.875000 T:1582298096   ERROR: COMXImageFile::ReadFile nfs://192.168.1.13/volume1/music/Adele/Rolling in the Deep/cover.jpg not found
15:39:59 713937.875000 T:1582298096   ERROR: Previous line repeats 1 times.
15:39:59 713937.875000 T:1582298096  NOTICE: LoadJpeg: unable to load nfs://192.168.1.13/volume1/music/Adele/Rolling in the Deep/cover.jpg
15:40:02 713941.562500 T:1546646512  NOTICE: [Artist Slideshow] script version 2.0.0 started
15:40:02 713941.562500 T:1546646512  NOTICE: [Artist Slideshow] debug logging set to false


Any idea ? how can i debug that ?
Thanks.

-
