### ISSUE TITLE
Can't cross-compile kernel: "Argument list too long"

### ISSUE THREAD

**Issue by tito** [osmc/osmc#323]
Hi everyone,

I tried to rebuild OSMC kernel from master (to patch hid to add support for Harmony Smart Control/PS3, and then do a pull request). But i failed twice. I followed the steps for vero2:

1. Clone the repo
2. Build the toolchain (cd toolchain/armv7-toolchain-osmc && make && dpkg -i armv7-toolchain-osmc.deb)
3. Build the kernel (cd package/kernel-osmc && make vero2)

And it failed (tested on elementary os (patched supported os first), then tested on Debian Wheezy in virtualbox). Both failed almost at the end of the kernel building (on a fresh wheezy install):

![selection_148](https://cloud.githubusercontent.com/assets/37904/17407896/4ccf5eca-5a69-11e6-88ec-137d4d28a725.png)

(i don't have the log, since i didn't used tee...)

I've seen the error a little bit before with md5sum by the way.

On my system, `getconf ARG_MAX` is 2097152, while ARG_MAX in vero2-linux-master/include/uapi//linux/limits.h is 131072. 

What should i do?

**Comment by samnazarko** [comment]
Hi

Building on Debian Wheezy won't work reliably, as the QEMU userspace emulation isn't very recent and this is quite slow. Debian Jessie is the recommended build environment for OSMC.

If you are building on the Vero 2, I would recommend cloning in /home/osmc and building from there. I have only seen the above error when you are nested several directories deep.

To rule out issues with your toolchain, you can also do:

```
sudo apt-get remove --purge armv7-toolchain-osmc
```

Then run make vero2 in package/kernel-osmc. This will then fetch the toolchain from our repository.

**Comment by tito** [comment]
I tried not to build the toolchain in the first place, but it were asking for the package first, that's why i build it first. Will try with your instruction, thanks!

**Comment by samnazarko** [comment]
If you add deb http://apt.osmc.tv jessie main to /etc/apt/sources.list, the package will be automatically installed. On OSMC systems, this repository is already added.

**Comment by tito** [comment]
So i installed a fresh Debian Jessy, created the default user as osmc, added the deb apt source, clone the repo, and make vera2 in the kernel package. It's still undergoing, but i'm still having the max arguments issue:

![selection_149](https://cloud.githubusercontent.com/assets/37904/17416036/af41d3c6-5a8c-11e6-8cd5-7f267b7d03fb.png)

Let's see what will be the result at the end.

**Comment by tito** [comment]
Yep, same issue on Jessy :(

![selection_150](https://cloud.githubusercontent.com/assets/37904/17416352/01e09f8a-5a8e-11e6-9d49-8f32cb784272.png)

**Comment by samnazarko** [comment]
It may be an environmental issue. I stopped emulating kernel builds some time ago and now build them on arm hardware. You should be able to have a successful build on the Vero 2

In the interim, I will investigate this issue.

**Comment by tito** [comment]
Ok. Just to confirm, it's fresh install with absolutely nothing else except ssh selected in tasksel, and git-core, build-essential, vim, sudo.

**Comment by samnazarko** [comment]
I use a netboot based command line install of Jessie on KVM for Jenkins workers which do QEMU based builds. I'll force a build over to x64 later and see if I can replicate the issue.

**Comment by tito** [comment]
Oh you mean i should have tried to build on x86?

(also, could you share your command line for jenkins? ^^)

**Comment by samnazarko** [comment]
Hi

To clarify: we build on ARM usually for kernel and Kodi. These are long-duration builds with significant performance hits on non-native hardware, even with ccache. So when I said I would try an x64 build, I meant that I would do so instead of executing a build on an ARM build slave.

If you can, just try and build the package on your Vero 2. This is the best approach and is guaranteed to work. We can't always guarantee build reliability on other platforms, although I am working to improve this. My Jenkins commands are simple:

```
pushd package/kernel-osmc
make clean
make vero2
```

I use the Git SCM plugin and some other plugins to collect the outputted Debs are artifacts.

**Comment by tito** [comment]
I'm trying to build on vero2 itself right now (and forgot to clean previous attempts on /usr/src, and lead to full space used :/).

Thanks for sharing your past experience on that!

**Comment by samnazarko** [comment]
Chuck a usb pen drive in or mount something in /etc/fstab like an NFS share.

Then you can do mount --bind /opt/osmc-tc /some/path and the build system and ccache will be stored elsewhere. ccache can sometimes be a bit funny with NFS (flock() issues), but should be OK with recent versions of the OSMC build system.

**Comment by tito** [comment]
The build failed on x86 as well.
But the build on vero2 worked.

**Comment by samnazarko** [comment]
You are not expected to be able to build any OSMC packages on x86, apart from Apple TV ones, so I'm not surprised the build failed.

**Comment by samnazarko** [comment]
OK to close?
