### ISSUE TITLE
CEC idea

### ISSUE THREAD

**Issue by zangyedits** [osmc/osmc#327]
You should integrate so that one of the buttons on older simplink LG remotes works as a rightclick/info button. 
Because the the button marked "info" only makes the tv show what res/inputname/hdmi-port it is on. 

Older simplink = AKB72914261 alike.

**Comment by samnazarko** [comment]
I no longer have an LG TV, so can't test this. It would be better to discuss this on the forum with other LG owners, then we could accept a PR if there are improvements on the whole.
