### ISSUE TITLE
Support for TP-Link T4U

### ISSUE THREAD

**Issue by dkadioglu** [osmc/osmc#331]
Hi,

I've got a Rbp2 and a TP-Link T4U which works for 2.4Ghz but not for 5Ghz. I think that the device is not properly detected. Googling around I found this driver which got updated to support the T4U: https://github.com/abperiasamy/rtl8812AU_8821AU_linux/commit/ec491cf25874a250b42bd3ac6e352c6fb9e814d0

Could you add this?

Thanks

**Comment by samnazarko** [comment]
If you are able to see WiFi networks, then the driver is being loaded. The suggested patch you have sent only adds support for the driver, but it seems that support has already been added for this adapter. You can confirm whether the module is loading with ```lsmod```.

Please ensure you are on the latest version of OSMC, there were improvements for handling 5Ghz networks in the August updates.

**Comment by dkadioglu** [comment]
I am on OSMC 2016.09-1. lsmod shows that the driver is indeed loaded. But I still can't see any 5Ghz network. Do you have any idea what the problem could be?

**Comment by samnazarko** [comment]
I don't unfortunately. You should read the Wiki on how to report bugs and investigate them. GitHub is for confirmed issues only.

**Comment by dkadioglu** [comment]
Just tested the device on my laptop (Arch Linux) using this driver: https://aur.archlinux.org/packages/rtl8812au_rtl8821au-dkms-git/
Here it can see 5Ghz networks and it can connect to them. So there seems to be an issue with the driver in OSMC. As far as I understand it, this should be a confirmed issue now, if not, than I apologize for that.

Which source of the driver do you use? I could try to build the driver from the same source you do and see what happens on my laptop. Would that be of any help?

**Comment by samnazarko** [comment]
Please read the Wiki on how to report bugs properly. This report isn't enough for us to start looking at the problem.

You can get the sources for the 8812au driver under the OSMC organisation

**Comment by dkadioglu** [comment]
OK, I don't know why but, now it works. As far as I can remember, there is nothing I changed.
I really apologize for the noise!!

Nevertheless thanks for your immediate replies!
