### ISSUE TITLE
Broken NOOBS `partitions.json` files?

### ISSUE THREAD

**Issue by lurch** [osmc/osmc#336]
I haven't tried it myself, but apparently something is broken in your online files?
https://github.com/raspberrypi/noobs/issues/360

**Comment by samnazarko** [comment]
Hi Andrew,

This is fixed now. Jenkins was publishing both Pi 1 and Pi 2 assets even though the build is parameterised. I have updated the job to only upload assets for the device it is built for. The new versions should now be published on our website.

Thanks for reporting this.
