### ISSUE TITLE
OSMC set PATH in a weird way

### ISSUE THREAD

**Issue by Testato** [osmc/osmc#343]
OSMC have problem with alternative shell program like Fish
I opened an issue on the Fish github, do you agree that the problem is on OSMC ?
May OSMC set default path in a different way for do not disturb alternative Shell ?
https://github.com/fish-shell/fish-shell/issues/3494#issuecomment-267848298

**Comment by samnazarko** [comment]
This isn't really an OSMC problem nor a Fish problem. PATHs are configured or Bash and the Unix shell interpreter, which is handled by BusyBox. 

It looks like you compiled Fish for OSMC. If that is the case, you are effectively the maintainer or distributor, and you shouldn't expect it to work perfectly out of the box. We have requests to support other shells; and while they may be in the Debian repositories; there may be customisation necessary to ensure a consistent environment on these shells. This is beyond the realm of OSMC, as we don't package these alternative shells ourselves at this time.

We define PATH modifications in ```/etc/profile.d``` as recommended by Debian. We do not wish to modify /etc/login.defs, particularly when the PATH can vary per OSMC platform (e.g. /opt/vc/bin on Raspberry Pi).

Fish does not read /etc/profile.d includes as this shell has a different syntax.
