### ISSUE TITLE
OSMC cannot handle Wifi password changes

### ISSUE THREAD

**Issue by dberg918** [osmc/osmc#345]
Today, I changed the password on my router's wifi SSID. Afterwards, I went into My OSMC's Network section to update the password there. It was disconnected from the wifi network as expected, but when I tried to reconnect, the spinner came up for about a minute. When it finally asked for a new password, I input the new one and the spinner came up again. It eventually threw a "Connection failed" notification after about 2 minutes, but repeated attempts produced the same results. (Just a sidenote: a successful connection to my network usually takes about 10 seconds)

I hooked up a keyboard to the Raspberry Pi (v3) to investigate and found that connman's settings for my wifi network (at `/var/lib/connman/wifi*/settings`) had not changed -- that is, the wifi password was still the old password. Seems like there's some disconnect between My OSMC's Network script magic and connman's settings.

As far as I can remember, I originally set up the wifi settings on OSMC in the installer. Not sure if that makes a difference.

**Comment by samnazarko** [comment]
> Seems like there's some disconnect between My OSMC's Network script magic and connman's settings.

Yes, pretty much. I think we just need to add a 'Forget Network' option to My OSMC, which deletes the stored connection settings.

Removing the wifi*/settings file and attempting reconnection via My OSMC should work.

**Comment by dberg918** [comment]
> Removing the wifi*/settings file and attempting reconnection via My OSMC should work.

Yes, I can confirm that this was the solution when I encountered the problem. An option to 'Forget Network' should work, as long as the option can be executed whether OSMC is currently connected to the network or not.

I don't know much about the OSMC codebase, but if you can tell me where to look, maybe I can put together a pull request.

**Comment by samnazarko** [comment]
Thanks for confirming

See package/mediacenter-osmc if you'd like to improve the situation.

You will find it on your system under /usr/share/kodi/addons/*.osmc*

**Comment by DBMandrake** [comment]
There is already an option to "disconnect and forget" wifi networks in the GUI - I've used it before.

If it's not working for you that's a bug, not a missing feature. Can you forget a network where the password is correct and it is currently connected ?

**Comment by dberg918** [comment]
> If it's not working for you that's a bug, not a missing feature. Can you forget a network where the password is correct and it is currently connected?

Yes I can, but that does not help me. If you are not connected to the network, you will see a "Connect to `SSID`?" pop-up with the only options being "Yes" or "No." The issue is that there is no way to forget a network that has an incorrect password stored by connman.

In my case, I had changed the password for my wireless network for security purposes, which disconnected OSMC from the network. Since I could not connect to the network due to the incorrect, but stored, old password, there was no way for me to "forget" it from the GUI. I had to go in manually with a keyboard and delete the settings from the terminal.

As I said, OSMC did prompt me for the password after it sat for a minute, but entering the new password did not change connman's settings for my SSID. When I checked manually, the old password was still there.

**Comment by samnazarko** [comment]
This is probably a limitation of the agent at this time.

**Comment by Argo8** [comment]
Just make a wifi hotspot on phone with data from old wifi, then connect to it and then disconect and forget. Then connect to new wifi

**Comment by samnazarko** [comment]
You need to forget the old network. This can be done manually via SSH or the command line using a keyboard.

**Comment by Argo8** [comment]
Isnt my way easier then ssh? Just make "old wifi" on a phone, connect to it and then forget it. Its basicly the same but much faster and easier for average person.

**Comment by Argo8** [comment]
It got revived because i had this problem today :D 
While i was looking for answers here i realized that i cant ssh with no connection and dont have a keyboard lying around. As i figured out a solution i wanted to share it for other people in my situation. Long story short this solution works like a charm.

**Comment by samnazarko** [comment]
You make a good point. It might make sense for us to forget the network on an auth failure.

A

Sent from a mobile device, so please excuse the brevity of this reply

On 7 Sep 2018, at 22:32, Argo8 <notifications@github.com<mailto:notifications@github.com>> wrote:


It got revived because i had this problem today :D
While i was looking for answers here i realized that i cant ssh with no connection and dont have a keyboard lying around. As i figured out a solution i wanted to share it for other people in my situation. Long story short this solution works like a charm.

**Comment by rgnjwrgjlnrb** [comment]
Status is "Closed"  but this is still a problem 5 years later and not fixed. Today I configured a fresh OSMC install (latest stable version) and entered the wrong password for the Wifi network. I then tried to enter the correct one but it kept failing to connect all the time. In the end I copied the OSMC image to the SD card again and configured everything from zero. This is not user friendly at all, people sometimes put the wrong password or the password changes over time and OSMC should be able to  handle it

**Comment by samnazarko** [comment]
This was fixed over a year ago. You can forget the network now. Please make sure you are on the latest version of OSMC

**Comment by rgnjwrgjlnrb** [comment]
> This was fixed over a year ago. You can forget the network now. Please make sure you are on the latest version of OSMC

You are right, the option to forget a network is present in the release from 20220314, which is the usual version I install. I had the problem with the one released 20201227, which is the last version that supports correctly 3D content on Raspberry Pi's and the reason why I was installing an older version. My bad, sorry, and thanks for the quick response

**Comment by samnazarko** [comment]
You’re welcome. Thanks for your understanding. I do apologise that it took us some time to fix this.
