### ISSUE TITLE
Please add support for Hauppauge soloHD DVB-T2 stick

### ISSUE THREAD

**Issue by Lemming0815** [osmc/osmc#352]
I've bought the above stick because DVB-T1 is switched off next month. However, in the kernel it's not supported yet. I've copied the firmware files to no avail.
Linux kernel should have support since 3.19 but apparently, media-build patches are required or modules being enabled.
This would be a guide for Ubuntu Kernel: https://wiki.ubuntuusers.de/v4l-dvb/
Maybe you can cross-read?

Cheers!

**Comment by samnazarko** [comment]
Wait for a kernel bump or use a different adapter. I don't have plans to build media build out of tree at this time
