### ISSUE TITLE
STRM Files to view streaming video 

### ISSUE THREAD

**Issue by lejanssen** [osmc/osmc#353]
A great feature was added to KODI/XBMC several years ago to allow users to view streaming live video feeds from various sources--I use it to watch live church services.  This feature works great with Version 16 and older Kodi releases, but has stopped working on Kodi 17.  This bug is common for both OSMC Kodi 17 release and for Linux/Kodi 17 releases.  My STRM files still work with Kodi release 16.1 and older but not with release 17.  This may not be a bug but could be a setup issue.  I can not find any info from the Kodi and OSMC forums.  Hoping someone out there know something about this.
Here is a one of the strm files I have used for years and still works great on both OSMC, OpenElec, and Linux/Kodi OS's.

http://getvhdflash-f.akamaihd.net/i/GETV_CHANNEL1@36799/master.m3u8
From a browser the same feed is accessible at GETV.org.

I also want to thank all the great work from the OSMC team.  Like the new release for look, feel, and operation (except for the strm problem).

**Comment by samnazarko** [comment]
This tracker is generally for confirmed bugs. I would advise starting a forum post, with some debug logs so we can look in to the problem. I'll close this for now and we can reopen if necessary
