### ISSUE TITLE
Can't have an answer from HTTP Get request

### ISSUE THREAD

**Issue by TitaneBoy** [osmc/osmc#354]
Hi everyone... I'm here because I think there is an issue with KODI (provided by osmc) on Raspberry pie. I'm writting a node.js application (writted in javascript) that will just send an http GET request to my Kodi to update the library... I saw in the Kodi wiki the request format to use (See [here](http://kodi.wiki/view/JSON-RPC#GET)) but when I run the app, I got a socket hang up error.

```
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Here is my http request:
` http://192.168.1.103:8080/jsonrpc?request={"jsonrpc":"2.0","method":"VideoLibrary.Scan"}.`

 I can see on my kodi that it received the request and that it updates my library...but I think that kodi must return something that it didn't do at all. I've tryied to make the http request with the chrome application: "Postman" but I got an error too ("Could not get any response")...So I don't think that there is something wrong with my application writted in javascript (Node.js)

Does anyone has the same issue/behavior than me ?

Thanks a lot for your answer

**Comment by samnazarko** [comment]
Have you tried this on another Kodi platform such as Windows for example?

**Comment by TitaneBoy** [comment]
Humm...I didn't...I will try it in few minutes and will give you the feedback about it... Thanks for your suggestion.

**Comment by TitaneBoy** [comment]
Hi again...It seems that even with Kodi on Windows, I can't have any response from my http request.

**Comment by samnazarko** [comment]
Closing, as this doesn't seem OSMC related. If it turns out to be, we can reopen.
