### ISSUE TITLE
deboostrap for some targets is called with --no-check-gpg

### ISSUE THREAD

**Issue by d1b** [osmc/osmc#355]
deboostrap for the following target is called with `--no-check-gpg` 
* [aarch64](https://github.com/osmc/osmc/blob/82faf42c528de5785c31580be3b32f8dab1750fd/toolchains/aarch64-toolchain-osmc/build.sh)
* [armv6l](https://github.com/osmc/osmc/blob/82faf42c528de5785c31580be3b32f8dab1750fd/toolchains/armv6l-toolchain-osmc/build.sh)
* [armv7](https://github.com/osmc/osmc/blob/82faf42c528de5785c31580be3b32f8dab1750fd/toolchains/armv7-toolchain-osmc/build.sh)
* [rbp1](https://github.com/osmc/osmc/blob/af16c537920576a0976759f8c6cf25fd9ef75b23/filesystem/osmc-rbp1-filesystem/build.sh)
* [rbp2](https://github.com/osmc/osmc/blob/af16c537920576a0976759f8c6cf25fd9ef75b23/filesystem/osmc-rbp2-filesystem/build.sh)
* [vero1](https://github.com/osmc/osmc/blob/af16c537920576a0976759f8c6cf25fd9ef75b23/filesystem/osmc-vero1-filesystem/build.sh)
* [vero2](https://github.com/osmc/osmc/blob/af16c537920576a0976759f8c6cf25fd9ef75b23/filesystem/osmc-vero2-filesystem/build.sh) 
* [vero3](https://github.com/osmc/osmc/blob/09024676cfb10bcc8c6ce1001085029a63c3ad65/filesystem/osmc-vero3-filesystem/build.sh)

Other targets for example [amd64](https://github.com/osmc/osmc/blob/82faf42c528de5785c31580be3b32f8dab1750fd/toolchains/amd64-toolchain-osmc/build.sh) do not call debootstrap with `--no-check-gpg`.

**Comment by samnazarko** [comment]
That's because key won't be necessarily be present until later. But debootstrap will fall back to HTTPS as a result (kernel.org).

If you have a way of improving this behaviour I'm happy to accept a PR.

**Comment by d1b** [comment]
I'll have a look.
