### ISSUE TITLE
Osmc updates : Insufficient room....

### ISSUE THREAD

**Issue by elbarbudo** [osmc/osmc#356]
According to the wiki, I should have enough room on all devices 

```
> osmc@osmc:~$ df -h
> Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
> udev                10M       0   10M   0% /dev
> tmpfs              147M    4,5M  143M   4% /run
> /dev/sda2          3,4G    3,1G  101M  97% /
> tmpfs              367M       0  367M   0% /dev/shm
> tmpfs              5,0M       0  5,0M   0% /run/lock
> tmpfs              367M       0  367M   0% /sys/fs/cgroup
> /dev/mmcblk0p1     240M     26M  214M  11% /boot
> /dev/sda3          1,8T    1,6T  168G  91% /home
> /dev/mmcblk0p2     3,4G    644M  2,6G  20% /media/3d83adb1-f328-49f1-b8ad-b60659839f9f
> /dev/sda1          240M     21M  219M   9% /media/BOOT
> /dev/sdb1          367G    243G  106G  70% /media/Trekstor
> tmpfs               74M       0   74M   0% /run/user/1000
> osmc@osmc:~$ 

```
Also apt update returns : 

```
> Atteint http://ftp.debian.org jessie/non-free Translation-en                   
> Ign http://apt.osmc.tv jessie/main Translation-fr_FR                           
> Ign http://apt.osmc.tv jessie/main Translation-fr        
> Ign http://apt.osmc.tv jessie/main Translation-en
> 13,1 ko réceptionnés en 16s (791 o/s)                                          
> Lecture des listes de paquets... Fait
> Construction de l'arbre des dépendances       
> Lecture des informations d'état... Fait
> All packages are up to date.

```
and 

```
> root@osmc:/home/osmc# apt dist-upgrade
> Lecture des listes de paquets... Fait
> Construction de l'arbre des dépendances       
> Lecture des informations d'état... Fait
> Calcul de la mise à jour... Fait
> 0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
> root@osmc:/home/osmc# 
> 

```
BUT when I run a manual update from MYOSMC I get an update and the message Insufficient space.... after the download.

What can I do?

**Comment by samnazarko** [comment]
>/dev/sda2 3,4G 3,1G 101M 97% /

Looks like you are using a USB installation?
It also doesn't look like a USB installation performed by the OSMC installer because you have multiple partitions on /dev/sda.

100M on rootfs is not enough for updates. We check for <300M.

**Comment by elbarbudo** [comment]
Yep, this is an USB installation on a Raspberry PI2.
I followed the RaspBerry "how to" to make an USB installation from the sd card because the OSMC installer refused to install on my 2 To USB drive from my LinuxMint PC.
I did the following : 

1. Installation on the SD card from my Linux  Mint machine
2. dd of the boot/root partition to the USB drive (2To drive)
3. expand the /home partition to use the whole disk

But the point is that both apt upgrade and apt dist-upgrade tells that everything is up to date.

**Comment by samnazarko** [comment]
>But the point is that both apt upgrade and apt dist-upgrade tells that everything is up to date.

Yes -- that will work until you run out of space, but 100M is dangerously low. We put the 300M advisory in My OSMC for a reason.

A few thumbnails, or a larger apt-cache will cause problems.

My OSMC is behaving as expected, so closing this.
