### ISSUE TITLE
Kodi doesn't start after March update

### ISSUE THREAD

**Issue by leonardder** [osmc/osmc#358]
I installed the OSMC March update, and after updating, Kodi doesn't start anymore. I get the following output when I running the mediacenter binary

```
Starting Kodi...
inactive
inactive
inactive
inactive
inactive
inactive
ERROR: Unable to create application. Exiting
Kodi exited with return code 139 after 0 hours, 0 minutes and 1 seconds
```

There's nothing interesting in the Kodi log, it is actually empty so it seems the process crashes before kodi even tries to start itself up.

I am using a Raspberry Pi II with kernel 4.4.27-9-osmc

**Comment by ActionAdam** [comment]
Github is for confirmed bugs.  Please start a thread on discourse.osmc.tv for support.

**Comment by ActionAdam** [comment]
Try starting here, I suspect it's a similar issue...  https://discourse.osmc.tv/t/kodi-17-1-does-not-boot-anymore/35561
