### ISSUE TITLE
No DNS with NFSROOT and DHCP

### ISSUE THREAD

**Issue by ggzengel** [osmc/osmc#360]
I have two PI 2 and both haven't name resolution any more.

I think the problem is here https://github.com/osmc/osmc/commit/058dc6537c79badb56bb429fe9689aa1950fff3c and here https://github.com/osmc/osmc/commit/29290ef3b66967e460f765d4fdacf594599a4f2d.

/proc/cmdline
> bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708_fb.fbswap=1 dma.dmachans=0x7f35 bcm2709.boardrev=0xa01041 bcm2709.serial=0x90ed65a4 bcm2709.uart_clock=48000000 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 smsc95xx.macaddr=B8:27:EB:ED:65:A4 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  root=/dev/nfs nfsroot=192.168.180.100:/srv/nfs/rootfs/kodi-gwez.donner14.private ip=dhcp rootwait quiet osmcdev=rbp2

/proc/net/pnp
> #PROTO: DHCP
domain donner14.private
nameserver 10.32.12.1
bootserver 0.0.0.0

ls -la /etc/resolv.conf 
> lrwxrwxrwx 1 root root 28 Apr 13 19:30 /etc/resolv.conf -> /var/run/connman/resolv.conf

cp /proc/net/pnp /etc/resolv.conf
> cp: not writing through dangling symlink '/etc/resolv.conf'

There is a symlink in /etc/resolv.conf and connman didn't change resolv.conf any more:
--noresolvmodify

**Comment by ggzengel** [comment]
ls -la /var/run/connman/
> total 0
drwxr-xr-x  2 root root  40 Apr 16 23:58 .
drwxrwxrwt 17 root root 520 Apr 17 00:53 ..

**Comment by samnazarko** [comment]
Already resolved in 74c4eafc327eaa166738eed720a0a11b03d18218 and c172728e9a410ea37789bb61de28c090bdfe9a59. Please search in future.

Re-open if this is still an issue after upgrading to staging.

**Comment by ggzengel** [comment]
So I have to delete symlink /etc/resolv.conf without breaking future updates?

**Comment by samnazarko** [comment]
No -- it will be resolved *automatically* in the next update.
You can also update to the staging repository if you want.

It's been discussed here: https://discourse.osmc.tv/t/problem-with-resolv-conf-on-nfs-root-install-since-march-update/35505/29.

Please search in future before opening issues.

**Comment by ggzengel** [comment]
How to update without DNS?

I searched in all open and closed issues on github and didn't find something.
I couldn't search in future without a tardis.

**Comment by samnazarko** [comment]
You should search the forum as well. The link above shows the solution.

To get the update you can copy /proc/net/pnp > /etc/resolv.conf temporarily.

**Comment by ggzengel** [comment]
Thanks.
And sorry for the noise.
Good work at all.

**Comment by samnazarko** [comment]
No problem.

If you have any more problems, just post on that thread and I will take a look.
