### ISSUE TITLE
Kodi v17 Playback crash on “Pause” with BT speaker

### ISSUE THREAD

**Issue by matejmosko** [osmc/osmc#367]
This is already known issue from the forums - [osmc.tv - #22608](https://discourse.osmc.tv/t/kodi-v17-playback-crash-on-pause/22608/5). The original fix [commited by sam_nazarko](https://github.com/osmc/osmc/commit/062302f32d6719bdae5219a67b62a560ba10e5eb) repaired the error in logs, but the issue still occurs after update of service.py. These are my logs after crash (with fixed service.py): http://paste.osmc.io/ipowejeseg I believe the problem is somewhere around 18:11.

I hope You will find some time to look into the problem. It is quite inconvenient when playing streaming content sent to kodi from PC (youtube etc), because everytime it crashes, I have to go back to computer to start playing the stream. Sorry for crossposting, I am not quite sure what do You prefer (forums or issue tracker)

**Comment by samnazarko** [comment]
Did you try: 1e2d82c4a111b8542e529ab267b40d150e284025.

@gezb and I haven't been able to reproduce this which means these are guesses.

**Comment by matejmosko** [comment]
Tried now. Replaced file, restarted Kodi. Playback on Pause still crashing. 

These are new logs: http://paste.osmc.tv/cexugebigi

Crash happened at 16:47.

**Comment by samnazarko** [comment]
What device are you streaming from?
Do you have another BT device you can test with temporarily?

CC @gezb 

We are having trouble reproducing this but if we can do so we have a chance of fixing this.

**Comment by samnazarko** [comment]
@gezb has a suggestion that may improve things. Can you update the Python file with these changes?

https://paste.osmc.tv/anonacedir

If this fails, can you try disabling the BTPlayer add-on and let us know if the issue still persist?

Thank you

**Comment by matejmosko** [comment]
I am using RPi3 with official BT dongle from osmc.tv. From there I am streaming sound to [Philips AEA2000 BT receiver](http://www.usa.philips.com/c-p/AEA2000_37/bluetooth-hi-fi-adapter).

1. The paused playback with new version of service.py (with disabled play event listener) crashed again. These are the logs from such try: https://paste.osmc.tv/faxucuzevi Crash happened somewhere around 11:06.

2. Heureka! The paused playback with disabled BTPlayer addon doesn't crash. As to "disabled" - I just disabled service inside of addon's settings. Kodi refused to deactivate addon. Is it ok? The weird thing is that (even after restart) my connected BT speaker works. What exactly si BTPlayer addon for?

**Comment by gezb** [comment]
The BTPlayer addon is designed to allow the display of track details and allow basic control when you are streaming audio from for example a mobile phone TO Kodi rather than streaming from Kodi to a Bluetooth speaker

As such when trying to reproduce I  have been using that use case now I know it is when streaming FROM Kodi I can try and reproduce and find a fix, BTPlayer should not be getting involved when streaming from Kodi  

Thanks for helping us debug this I will try and take a look in the next few days and attempt to get a fix in for the next update. 

For now you can leave BTPlayer disabled as you do not need its functionality

**Comment by matejmosko** [comment]
Thanks a lot. I am sorry if I wasn't clear as to what is happening. :)

**Comment by samnazarko** [comment]
Forgot about that: Kodi won't be able to disable the add-on; as we force it enabled so it works out of the box when the A2DP application is installed.

**Comment by samnazarko** [comment]
Is this still an issue?

**Comment by boxbillinggit** [comment]
Yes, it's still Crashing all Kodi, after unchecking the Enabled option, it works with kodi but I have no titles, songs with BT

**Comment by samnazarko** [comment]
Ok -- needs a revisit.

**Comment by boxbillinggit** [comment]
`22:00:35.084 T:1279259632  NOTICE: Creating InputStream
22:00:35.086 T:1279259632   ERROR: CVideoPlayer::OpenInputStream - error opening [/org/bluez/hci0/dev_B8_1D_AA_9C_E4_E5/player0]
22:00:35.087 T:1279259632  NOTICE: CVideoPlayer::OnExit()
22:00:35.087 T:1958146992   ERROR: Playlist Player: skipping unplayable item: 1, path [/org/bluez/hci0/dev_B8_1D_AA_9C_E4_E5/player0]`

And crash Kodi

**Comment by samnazarko** [comment]
A full log may be more helpful

**Comment by boxbillinggit** [comment]
Dmesg: https://paste.osmc.tv/ropexujoja.coffee
Kodi Log: https://paste.osmc.tv/panifixopo.md

**Comment by livinm** [comment]
some investigaion details are here:
https://discourse.osmc.tv/t/kodi-v17-playback-crash-on-pause/22608/42?u=livin

**Comment by samnazarko** [comment]
Thanks, we'll look in to it.

**Comment by samnazarko** [comment]
This should now be resolved.
