### ISSUE TITLE
Subtitles hack

### ISSUE THREAD

**Issue by iguana007** [osmc/osmc#368]
I would like ask you, if there are any plans of fixing following vulneability?
http://blog.checkpoint.com/2017/05/23/hacked-in-translation/
https://github.com/xbmc/xbmc/pull/12024

**Comment by samnazarko** [comment]
This is already resolved in db8c60b06b5fb974e7baf6a3ba84017d7550fa89.

**Comment by iguana007** [comment]
Thank you 👍

**Comment by spielzeugland** [comment]
I am not familiar with the development/version model of ocmc. Can you explain which version contains or will contain the fix or point me to any documentation on how to find this out?

**Comment by samnazarko** [comment]
This has been discussed on the forum. If you're not a fan of those, you may want to wait for the official announcement on the blog.

**Comment by samnazarko** [comment]
Security is paramount for us. Please see https://osmc.tv/2017/05/osmc-security-update-for-osmc-2017-04-1-and-earlier/
