### ISSUE TITLE
Critical Bug in Kodi 17.1

### ISSUE THREAD

**Issue by skldfjiosndfon** [osmc/osmc#369]
Can u please update Kodi. Kodi fixed the critical bug in version 17.2.

Sources:

https://kodi.tv/article/kodi-v172-minor-bug-fix-and-security-release
http://blog.checkpoint.com/2017/05/23/hacked-in-translation/

**Comment by fonini** [comment]
This is already resolved in db8c60b.

**Comment by samnazarko** [comment]
Duplicate of #368

**Comment by samnazarko** [comment]
Update is now live. See https://osmc.tv/2017/05/osmc-security-update-for-osmc-2017-04-1-and-earlier/
