### ISSUE TITLE
Malicious Subtitles (New vulnerability)

### ISSUE THREAD

**Issue by bzip22** [osmc/osmc#370]
https://torrentfreak.com/malicious-subtitles-threaten-kodi-vlc-and-popcorn-time-users-researchers-warn-170523/

Seems like this could be an potential security risk.

**Comment by jb2cool** [comment]
Yes, this was a potential issue, that's why it was fixed as and out-of-band update yesterday.

See this link for more information.
https://osmc.tv/2017/05/osmc-security-update-for-osmc-2017-04-1-and-earlier/
