### ISSUE TITLE
NextPVR client doesn't parse genres fully

### ISSUE THREAD

**Issue by graham8** [osmc/osmc#372]
NextPVR client on RPi2 does not read iGenreType.  It does read sGenre. iGenreType is either 0 or 256.
Note on Windows, NextPVR client reads iGenreType but not sGenre (but genre names are correctly displayed).  Both using NextPVR client 2.4.13.
[gromgsxr](https://discourse.osmc.tv/t/epg-genre/22902/4) reports LibreELEC works as expected, suggesting something odd in the compile process?

Affects display of epggrid in skins which support genre colours and FWIW, means genres are not given in the user's language as 256 signals 'get genre strings from backend'.

![epg11 nextpvr osmc](https://cloud.githubusercontent.com/assets/9421800/26627048/ffa96fd6-45f0-11e7-9759-47046b9f598f.png)

![epg11 nextpvr win10](https://cloud.githubusercontent.com/assets/9421800/26627066/09a6bc50-45f1-11e7-8814-46ed95405178.png)

**Comment by samnazarko** [comment]
Wait for 17.3 and let me know if the problem persists

**Comment by graham8** [comment]
Yes it does persist.  No change.

**Comment by ActionAdam** [comment]
Impossible! 17.3 has not been released for OSMC.

**Comment by graham8** [comment]
Well, I've got it - maybe because I forgot to turn off the staging repo after 4.9 kernel upgrade.  Will try again later.

**Comment by samnazarko** [comment]
17.3 is in the staging repository.

We're not making any changes to this binary add-on, so I wonder if it's a change upstream.

**Comment by graham8** [comment]
Do you just get the binary from somewhere else or compile it?  I haven't checked gromsxr's claim that it works in LE but suppose their .so should be the same as yours.  let me have a look the next time it rains - too nice to be indoors.

**Comment by samnazarko** [comment]
We compile it when building Kodi.

It's picked from upstream Kodi binary addon repos.

**Comment by graham8** [comment]
Update: Had a quick look at LE.  All the pvr addons have a .1 suffix to their versions in the repo listing but not to their binaries ie the binary is still pvr.nextpvr.so.2.4.13. But it's not the same size as the osmc one. I couldn't test it - gave up when I couldn't even get LE to ping the NextPVR server.

**Comment by samnazarko** [comment]
@graham8 Is this still an issue?
