### ISSUE TITLE
[Language issuse ]Raspberry Pi 3 

### ISSUE THREAD

**Issue by version1123** [osmc/osmc#386]
![image](https://user-images.githubusercontent.com/30774929/29004378-14551394-7af9-11e7-8756-2f6545e3983b.png)
I have chosen chinese language at first boot time ,it didn't work ,help!
Raspberry Pi 2 / 3
Release	Checksum (MD5)
2017.06-1	d36818b085908cfe4da0079035a5104e

**Comment by samnazarko** [comment]
Resolved in https://discourse.osmc.tv/t/language-problem-with-osmc/37619/29
