### ISSUE TITLE
OSMC installer logs the WiFi password in plain text readable for other users

### ISSUE THREAD

**Issue by uykusuz** [osmc/osmc#387]
On my linux system the installer will generate a log file with the WiFi password in plain-text, readable for group and others. Logging the password at all is questionable. Besides then at least the log file should be readable only for the current user, not group nor others.

System details:
* Arch Linux
* used [AUR](https://aur.archlinux.org/packages/osmc-installer-bin/) for debian installer 1.2.7-2 based on debian install package osmc_installer_127_amd64.deb

**Comment by samnazarko** [comment]
I agree -- let's not log the password.

Should be addressed in 863e281db0eb386b3bc7461d538e9508e3eb2d17.

**Comment by samnazarko** [comment]
If the rest of the logs, including logging of the SSID is OK, then we can close this.
