### ISSUE TITLE
both deskptop gui and command line support

### ISSUE THREAD

**Issue by suconghou** [osmc/osmc#391]
It would be wonderful if osmc both support desktop gui and command line at the same time
just like ubuntu desktop , so that I can switch them without reboot my pi .

for example  
use ctrl+alt+f1 for osmc gui 
use ctrl+alt+f2 for command line 
and type ctrl+alt+f1 switch to the gui without anything changed 

another question , I boot my pi without plug the hdmi  , and after started , then plug my hdmi display, It still can not display anything , what's the problem , please give me some suggestions , thank you !

**Comment by samnazarko** [comment]
The scope of this issue is too broad. We are focused on being a media centre OS. There are some desktop options, but we don't plan to include them by default as most users have no use for them.

Please start a forum post for questions. The tracker is for confirmed bugs only.

**Comment by suconghou** [comment]
sorry for my poor English make you have a misunderstanding of what I said. 
I mean I just want a Linux command line without reboot the system.
