### ISSUE TITLE
TVheadend misconfigures on clean install, can't login to web UI

### ISSUE THREAD

**Issue by Sjord** [osmc/osmc#393]
Today I tried to install armv7-tvheadend-app-osmc. The [postinst script](https://github.com/osmc/osmc/blob/master/package/tvheadend-app-osmc/files/DEBIAN/postinst) didn't run correctly. 

```
Setting up armv7-tvheadend-app-osmc (4.2.0-3) ...
grep: /home/osmc/.hts/tvheadend/config: No such file or directory
grep: : No such file or directory
Creating OSMC default access control file
```

When the installation finished, I did have an /home/osmc/.hts/tvheadend/config file. Maybe it wasn't there during postinst?

It seems this resulted in an invalid `$EXISTINGVER`, which resulted in the wrong version of accesscontrol file (`/home/osmc/.hts/tvheadend/accesscontrol/ef332059f7bb54d72ce2e028f71e1540`).  My accesscontrol file looked like [this](https://github.com/osmc/osmc/blob/master/package/tvheadend-app-osmc/files/DEBIAN/postinst#L58-L81) and I couldn't log in to the web UI at port 9981. After I replaced it with [this](https://github.com/osmc/osmc/blob/master/package/tvheadend-app-osmc/files/DEBIAN/postinst#L88-L133) (and reloaded tvheadend) I could log in to the web UI.

**Comment by graham8** [comment]
Thanks for the feedback.  Forgot to re-test the installation for brand-new installs.

**Comment by samnazarko** [comment]
Sjord -- can you confirm if this is fixed by #394

**Comment by Sjord** [comment]
Yes, it now installs the correct accesscontrol file. Thanks!

Note that it still displays an error about a file that is not found:

```
Setting up armv7-tvheadend-app-osmc (4.2.0-5) ...
grep: : No such file or directory
Creating OSMC default access control file
```

**Comment by samnazarko** [comment]
Thanks for confirming.

>grep: : No such file or directory

We probably want to check the file exists first

**Comment by graham8** [comment]
hmm thought I'd covered that. no harm but will review if there are any more bugs to fix

**Comment by Sjord** [comment]
The error originates from this line:

    OSMCUSERPASS=$(grep "\"password2\":" "$OSMCPASSFILE")

`$OSMCPASSFILE` is empty.

**Comment by graham8** [comment]
quite. it's in the todos.

**Comment by samnazarko** [comment]
Thanks for reporting this problem.
