### ISSUE TITLE
Latest rbp2-device-osmc breaks bluetooth

### ISSUE THREAD

**Issue by mbarnes** [osmc/osmc#399]
Commit fb53304fa95681c6ddc20267300ebd0d18642d74 changed the shell in the "shebang" line in `/usr/bin/rpi-btuart` from `/usr/bin/bash` to `/usr/bin/sh`, which causes the script to fail with a "Bad substition" error on bootup (I didn't track down where the bash-specific substitution was), which in turns breaks `bluetooth.service`.

Changing the "shebang" line back to `/usr/bin/bash` fixed the problem for me.

**Comment by samnazarko** [comment]
Resolved in  e3d1e59.

You should get an update in a few minutes.
Thanks for the report
