### ISSUE TITLE
Make use of apparmor policies found in debian.

### ISSUE THREAD

**Issue by d1b** [osmc/osmc#401]
This similar to #390 requires changing kernel config options -
```
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
CONFIG_AUDIT=y
```
I assume that osmc will want 

```
CONFIG_DEFAULT_SECURITY_APPARMOR=y
```
then we will want to follow https://wiki.debian.org/AppArmor to add ` apparmor apparmor-profiles apparmor-utils` (assuming the size isn't too large) and enable the usr.sbin.ntpd profile in enforcing mode.

**Comment by d1b** [comment]
Related, you may wish to make  `armv7-network-osmc` and `rbp2-device-osmc` depend upon `ntpclient` or `chrony` or `ntp`.

**Comment by samnazarko** [comment]
network-osmc already depends on ntp.

**Comment by samnazarko** [comment]
No plans for AppArmor at the moment; but if I had a preference it would be for SELinux

**Comment by d1b** [comment]
@samnazarko  I meant to make `network-osmc` require one of them (not just `ntp`).

> No plans for AppArmor at the moment; but if I had a preference it would be for SELinux

Interesting because AppArmor is fairly simple and has policies that can be applied without much work. 
Regardless, will you accept a pull request to enable the apparmor in the kernel & if so by default use it as the main LSM ?

**Comment by samnazarko** [comment]
Sorry for the delay in reply. I'd be happy to accept a PR more modules to be built for all kernels.
Could you advise regarding your use case, it may be beneficial to some users in the future?

**Comment by d1b** [comment]
My use case is enabling apparmor policies for system services to harden the OSMC software. By the way it looks like debian is considering enabling apparmor by default in debian (https://wiki.debian.org/AppArmor/Progress).

**Comment by samnazarko** [comment]
Closing as this is handled in Buster
