### ISSUE TITLE
CEC patch settings mismatch 

### ISSUE THREAD

**Issue by NewFolk** [osmc/osmc#409]
Hello,

Looks like wrong settings in CEC.

In this patch we have 
`LOCALISED_ID_IGNORE       36028 `
https://github.com/osmc/osmc/blob/f9a8b89294ce12c85f9fe8db355bed85798fef2a/package/mediacenter-osmc/patches/all-005-better-cec-behaviour.patch#L32

that brings to error msg.
https://github.com/xbmc/xbmc/blob/3ec83805d6d8fcdf849d2029c85104ac11cef270/xbmc/peripherals/devices/PeripheralCecAdapter.cpp#L655

**Comment by samnazarko** [comment]
Hello

There was an overlap in the past with one of the strings. It's certainly possible some of the options need updating. I will take a look shortly.

**Comment by samnazarko** [comment]
Hello

Patch is updated in b5209b9985ede7aa1f369e3d64ff6752debf0906
I've checked and 36028 is considered an acceptable value for this setting.

Some of the more advanced CEC settings were missing however. I've now resolved this.

**Comment by samnazarko** [comment]
I believe this is now resolved. Let me know if you find this to not be the case in the next update.
