### ISSUE TITLE
osmc-installer on debian stretch

### ISSUE THREAD

**Issue by CrYpT0n1T3** [osmc/osmc#424]
Hey. How to install osmc-installer on debian stretch?

where is stretch? instructions for debian 8 not working for me.
https://software.opensuse.org/download.html?project=home:osmc&package=osmc-installer&hcolor=17394a&fcolor=17394a&acolor=17394a

**Comment by samnazarko** [comment]
When you say it isn't working, can you let us know what happens in more detail?

**Comment by CrYpT0n1T3** [comment]
I made a mistake. it works. thread to be deleted. thanks for quick reply
