### ISSUE TITLE
Integrate a VNC server

### ISSUE THREAD

**Issue by mvglasow** [osmc/osmc#430]
Many OSMC setups are either headless, in locations where it’s inconvenient to attach a local keyboard and mouse, or simply away from the computer which one would use for web searches in case of troubleshooting or other maintenance tasks.

Being able to mirror the display of the OSMC box and fully remote-control it would simplify things a lot. Combined with a mobile VNC client it would even overcome some limitations of the remote control.

I see you have forked dispmanx_vnc, which would presumably address this if it were fully integrated into OSMC (i.e. installed by default or available as an add-on)—is this planned?

If lack of portability is the blocker here (the description sounds like it’s RPi-specific), then a solution similar to Ubuntu would work: users can enable a VNC server which mirrors the local display (only the X display, though). Combine this with autostart and drop the user confirmation dialog on the local display (which is needed on a desktop machine for privacy reasons, but is counterproductive on a headless server), and at least the GUI can be remote-controlled in this way—which should be sufficient for most purposes.

**Comment by samnazarko** [comment]
There are plans to add VNC capabilities to the App Store in the future. However, as you have noted, the implementation is specific to the underlying windowing platform.

There is already a HOW-TO on our forums for setting up VNC.
