### ISSUE TITLE
No automount of external USB HDD after update

### ISSUE THREAD

**Issue by Perfect-Chaos** [osmc/osmc#433]
At first please excuse the bad error description. Iam am a software developer myself and I know that a reported issue should be as detailed as possible but I use OSMC on my Raspberry Pi Zero just to randomly watch old series from my USB-HDD so I never have looked at the details regarding the OS and patchlevels.

Error:
After one of the last updates (must have been in the last 3 months) OSMC stopped to automount my external HDD which is connected via USB. 
Before I just powered on my socket outlet with the Pi Zero and my external HDD already plugged in and after the boot of OSMC the HDD was mounted.
Now the HDD is powered on but not mounted at all. I have to plug out the micro-usb connected to the HDD from my Pi Zero and then just plug it back it. After that OSMC recognizes the plugged in HDD and mounts it.

Maybe the automount does not work anymore because the HDD is already powered on when the Pi Zero starts?

Greetings!
Felix

**Comment by fzinken** [comment]
The issue tracker is for confirmed bugs. Please open a thread on https://discourse.osmc.tv providing the required debug logs.

**Comment by samnazarko** [comment]
Closing for now.
