### ISSUE TITLE
Gpio-shutdown overlay not working on pi 3b or 3b+

### ISSUE THREAD

**Issue by JamesGKent** [osmc/osmc#434]
I have an install of osmc running the march update. I tried to enable the gpio-shutdown overlay in the config file, however connecting gpio3 (pin5) to ground does nothing, this was originally testing in my 3b+, i moved the card to my pi3 and observed the same thing.
The only other pi i have is a 1b which doesn't seem to boot that osmc image (didn't think it would)
The different lines i tried added to config.txt:
```
dtoverlay=gpio-shutdown
dtoverlay=gpio-shutdown,gpio_pin=3
dtoverlay=gpio-shutdown-overlay
dtoverlay=gpio-shutdown-overlay,gpio_pin=3
```
I noticed that on osmc the overlay files have the extension .dtb whereas a raspbian installs files are .dtbo, i tried a raspbian install on my pi 1b and the overlay worked as expected.
I tried copying the raspbian overlay files to osmc and that also failed to work.

Strangely overlay in the raspbian image also failed to work on either my 3b or 3b+

I'm trying to work out how i can investigate any further?

**Comment by JamesGKent** [comment]
upon further investigation it appears that the gpio_keys.ko module needed for this overlay to work is missing from the pi image. i have tried to add it and the alias's etc from a raspbian installation manually but currently with no success.

**Comment by samnazarko** [comment]
Indeed. I’ll add it shortly. Do you know the CONFIG_ option needed?

Sent from a mobile device, so please excuse the brevity of this reply

On 27 Mar 2018, at 20:12, James <notifications@github.com<mailto:notifications@github.com>> wrote:


upon further investigation it appears that the gpio_keys.ko module needed for this overlay to work is missing from the pi image. i have tried to add it and the alias's etc from a raspbian installation manually but currently with no success.

**Comment by JamesGKent** [comment]
the best reference I've found is here:
https://discourse.osmc.tv/t/gpio-hardware-buttons-control-with-gpio-keys/22717/4
which suggests `CONFIG_KEYBOARD_GPIO`

I figured out the reason copying from raspbian didn't work is due to the different kernel versions meaning the module format differs to what osmc's kernel needs. if the module is built against the correct headers then it should work.

**Comment by samnazarko** [comment]
I've added that kernel option for both RBP1 and RBP2 (fbda21228cd9a38ffb460f885693d2c56ee2ef08) now and you can grab it from stretch-devel (dist-upgrade) in a couple of hours. Please let me know if this resolves things for you.

**Comment by JamesGKent** [comment]
This doesn't solve the issue, inside `/lib/modules/4.14.30-1-osmc/kernel/drivers/input/keyboard` i should have a gpio_keys.ko module, but I only have a matrix_keyboard.ko module

**Comment by JamesGKent** [comment]
after reading through more [documentation](https://cateee.net/lkddb/web-lkddb/KEYBOARD_GPIO.html) the config option i gave earlier `CONFIG_KEYBOARD_GPIO` should result in building a module named `gpio_keys` yet for some reason this does not appear to be the case.
just to check the steps i followed were:
 

1. edit /etc/apt/sources.list to add:
deb http://apt.osmc.tv stretch-devel main
2. sudo apt-get update && sudo apt-get dist-upgrade
3. reboot

lsmod showed no sign of the module being loaded, i tried to load it using modprobe, that gave an error message stating not found, i then checked the folder where it should be (where is appears on raspbian but corrected for kernel version) and the module is not present.

**Comment by samnazarko** [comment]
A different config option must be required then. I’ll see if I can find this.

Sent from a mobile device, so please excuse the brevity of this reply

On 28 Mar 2018, at 07:04, James <notifications@github.com<mailto:notifications@github.com>> wrote:


This doesn't solve the issue, inside /lib/modules/4.14.30-1-osmc/kernel/drivers/input/keyboard i should have a gpio_keys.ko module, but I only have a matrix_keyboard.ko module

**Comment by JamesGKent** [comment]
thank you, this would be much appreciated

**Comment by JamesGKent** [comment]
also and should probably be a separate issue, any chance of getting this config turned on:
'CONFIG_INPUT_GPIO_ROTARY_ENCODER' to enable the rotary_encoder module
would be nice to be able to connect a rotary encoder up to use as a volume control...

**Comment by samnazarko** [comment]
Added rotary encoder support
Fixed GPIO button support.

I've scheduled builds for Jenkins now. Should be ready for testing in an hour or two.

**Comment by harryberlin** [comment]
how to use the rotary encoder modul?

**Comment by JamesGKent** [comment]
@harryberlin in an ideal world there would be a kernel module to interpret the encoder as keyboard input, but in the short term I'm looking at making a kodi addon using python-evdev to do this.

**Comment by harryberlin** [comment]
i started to write a rotary encoder addon, but there is an error with rpi.gpio, so i decided to switch to pigpio. but after this, i got no time to continue the program.

**Comment by samnazarko** [comment]
It's probably best to continue this discussion on the forum (https://discourse.osmc.tv)

**Comment by JamesGKent** [comment]
This way there is a kernel module that does the hard work interpreting the encoder and provides an axis input, if you set this up as a relative input you can turn each positive event into a volume up keypress and pass it to uinput. Likewise for negative events and volume down. This means that neither rpi.gpio or pigpio are needed and the busy loop is moved to kernel space where it can be much more efficient

**Comment by JamesGKent** [comment]
If i can make a module to do it instead then it all happens at an os level instead and no changes or addons would be needed

**Comment by JamesGKent** [comment]
@samnazarko just downloaded the latest update and still haven't got the gpio_keys module, this is after a reboot too

**Comment by samnazarko** [comment]
Check uname -a and verify your kernel is up to date.

Module is there: INSTALL drivers/input/keyboard/gpio_keys.ko

**Comment by JamesGKent** [comment]
Output from uname -a
`osmc@RPi-HTPC:~$ uname -a                               
Linux RPi-HTPC 4.14.30-1-osmc #1 SMP PREEMPT Tue Mar 27 
23:45:27 UTC 2018 armv7l GNU/Linux`

**Comment by samnazarko** [comment]
Bumped the version for the wrong device by mistake.
Re-building now and will be ready in a couple of hours.

**Comment by JamesGKent** [comment]
Thanks, I'll try to be patient :P

**Comment by JamesGKent** [comment]
@samnazarko can confirm that now both the gpio_keys and rotary_encoder modules are now present, with the encoder module enabled an `event` item shows up in `/dev/input` from the rotary driver.
I have not yet done any further testing with the rotary.
However the gpio_keys is not currently working, with the gpio-shutdown-overlay enabled the gpio_keys is loaded and shows up with lsmod, however connecting the pin to ground does not seem to cause the system to shutdown. Will update when I know more.

**Comment by samnazarko** [comment]
Thanks for confirming the modules are in.
Check if KEY_POWER is actually being received. In OSMC this would be handled by Kodi which would then invoke halt via systemd-logind provided that the key is not nooped.

**Comment by JamesGKent** [comment]
I've loaded the evbug module to look at all events happening in the input system, and no events are being received from either gpio_keys or the rotary_encoder module.
both modules are creating devices under /dev but for some reason are not feeding events into the input system.
```
Mar 29 19:40:56 RPi-HTPC kernel: evbug: Connected device: input3 (rotary@4 at unknown)
Mar 29 19:40:56 RPi-HTPC kernel: evbug: Connected device: input4 (soc:shutdown_button at gpio-keys/input0)
```

**Comment by JamesGKent** [comment]
Ok so it looks like kodi is grabbing all events from these devices and not responding to them accordingly, if i stop the mediacenter service i get events from them as expected

**Comment by JamesGKent** [comment]
can also confirm, if kodi is not active then the button triggers a shutdown as expected. seems to be a common issue when kodi is running without an x server.

**Comment by samnazarko** [comment]
Check Kodi.log to see if the input event is logged. If it is you can just map it.

**Comment by JamesGKent** [comment]
nothing in the kodi logs, but I tried using the keymap editor script anyway, no joy. its not seen as a key as long as kodi is active. I suspect I need to figure out how to change the permissions (udev rules?) to prevent kodi being able to grab them.bbut to start with i'm going to look at udev rules to give them consistent names (if i have my wireless mouse/keyboard dongle plugged in the eventX numbers change)
i suppose we can call this issue closed because the modules are present and working, just kodi thats not playing nice. i'll update this issue if i work out a solution.

**Comment by JamesGKent** [comment]
if i stop the mediacenter service, change the ownership group to root and then restart the mediacenter service, the events are received as desired. currently trying to work out udev rules to do this automatically on startup.

**Comment by JamesGKent** [comment]
ok so i had to alter the existing file `/etc/udev/rules.d/998-fix-input.rules`
from this:
```
# input
#KERNEL=="mouse*|mice|event*",   MODE="0660", GROUP="osmc"
KERNEL=="ts[0-9]*|uinput",      MODE="0660", GROUP="osmc"
KERNEL=="js[0-9]*",             MODE="0660", GROUP="osmc"

# tty
SUBSYSTEM=="tty", KERNEL=="tty[0-9]*", GROUP="tty", MODE="0666"
```
to this:
```
# input
KERNEL=="event*", MODE="0660", GROUP="osmc"
KERNEL=="event*", DRIVERS=="gpio-keys", MODE="0660", GROUP="root"
KERNEL=="event*", DRIVERS=="rotary-encoder", MODE="0660", GROUP="root"
KERNEL=="mouse*|mice", MODE="0660", GROUP="osmc"
KERNEL=="ts[0-9]*|uinput",      MODE="0660", GROUP="osmc"
KERNEL=="js[0-9]*",             MODE="0660", GROUP="osmc"

# tty
SUBSYSTEM=="tty", KERNEL=="tty[0-9]*", GROUP="tty", MODE="0666"
```

so the `event` inputs are now separate to the mouse and mice inputs, and the root group is applied to and devices that are created by gpio-keys or rotary-encoder drivers.

**Comment by samnazarko** [comment]
Can you list the input paths that were fixed up by this rule?

cc @DBMandrake.

We also likely want to split this in to a separate rules file, so that we don't crowd things.

**Comment by JamesGKent** [comment]
@samnazarko i'm not suggesting this is merged, as this simply makes the key handled by systemd instead of kodi. the real issue is kodi grabbing these devices but not registering any events from them.
but systemd only knows how to handle the power key in a meaningful way.
i'm currently investigating why kodi doesn't handle these events, but my current hunch is that these being simple drivers don't implement scancodes, instead they output keycodes only. i'm still delving into the kodi source to figure out where this gets handled, but i thing kodi is treating the keycode as a scan code, asks the driver for the translation to keycode, but because the driver doesn't implement those functions none is given and kodi silently drops the events.

the only lines of any consequence are losing this:
```

```

and replacing it with this:

**Comment by samnazarko** [comment]
Try stopping Kodi and running evtest

**Comment by JamesGKent** [comment]
ok I think I've gotten to the bottom of it.
in kodi's input handling devices with less than 20 keys are not assigned the keyboard type:
[https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/input/LinuxInputDevices.cpp#L1003](https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/input/LinuxInputDevices.cpp#L1003)
because it also doesn't fit the criteria of any other input device type it is assigned `LI_DEVICE_NONE`.

then in the event handling code:
[https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/input/LinuxInputDevices.cpp#L824](https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/input/LinuxInputDevices.cpp#L824)
if the type is `LI_DEVICE_NONE` the event handler returns without doing anything to handle the event.

will test this tonight and see if this fixes it.

**Comment by JamesGKent** [comment]
i can confirm the issue is in kodi, if i alter the driver to report more keys then it works with kodi just fine. unfortunately this means that kodi needs modifying to work correctly.

**Comment by JamesGKent** [comment]
@harryberlin I've put a writeup of my gpio_volume stuff here: [https://discourse.osmc.tv/t/rpi-rotary-encoder-as-volume-control/72053](https://discourse.osmc.tv/t/rpi-rotary-encoder-as-volume-control/72053)
