### ISSUE TITLE
NOOBS v2.7.0 OSMC_Pi2 partition_script.sh arithmetic syntax error

### ISSUE THREAD

**Issue by geekycow** [osmc/osmc#435]
Hiya

Just been playing with NOOBS (always gone straight to Raspbian before) and noticed that OSMC_Pi2 falls to install on NOOBS Lite 2.7.0.

partition_setup.sh fails with an arithmetic error.  This appears to be a problem with the is_pi_zero function which looks for boardrev in /proc/cmdline, which is not in the cmdline on the Pi2 with this version of NOOBS.

**Comment by samnazarko** [comment]
Can you please post the output of what you see on screen?
The script is here: https://github.com/osmc/osmc/blob/master/installer/noobs/partition_setup.sh

**Comment by geekycow** [comment]
![img_20180330_022825](https://user-images.githubusercontent.com/16445944/38121026-96cc58e4-33c4-11e8-8372-771dbc5160dd.jpg)

**Comment by geekycow** [comment]
Looks like you asked me to send the screenshot just seconds after I'd added it.

**Comment by samnazarko** [comment]
Thank you very much for the screenshot. It allowed me to work this out promptly. I've given the script a cleanup.

Can you try again on your side?

**Comment by geekycow** [comment]
Hi Sam

Perfect timing, just as I'd switched off and gone to bed. ;) ROTFL.

You've fixed it!  Installs, boots and runs fine.

Night night, and thanks.  :)

Julie
Xxx

**Comment by samnazarko** [comment]
Thanks for confirming this. I'm glad to hear this is now resolved, and I'm sure it will benefit plenty of others.
