### ISSUE TITLE
Problems in osmc install script in NOOBS and PINN

### ISSUE THREAD

**Issue by ernestomiralles** [osmc/osmc#436]
Hi;

I'm trying install osmc under noobs 2.7.0 and it gives me in install script error, I can't do it.

Thanks for all.

**Comment by lurch** [comment]
Ping @procount :wink:

**Comment by samnazarko** [comment]
Can you take a quick photo of the error?

**Comment by ernestomiralles** [comment]
Ok, I try this night at home, but give me an error in install script. Download osmc with out problems but can't install because give me this error.

**Comment by procount** [comment]
@ernestomiralles - Are you installing/downloading the latest OSMC from the website (within the past 5 days)?

I just tried installing OSMC on a Pi2 from an old version I had downloaded some time ago and got the following error:
```
Error: "OSMC_Pi2: Error executing partition setup script
+ grep -q ARMv7 /proc/cpuinfo
+ [ 0 -eq 0 ]
+ dev=rbp2
+ mkdir -p /tmp/mount
+ vfat_part=/dev/mmcblk0p6
+ ext4_part=/dev/mmcblk0p7
+ [ -n LABEL=boot-rbp2 ]
+ vfat_part=LABEL=boot-rbp2
+ [ -n LABEL=root-rbp2 ]
+ ext4_part=LABEL=root-rbp2
+ mount /dev/mmcblk0p6 /tmp/mount
+ echo root=LABEL=root-rbp2 osmcdev=rbp2 rootfstype=ext4 rootwait quiet
+ is_pi_zero
+ cat /proc/cmdline
+ awk -v RS=  -F= /boardrev/ { print $2 }
+ revision=
/tmp/media/sda1/os/OSMC_Pi2/partition_setup.sh: line 1: arithmetic syntax error
```
Is this the same error you get?
If so, try the latest version because I think this may have been fixed now.

**Comment by ernestomiralles** [comment]
Yes this is my error

**Comment by samnazarko** [comment]
Can you see if it works now?

**Comment by ernestomiralles** [comment]
Now it's good. I tried with noobs 2.7 and pinn 2.52a and everything it's ok. 

Thanks.

**Comment by procount** [comment]
The noobs firmware has changed in 2.7. You must use the latest osmc software with the latest noobs.

**Comment by lurch** [comment]
@ernestomiralles Can this issue and https://github.com/raspberrypi/noobs/issues/485 be closed?
