### ISSUE TITLE
Undesired password prompts on SSH login due to sudo command in /etc/profile.d/105-check-ssh-password.sh

### ISSUE THREAD

**Issue by aldehoff** [osmc/osmc#440]
The OSMC custom script `/etc/profile.d/105-check-ssh-password.sh` issues a warning if the default password of user `osmc` is used. It is run on every login attempt, however the check does not make sense for users other than `osmc` that may be created after installation. The script introduces undesired interactive password prompts to all ssh login attempts by running `sudo` even _before_ checking for presence of `/home/osmc/.nosshwarn`.

See https://stackoverflow.com/questions/50242504/ssh-promted-sudo-password-just-after-login/50281819 for examples where this has caused issues already.

The following steps are suggested to fix the problem:
- change the easy-to-guess default password of user `osmc` upon first login,
- disable SSH logins for the pseudo-root user `osmc`, and
- delete `/etc/profile.d/105-check-ssh-password.sh` for good.

Unfortunately, a system update will currently restore the deleted file and hence the login problems.

**Comment by samnazarko** [comment]
> however the check does not make sense for users other than osmc that may be created after installation.

Have you checked to see if this is not fixed by 3d8bdba1c3b9dd8beb30e6f4bd4f9a29f2ae652e and 201002333bed75928ee99f6c2265ac1888085254? 

The check is no longer ran against users that are not the OSMC user.

**Comment by aldehoff** [comment]
I hadn't checked, but those commits seem to fix the problem. However, why not keep the check in `/home/osmc/.profile` instead of `/etc/profile.d/`? That would limit it to the one and only user affected by the default password. And instead of checking for the presence of `/home/osmc/.nosshwarn` one could simply comment out the corresponding section of the file if the check is no longer desired. One less file to worry about -> KISS. To me the current situation seems like an overly complicated patch for the fact that user `osmc` has been turned into a second `root` user with a password known by everyone.

**Comment by samnazarko** [comment]
We consider the home directory to be somewhat ephemeral in how users make / restore backups.

**Comment by samnazarko** [comment]
Thanks for your thoughts. I'll follow up in the two related issues (#441, #450).
