### ISSUE TITLE
sudo use in shells startup script?

### ISSUE THREAD

**Issue by datamuc** [osmc/osmc#441]
https://github.com/osmc/osmc/blob/201002333bed75928ee99f6c2265ac1888085254/package/base-files-osmc/files/etc/profile.d/103-generate-locale.sh#L5

Shouldn't that and the other occurrences go into `~osmc/.bash_profile` at least? How to add an unprivileged user with such startup scripts?

**Comment by samnazarko** [comment]
OSMC is designed to mainly be operated as the osmc user.

What is the role of the additional user you have?
We could add an environment variable to OSMC's bash profile or check the user before running these scripts?

If you can provide us with some more detail it can certainly inform the direction that we take.

**Comment by datamuc** [comment]
Well, i've chosen osmc because the website says: "For those that do want to tinker, you have the full Debian repositories (which bring over 30,000 packages) at your disposal." So, since my Pi is running all the time I wanted to use it as a small shell-server as well, where my mutt, fetchmail are running. So, I wanted a user that is completely unrelated to the media center thing.

For now I tinkered and updated /etc/profile to check the profile.d scripts for sudo usage and skip them if sudo is found.

```
if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r "$i" ]; then
      grep -q sudo "$i" && continue
      . "$i"
    fi
  done
  unset i
fi
```

Now that I'm reading the code again. It would be enough to chgrp the sudo scripts in profile.d to "osmc" and remove the world readable bit. Then the `-r` test will fail for an ordinary user.

**Comment by samnazarko** [comment]
>Now that I'm reading the code again, it would be enough to chgrp the sudo scripts in profile.d to "osmc" and remove the world readable bit. Then the -r test would fail for an ordinary user.

That's not a bad idea. Instead, it might be better for this to become a systemd oneshot 

The sudo approach is a bit hacky admittedly (particularly for checking password status).

**Comment by samnazarko** [comment]
Please see #450 as this is a duplicate.
