### ISSUE TITLE
Musicvideo Widget navigation

### ISSUE THREAD

**Issue by quickmic** [osmc/osmc#447]
I'm using latest dev builds based on Kodi 18 with Estuary MOD V2 and emby plugin. (Vero 4k)
Anyway, it is not possible to navigate in the Musicvideo subsection of the widgets. e.g. "recently added" or "recently played".
I run the exact same config on a stock kodi 18 on another device, and here it's working. So I guess this has nothing to do with the plugins, or skins.
btw, it's only in the Musicvideo section, everything else looks ok.

**Comment by samnazarko** [comment]
Does your other device run Kodi v18 based on the same Git rev?

This likely isn’t an issue with OSMC unfortunately.

**Comment by quickmic** [comment]
I will investigate by myself. This issue appears in all kodi 18 osmc builds and never in the stock kodi dev builds. The other device is a FireTV Gen2 Box.
Anyway, just one question. Can you reproduce the issue?

**Comment by samnazarko** [comment]
I don’t use that skin or Emby.
You could try posting on the OSMC forum under the v18 builds section, as GitHub’s issues are really for confirmed bugs only
