### ISSUE TITLE
Rpi3: could not mount bootfs due to misassumption when installing from usb

### ISSUE THREAD

**Issue by fabianMendez** [osmc/osmc#448]
If installing from an usb after following [this](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md) instructions to allow usb booting on a raspberry pi

I get the error:
```
Install error: could not mount bootfs
``` 

This is because is assumed that is only possible to boot from sd card:
https://github.com/osmc/osmc/blob/ad5cccf5780d29af5b44655c15ba77752640840c/installer/target/qt_target/qt_target_installer/mainwindow.cpp#L87-L106

**Comment by samnazarko** [comment]
Those instructions aren't supported for OSMC.
Use NOOBS if you need a USB only boot.

**Comment by MPParsley** [comment]
Hi @samnazarko!

Note that USB Mass Storage Boot is now supported using the Raspberry Pi Imager to update the bootloader.
That same Raspberry Pi Imager supports installing OSMC.

**Comment by samnazarko** [comment]
Until our initramfs supports UUID based booting this won't work unfortunately.

I am happy to accept a PR to support this.

**Comment by MPParsley** [comment]
If it's just a matter of changing the if's above, I'd be happy to give it a go.
Not sure what other stuff would need refactoring?

**Comment by samnazarko** [comment]
For a pure USB boot - the initramfs in target needs to be patched to support label or UUID filesystem mounts.
