### ISSUE TITLE
 Undesired password prompts on SSH login due to sudo command in /etc/profile.d/103-generate-locale.sh

### ISSUE THREAD

**Issue by aldehoff** [osmc/osmc#450]
Similar to issue #440, an undesired password prompt appears on attempts to login to any user account via SSH if the desired locale has not yet been created. This is due to commands including `sudo` in lines 5 and 6 of file `/etc/profile.d/103-generate-locale.sh`. The undesired password prompts interfere with any automated login attempts that do not expect interactivity. Deletion of `/etc/profile.d/103-generate-locale.sh` fixes the issue.

Similar to #440, my suggestion to fix the issue is deleting `/etc/profile.d/103-generate-locale.sh` and moving the code to `/home/osmc/.profile` if needed.

**Comment by samnazarko** [comment]
Did you try touching the nowarn file?

**Comment by aldehoff** [comment]
Unlike the script referenced in #440, this one does not check for the presence of `~/.nosshwarn`. I assume it wouldn't make sense here, either, as the only purpose of the script seems to be the generation of missing locales.

**Comment by samnazarko** [comment]
Ok, no sweat.

I’ll check my notes and will catch up on this shortly. I do have some ideas to make such a suggestion persistent beyond the deletion of the home directory.

**Comment by samnazarko** [comment]
Also related to https://discourse.osmc.tv/t/ssh-login-launches-sudo-command/73443

**Comment by samnazarko** [comment]
I've had some time to think this over, and I think simply adding a check to see if the user is OSMC will be sufficient. If they aren't the OSMC user, we can set a standard locale (LANG=C). 

Using a parameterised systemd target is an option as the OSMC user is able to launch systemd targets as defined by PolicyKit. However:

* This only applies to the OSMC user
* Running locale generation changes as a oneshot will not effect the active session in time, which is undesirable.

Most users logging in via SSH are doing so using the osmc user. If they are not, for now we consider them to be advanced users and won't try and generate locales based on the locale of the device they are connecting from. It's a feature we've added as a matter of convenience, but isn't necessary for standard operation.

**Comment by samnazarko** [comment]
Addressed in https://github.com/osmc/osmc/commit/8ac782cad0a51aec37378b36e89933ef899d9467
