### ISSUE TITLE
connmand not starting, prevents bluetooth device connections

### ISSUE THREAD

**Issue by thisisthedaveyouarelookingfor** [osmc/osmc#452]
I'm booting off NFS root, which is probably why this is affecting me. I'm only experiencing bluetooth issues from this. After a recent upgrade, bluetooth didn't connect, hciconfig dev hci0 remained DOWN, but could be set to UP manually after a reboot. 

The issue appears to be that --noresolvmodify is not a valid switch for connmand 1.36. 

[root@osmc: ~] # systemctl status connman
* connman.service - Connman connection service
   Loaded: loaded (/lib/systemd/system/connman.service; enabled; vendor preset: enabled)
   Active: deactivating (stop-post) (Result: exit-code)
  Process: 6165 ExecStart=/usr/bin/start-network (code=exited, status=1/FAILURE)
 Main PID: 6165 (code=exited, status=1/FAILURE); Control PID: 6180 (sleep)
   CGroup: /system.slice/connman.service
           `-control
             `-6180 /bin/sleep 2

[root@osmc: ~] # /usr/sbin/connmand -n --nodnsproxy --noresolvmodify --config=/etc/connman.conf
Unknown option --noresolvmodify

Removing --noresolvmodify from /usr/bin/start-network resolves the issue, and the bluetooth device connects automatically after a reboot. (Maybe this has been moved to the .prefs file?)

**Comment by samnazarko** [comment]
Sorry for the late reply -- I'm currently on a break.
Just to let you know this hasn't been ignored, but I won't be able to look in to this for a little while.

Cheers

Sam
