### ISSUE TITLE
OSMC Skin for Kodi on recalbox 

### ISSUE THREAD

**Issue by BertanStar** [osmc/osmc#457]
Hey, I have a raspberry pi running recalbox os and as you know it has Kodi built in. Is there a way I can turn it into osmc since osmc is also based on Kodi? Thanks!

**Comment by samnazarko** [comment]
OSMC is an OS, not an application. See https://osmc.tv/wiki/general/frequently-asked-questions/

**Comment by Wuschel-Wuschel** [comment]
You can find the OSMC skin here on GitHub:
https://github.com/osmc/skin.osmc
Just download the zip file, rename the folder inside the zip file to "skin.osmc" and you can install it the same way you can install any addon/skin via zip in Kodi.

Maybe that'll help you.

**Comment by BertanStar** [comment]
Thanks! I taught that this should be the because I saw that in the skin settings of my osmc running raspberry pi osmc was selected. And I was able to chose Kodi as my skin and immediately turned into regular Kodi often doing that. For short, thank you very much and have an awesome day :)

**Comment by BertanStar** [comment]
Thank you so much for your

**Comment by Wuschel-Wuschel** [comment]
Glad to be of help. Enjoy our skin!

**Comment by BertanStar** [comment]
:) Thanks...

**Comment by BertanStar** [comment]
@samnarzko I also wanted to say thank you too because of your kindness. Have a great day:)
