### ISSUE TITLE
OSMC Skin highlight, strikethrough instead of underline on next ep overlay

### ISSUE THREAD

**Issue by zilexa** [osmc/osmc#458]
Very minor issue. 
This is about the notification you see during playback when you are almost finished with an episode. A notification about the next episode (using default skin with all recommended addons). 

The text of this notification is striken through. 

Expected behavior: underlined or not underlined (doesn't matter since it's just 1 line of text).  

Actual behavior: strikethrough text.

**Comment by samnazarko** [comment]
What do you mean by recommended addons? This sounds like a problem with the addon you are using

**Comment by Wuschel-Wuschel** [comment]
Got it fixed... Will be in the next update:

![unbenannt](https://user-images.githubusercontent.com/36623079/43975367-a11c1280-9cdd-11e8-8129-85597b8d3fb0.png)

Thanks for making me aware of the issue @zilexa :)

**Comment by zilexa** [comment]
That's the one! very minor but now the highlighting feature is 100% perfect :)
