### ISSUE TITLE
PulseAudio doesn't switch to bluetooth automatically

### ISSUE THREAD

**Issue by nanthony21** [osmc/osmc#463]
After being very pleasantly surprised to find that with just a little bit of work in the terminal I could get the Raspbery Pi 3's built-in bluetooth adapter to connect to my speakers, I've come across an annoying behavior that I think is probably easy to fix.

After going in to MyOSMC and connecting to my paired speakers (it would be nice if this happened automatically on startup.) I find that pulseaudio doesn't automatically switch over to bluetooth. In order to get audio I need to either ssh in and restart pulseaudio or go into the audio settings of kodi, deseleect PulseAudio as the output and then reselect it.

Would it be possible to make it so that pulseAudio automatically switches to bluetooth when a bluetooth device is connected?

**Comment by graham8** [comment]
Last time I looked, it did switch automatically to BT if pulse was selected as the audio output.  But when a BT device was not there, there was a horrible lag on the default audio device.  It may not be 'easy to fix' without that side effect. Anyway, I suspect the pulse BT setup won't get much love as the plan is to move to bluez-alsa as soon as that can offer similar functionality.

**Comment by samnazarko** [comment]
I will resolve this after Kodi v18 and bring A2DP in to OSMC as standard.

**Comment by mvglasow** [comment]
So that means the next version of OSMC will have full support for Bluetooth speakers? Would be very much appreciated (else this would have been a feature request).

**Comment by graham8** [comment]
You can get it right now. https://discourse.osmc.tv/t/how-to-install-bluez-alsa-for-bluetooth-audio/87908

**Comment by w3tech** [comment]
Really? If that is so, there are already ways to do surround sound with Bluetooth speakers. In fact, wouldn’t it be cool if you could use any collection of Bluetooth speakers to setup surround sound? You actually can.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
