### ISSUE TITLE
OSMC failing (and reboots) after the last update

### ISSUE THREAD

**Issue by PrateekSB** [osmc/osmc#468]
Hello, 

I recently update my OSMC running on rpi 3b. I am now constantly seeing a splash screen upon doing any kind of operations. Please let me know how to debug this.

Regards,
Prateek

**Comment by graham8** [comment]
It will be easier to deal with this on the forum discourse.osmc.tv

**Comment by samnazarko** [comment]
Indeed. This tracker is for confirmed issues only.
