### ISSUE TITLE
HD video playback hangs occasionally 

### ISSUE THREAD

**Issue by michiganimc** [osmc/osmc#470]
After playing several HD files, kodi hangs and only a restart helps.  Please find the log attach. 

[kodi.log](https://github.com/osmc/osmc/files/2522381/kodi.log)

**Comment by samnazarko** [comment]
Please start a forum post with details on the device you are using and a full set of logs via My OSMC

On 28 Oct 2018, at 01:45, michiganimc <notifications@github.com<mailto:notifications@github.com>> wrote:


After playing several HD files, kodi hangs and only a restart helps. Please find the log attach.

kodi.log<https://github.com/osmc/osmc/files/2522381/kodi.log>

**Comment by michiganimc** [comment]
How do I get the full set of logs?  I’m using Vero 4K.

**Comment by bmillham** [comment]
As Sam asked you, please post your problem with logs on https://discourse.osmc.tv

**Comment by michiganimc** [comment]
I will, no problem.  Just one Q: I was able to find only one log file -- /.kodi/temp/kodi.log -- do you need other logs beyond this?

**Comment by samnazarko** [comment]
See https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/

**Comment by michiganimc** [comment]
When I turn the debugging on, a text overlay pops up on top of anything I play -- is there a way to make it go away?  My problem can take some time to emerge and I need to normally watch my videos in the meantime.  I use Vero 4K+.  Thanks

**Comment by samnazarko** [comment]
See https://kodi.wiki/view/Log_file/Advanced#Turn_on_debugging_using_a_file_.28advancedsettings.xml.29
