### ISSUE TITLE
SSL for  download.osmc.tv

### ISSUE THREAD

**Issue by StarPicard** [osmc/osmc#474]
Hello, thank you for building such a great mediacenter!

Reffering to https://github.com/osmc/osmc/issues/251#issuecomment-285919539 I would like to ask if it would be possible to get ssl for download.osmc.tv? As I see you are using Let's encrypt so I think it would not be that hard to implement.

Once again; Thank You!

**Comment by samnazarko** [comment]
Thanks for your kind words. Unfortunately this isn't trivial to do at this time.
You can however verify hashes over HTTPS from the OSMC Download page.

Further, OSMC uses APT which implements signature validation; which negates the need to use HTTPS during the update process.
