### ISSUE TITLE
RPI: HDMI full RGB range on TV startup

### ISSUE THREAD

**Issue by kurac338** [osmc/osmc#479]
Hi, there is a weird behavior on my new Samsung TV.
When I wake the TV from standby, it does not recognize the RPI's HDMI output as full RGB.
I have to switch to some other source (i.e. antenna) and than back to get it working properly.
So on wake the TV sees the source as HDMI normal level, but after I switch back, it sets it as Low level.
Is this a known issue, or TV dependent? I did not experience this behavior before on my old LG TV.

**Comment by samnazarko** [comment]
The issues section is for confirmed bugs only.
Please start a forum post.
