### ISSUE TITLE
[Vero 4K+ BUG REPORT] OSMC/Kodi freezes when trying to play 8K video

### ISSUE THREAD

**Issue by martinrotter** [osmc/osmc#487]
LOGS - `https://paste.osmc.tv/qeyukatesi`

How to reproduce:
1. Obtain some 8K video from YouTube and place onto USB flash drive.
2. Insert USB flash drive into Vero.
3. Try to play video from USB flash drive.
4. Video does not start playing (of course).
5. **Whole GUI of Kodi completely freezes and I have to hard reboot with SSH or plug-out/in power cord.**

Kodi/OSMC should handle unsupported video/audio/whatever formats gracefully and should maybe display messagebox "Cannot play this file." instead of just freezing.

**Comment by samnazarko** [comment]
Agreed on warning message; although this will take a bit of mid-term work.
In the interim, introducing sd support will mitigate Kodi freezes.

**Comment by samnazarko** [comment]
While this is arguably a Kodi issue, we can never rely on it to always be stable.
Best plan is to use systemd watchdog support to restart the process if it hangs. But this needs some work to allow exit to handle gracefully (some IPC needed here).

**Comment by martinrotter** [comment]
OK, reported upstream.

**Comment by samnazarko** [comment]
Can you provide a reference to the upstream issue?

Relying on Kodi to tell you when a file cannot be played will always be ambitious; although it's not infeasible. 

AML has platform specific checks and if they are not compatible they are deferred to ffmpeg (SW) decoding. Same for other platforms.

**Comment by martinrotter** [comment]
https://github.com/xbmc/xbmc/issues/15388

Why ambitious? From my POV this seems a reasonable request. It certainly should not just hang...

**Comment by samnazarko** [comment]
There will always be broken files. It is not always possible to anticipate this.

In the case of 8K videos: the Vero isn't designed or advertised to play 8K content.

I'll take a look at this -- but hope you can appreciate that it's quite low on the list; there aren't many users that try and play 8K content (presumably demos) on this 4K device.

I can add a downstream clamp on max res in the interim; but warning messages wouldn't be localised.
Alternatively, and more practically, we can refuse to play the file and CLog (ERROR) with details why. This is better for diagnostic purposes.

**Comment by martinrotter** [comment]
I dont blame Vero of this. Vero is great device and I completely expected the video to not play.

It just should not freeze/hand the device completely. Even crash/restart of Kodi would be better outcome than hard freeze.

**Comment by samnazarko** [comment]
From the fact you've posted a log, I'm guessing SSH was still up.
If so -- then Kodi has crashed.

This will be mitigated by adding watchdog support to Kodi which will come soon.
I will add a warning for 'This content may not play optimally' etc for some content like Hi10.

**Comment by martinrotter** [comment]
@samnazarko To me, this seems to reasonable "fix". It seems good approach to just check dimensions (and probably other metadata) of the file before it is played, and if those metadata indicate that the file clearly cannot be played, then do not even try to play it.

**Comment by samnazarko** [comment]
That would be more indicative of an OOPS to me that hung the system.
General hangs will be resolved promptly; but more niche situations like playing 8K will take longer to address.
