### ISSUE TITLE
SFTP Crashes OSMC in nightly when enabling vfs.sftp Add-On.

### ISSUE THREAD

**Issue by NonaSuomy** [osmc/osmc#495]
I think this may be related to building KODI against libssl1.0 instead of 1.1 referenced here: 

[vfs.sftp issue](https://github.com/xbmc/vfs.sftp/issues/25)

Updated platform to current gmc-19

Click My Add-Ons -> Virtual filesystems -> SFTP support -> enable. 

Instant crash, after enable, and then sadface boot loop until you manually ssh in and disable sftp again.

**Comment by samnazarko** [comment]
If you are using gmc-19, please start a debug log on the appropriate test build post.

**Comment by NonaSuomy** [comment]
It's also in gmc-18 as sftp was removed in leia and moved to a plugin. Updated to gmc-19 to see if it was fixed. Where do I find the place to report this issue for gmc-18/19 doesn't seem to be under branches...

**Comment by samnazarko** [comment]
GMC builds aren't officially part of OSMC, so reporting here isn't the best place.

They're produced by one of our devs as experimental. You should post details on the nightly thread where you followed the instructions to install the builds.

**Comment by samnazarko** [comment]
I have brought this issue to gmc now and believe he is working on a solution, but it's still worth making a post so that the issue can be tracked properly.

**Comment by NonaSuomy** [comment]
Thank you for the further information.

**Comment by NonaSuomy** [comment]
This is fixed now after compiling against libssl1.1 GMC-19 18.8-3, 17 March 2019 for future references [testing-kodi-18-leia-builds-for-raspberry-pi](https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631/1657?u=nonasuomy)
