### ISSUE TITLE
Movie has dupicate chapters at the end

### ISSUE THREAD

**Issue by Hakun1n** [osmc/osmc#496]
Heya, 

I have a movie file (Alien) which has duration 1:56:37 - Win media player, VLC and Zoom player - all of them shows proper length. No issues here.

But when i add the same movie to my library in Kodi it suddenly has length 2:48:11. I found that the first 1:56:37 are correct and the movie plays in its full scale without issues but once it reaches its "end" (closing titles included) some chapters are played again for no obvious reason. I don't understand but seems to be a bug so here i am.

I am running OSMC 2018.12-1 on VERO 4K+

Short record of what is happening:
https://youtu.be/Ehax6_pSAfM

Media Info:
[AlienMI.txt](https://github.com/osmc/osmc/files/3010076/AlienMI.txt)

MKV content:
![image](https://user-images.githubusercontent.com/12685294/55029276-01b45000-500a-11e9-92ff-2b72848aafbb.png)

Kodi DEBUG log with video component log enabled (Matches the video on Youtube above)
[Alien.log](https://github.com/osmc/osmc/files/3010126/Alien.log)

This is how it looks like on PC in VLC:
![image](https://user-images.githubusercontent.com/12685294/55031087-12ff5b80-500e-11e9-86f9-f4a2d7ead724.png)

Please let me know if you need more information.

Thank you in advance

Alex

**Comment by samnazarko** [comment]
Can you try remuxing the file with MKVToolnix?

On 26 Mar 2019, at 20:32, Hakun1n <notifications@github.com<mailto:notifications@github.com>> wrote:


Heya,

I have a movie file (Alien) which has duration 1:56:37 - Win media player, VLC and Zoom player - all of them shows proper length. No issues here.

But when i add the same movie to my library in Kodi it suddenly has length 2:48:11. I found that the first 1:56:37 are correct and the movie plays in its full scale without issues but once it reaches its "end" (closing titles included) some chapters are played again for no obvious reason. I don't understand why so here i am hoping someone can help me to fix this.

I am running OSMC 2018.12-1 on VERO 4K+

Short record of what is happening:
https://youtu.be/Ehax6_pSAfM

Media Info:
AlienMI.txt<https://github.com/osmc/osmc/files/3010076/AlienMI.txt>

MKV content:
[image]<https://user-images.githubusercontent.com/12685294/55029276-01b45000-500a-11e9-92ff-2b72848aafbb.png>

Kodi DEBUG log with video component log enabled (Matches the video on Youtube above)
Alien.log<https://github.com/osmc/osmc/files/3010126/Alien.log>

This is how it looks like on PC in VLC:
[image]<https://user-images.githubusercontent.com/12685294/55031087-12ff5b80-500e-11e9-86f9-f4a2d7ead724.png>

Please let me know if you need more information.

Thank you in advance

Alex

**Comment by Hakun1n** [comment]
Oh, i forgot to mention that i've already tried that. I even removed the chinese subtitles, AAC audio and global tags.

But i can try to remux again if you have specific request.

**Comment by samnazarko** [comment]
Can you upload full debug logs via My OSMC? I want to see the ffmpeg parsing data

On 26 Mar 2019, at 20:37, Hakun1n <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, i forgot to mention that i've already tried that. I even removed the chinese subtitles, AAC audio and global tags.

But i can try to remux again if you have specific request.

**Comment by Hakun1n** [comment]
Done, logs uploaded. I've sent you PM of forum with link as i don't want to expose network details.

**Comment by nabsltd** [comment]
> I have a movie file (Alien) which has duration 1:56:37 - Win media player, VLC and Zoom player - all of them shows proper length. No issues here.

Based on the "Director's Cut" in the mediainfo, but the time of 1:56:37 is for the theatrical cut (director's cut is about a minute shorter), my guess is that there used to be more than one set of chapters, with MKV seamless branching, but I don't think Kodi supports that, and definitely won't without the extra chapter listing.

I think that if you look closely, you'll see that the "duplicate" chapters at the end are slightly different:
https://www.imdb.com/title/tt0078748/alternateversions

The other players just ignore the extra data.

**Comment by Hakun1n** [comment]
@nabsltd Ha, you've nailed it. I have "Aliens" from the same BR boxset and it has the same "Issue" in Kodi. But when observing the chapter list i see two chapter sets as you mentioned. Apparently I've messed up the first movie but the second one is OK.

So basically i just have to cut-off the extra part because Kodi does not handle such situation. I am OK to have only the "Theatrical" version in my Kodi library.

![image](https://user-images.githubusercontent.com/12685294/55044549-0fce9480-503b-11e9-9cd2-3fd09e9b881e.png)

**Comment by samnazarko** [comment]
Glad this is now solved.
OK to close?

**Comment by Hakun1n** [comment]
Yes, resolved. I've used MKVToolnix to split by time 00:00:00-01:56:37 and dropped the rest. Output file is perfect, chapters from the existing sets matches the scenes. Thanks for help/explanation :]
