### ISSUE TITLE
Release signing key expired in march 8 2019 for apt xenial repository

### ISSUE THREAD

**Issue by redwil** [osmc/osmc#497]
FYI
As per title the signing key (http://download.opensuse.org/repositories/home:/osmc/xUbuntu_16.04/Release.key) expired

**Comment by samnazarko** [comment]
Thanks -- there's a forum post regarding this issue; but I'm not sure how to renew the key under OBS presently.

**Comment by samnazarko** [comment]
The Linux installer is now deprecated.
Use dd for now until the new installer is released.
