### ISSUE TITLE
crash on large seek (up arrow) with latest update

### ISSUE THREAD

**Issue by vajonam** [osmc/osmc#498]
With the latest update from today I am seeing crash (sad face) when I seek a video using the "UP" arrow, or chapter seek. using the left and right I am able to seek fine. 

```
$ uname -a
Linux osmc 3.14.29-134-osmc #1 SMP Mon Dec 31 00:16:36 UTC 2018 aarch64 

ii  vero3-mediacenter-osmc               18.8-19                        armhf        Media Center package for OSMC
```

here is the [log](http://paste.ubuntu.com/p/XyWjX2YwKW/)

**Comment by samnazarko** [comment]
Unfortunately the log does not provide significant detail.
Please see https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/.

**Comment by vajonam** [comment]
closing because of not enough detail or already fixed?

**Comment by samnazarko** [comment]
Closing because the issue tracker is for confirmed bugs.
Forum is for support.

**Comment by vajonam** [comment]
until this is confirmed bug :-) https://discourse.osmc.tv/t/crash-on-large-seek-up-arrow/79200 

thanks for the quick reply
