### ISSUE TITLE
Post-install setup doesn't create locales

### ISSUE THREAD

**Issue by CRCulver** [osmc/osmc#50]
When installing, I chose "English" (the only option given in the Alpha 1 installer). When I then logged in via SSH after installation, I got a warning that my specified locale (`en_GB.UTF-8`) was not available and the shell was falling back on the plain C locale instead. (Because OSMC's `/etc/ssh/sshd_config` file has the line `AcceptEnv LANG LC_*`, SSH asks for the same locale on the OSMC device that I have on the computer I’m running SSH from.)  I had to manually run `dpkg-reconfigure locales` on the OSMC installation to generate that locale.

So, the installer will need to insure that a locale is generated to match the language chosen during installation. If only one generic `English` option is to be offered in the installer, you’ll have to generate all of the `en_**.UTF-8` locales to cover US/UK/etc. users.

**Comment by akaihola** [comment]
On Alpha 4, on first SSH login it started generating locales:
```
$ ssh osmc@xx.xx.xx.xx
The authenticity of host 'xx.xx.xx.xx (xx.xx.xx.xx)' can't be established.
ECDSA key fingerprint is *****.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'xx.xx.xx.xx' (ECDSA) to the list of known hosts.
OSMC: Open Source Media Center
osmc@xx.xx.xx.xx's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Generating locales (this might take a while)...
  fi_FI.UTF-8... 
```
And it just sits there forever. I was able to connect in another terminal window simultaneously.
