### ISSUE TITLE
Bold cyrillic text can not be displayed

### ISSUE THREAD

**Issue by CTYDEHb** [osmc/osmc#515]
After the last update the selected option in the menu is displayed as a bunch of ☒ for every character if it is cyrillic text. Regular text is fine though.

**Comment by Ch1llb0** [comment]
Which skin are you using? We've tested Cyrillic bold text with our own OSMC skin and it's working fine...

**Comment by CTYDEHb** [comment]
OSMC Skin. All interface settings are default.
Is there a method to take a screenshot through ssh on osmc?

**Comment by Ch1llb0** [comment]
Yup, see here: https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/

Is this happening in a specific window? Just asking to be able to reproduce. We haven't been able to yet.

**Comment by Ch1llb0** [comment]
This should be adressed with the next update that's around the corner, I believe :)

**Comment by samnazarko** [comment]
Closing as this should now be fixed
