### ISSUE TITLE
Selecting a custom build does not always bring up file selection dialog

### ISSUE THREAD

**Issue by samnazarko** [osmc/osmc#52]
In the host installer, if you select a custom build, then click Cancel, and then click use custom build again, the browse dialog doesn't show up unless you untick it and reclick it again. It seems the untick action from clicking cancel is not properly triggering the slot notifier that the checkbox has changed.

**Comment by srmo** [comment]
Potentially fixed. Looks like it may have been triggered by https://bugreports.qt-project.org/browse/QTBUG-15309
