### ISSUE TITLE
DLNA and subtitles

### ISSUE THREAD

**Issue by fallais** [osmc/osmc#533]
Hello to all the team,

And thanks for your work. I am enjoying great moments with OSCM / RPi / Official Remote Controller.
That being said, I am facing an issue with the DLNA, more especially when I change the subtitles. I need to go back, and then play the episode again.

Is it normal please ?

I would expect that when I am watching an episode, I would be able to change the subtitle and the modification is applied directly. As well as the language.

Regards,
F.

**Comment by samnazarko** [comment]
Please start a forum post with debug logs. This issue tracker is for confirmed issues.
