### ISSUE TITLE
Problem with video h264 on raspberry 3

### ISSUE THREAD

**Issue by mikysal78** [osmc/osmc#535]
I have the video converted with ffmpeg and cuda:
-hwaccel nvdec -hwaccel_output_format cuda
-c:v h264_nvenc -rc vbr_hq
-acodec ac3 -ac 6 -strict experimental -ar 48000 -b:a 1536k -metadata:s:a:0 language=ita
See my file [1080p](https://github.com/mikysal78/scripting/blob/master/videoconverter)

OSMC on RaspBerry don't work, audio ok...video no.
because?
Thanks.

**Comment by samnazarko** [comment]
Hi,

This issue tracker is for confirmed issues.
Please start a forum post with MediaInfo.
