### ISSUE TITLE
international keyboard layouts does not work on hardware keyboard on kodi 18.5.

### ISSUE THREAD

**Issue by virserg** [osmc/osmc#537]
international keyboard layouts does not work on hardware keyboard on kodi 18.5. But it works on version 17.6 kodi (right-alt key).

who has a patch for this?

Sorry, my bad English.

**Comment by samnazarko** [comment]
This issue tracker is for confirmed issues. Please start a support request first. https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/
