### ISSUE TITLE
Subtitle downloader doesnt work if previous video wasnt played until the end.

### ISSUE THREAD

**Issue by xoleja01** [osmc/osmc#544]
Hello,

I beleive, I found a small bug in OSMC but didnt found any better place to report it.

If you stop previous video early (let say, skip credits), subtitle downloader will fail. There is blank space where name of actualy playing video should be when you try to download subtitles. This issue doesnt occur when previous video run to the end and close naturaly. 

If this happens, all what is need to do is to move any video to the end so it close naturaly and downloader is working again, it is a bit annoying solution thou.

**Comment by samnazarko** [comment]
Please start a support request, as this section is for confirmed issues only.
