### ISSUE TITLE
osmc.tv documentation issues

### ISSUE THREAD

**Issue by evitalis** [osmc/osmc#547]
Supported devices says any Raspberry Pi later than the RPI 2 is supported but in #521 it is explicitly stated the RPI 4 is not supported. For new comers to OSMC who may not have experience with GitHub to search the issues it is important to properly list of the main site. Perhaps this is listed somewhere else I was not able to find on the osmc.tv wiki?

On the 'Getting Involved with OSMC development' the listed OS have issues. Ubuntu 14.04 has been of of standard support since 2019 and Debian 8 LTS goes EOL in a few months. Are there plans to update the list of supported OS? Sure there might be a little time left on Ubuntu 14.04 per their releases page but in 2020 its very dated, and without resorted to a search engine its a pain to find the download link for.

**Comment by samnazarko** [comment]
You can already build with 9.0 and 16.04

I’m happy to accept a PR to update our docs or any suggestions you have

Cheers

Sam

**Comment by evitalis** [comment]
The suggestions are present in the post. I am not sure I will get to a PR but hopefully the docs get properly updated to not confuse new users.

**Comment by samnazarko** [comment]
I've updated the documentation to reflect the versions of Ubuntu and Debian that can be used.

**Comment by evitalis** [comment]
@samnazarko The supported devices were not updated. Do you support the RPI 4 or not?

**Comment by samnazarko** [comment]
No - but we don’t list the devices we don’t support. We list the devices we do support. Pi4 is still WIP.

On 15 Feb 2020, at 15:15, evitalis <notifications@github.com> wrote:

﻿

@samnazarko<https://github.com/samnazarko> The supported devices were not updated. Do you support the RPI 4 or not?

**Comment by evitalis** [comment]
@samnazarko See the quote from your website below:

> Raspberry Pi
> 
> OSMC runs on all models of Raspberry Pi. We recommend you use a Class 10 SD card, a stable power supply, and at least the Pi Model 2 for the best experience.

If you do not support the RPi 4 that the first statement is blatantly false given your last statement. Sure you don't need to list every unsupported device but the wording should be accurate for what you do support.

**Comment by samnazarko** [comment]
This is pretty poor trolling.

On 15 Feb 2020, at 15:21, evitalis <notifications@github.com> wrote:

﻿

@samnazarko<https://github.com/samnazarko> See the quote from your website below:

Raspberry Pi

OSMC runs on all models of Raspberry Pi. We recommend you use a Class 10 SD card, a stable power supply, and at least the Pi Model 2 for the best experience.

If you do not support the RPi 4 that the first statement is blatantly false given your last statement. Sure you don't need to list every unsupported device but the wording should be accurate for what you do support.

**Comment by evitalis** [comment]
I am not trolling just helping you to avoid confusion among your users. With the documentation as it is then it is possible more issues will be opened asking about the rpi 4 if someone attempts to use OSMC and it does not work as expected, so to be fair updating the documentation will also help you avoid these situations.

**Comment by samnazarko** [comment]
I think it is trolling given you’ve stated that this is ‘blatantly false’ which suggests we may be trying to mislead users. It should be clear from the suggested model (Pi 2) and distribution versions that the documentation is simply out of date. Anyone is welcome to update the documentation; which begs the question of why this wasn’t opened in the form of a PR instead.

The documentation has since been updated and I welcome any further changes / suggestions in the form of a PR. 

Cheers

Sam
