### ISSUE TITLE
No kernel headers metapackage

### ISSUE THREAD

**Issue by alkisg** [osmc/osmc#548]
Hi, rbp2-kernel-osmc depends on the latest kernel image like rbp2-image-4.19.55-6-osmc.
But there's no package that depends on the latest kernel **headers** like rbp2-headers-4.19.55-6-osmc, as in other distributions.
So, after each kernel upgrade, I have to manually install the matching headers.

This makes it very hard to have dkms-based modules installed, like some Realtek wifi adapters, but it's also an issue outside of dkms.

Ideally, the headers name is derived by replacing "image" with "headers", for example:

- Debian: linux-image-686 => linux-headers-686
- Debian: linux-image-amd64 => linux-headers-amd64
- Debian: linux-image-armmp => linux-headers-armmp
- Ubuntu: linux-image-generic => linux-headers-generic
- Ubuntu: linux-image-lowlatency-hwe-16.04 => linux-headers-lowlatency-hwe-16.04

So I would suggest that rbp2-kernel-osmc be renamed to linux-image-osmc, and then provide linux-headers-osmc, but of course any name will do the job.

Thanks!

**Comment by samnazarko** [comment]
I’m happy to do this but please keep in mind it’s not a magic bullet, even if your goal is to use something like DKMS.

You mentioned in IRC that you are maintaining RTL WiFi drivers. For which chipsets?

On 29 Feb 2020, at 06:20, Alkis Georgopoulos <notifications@github.com> wrote:

﻿

Hi, rbp2-kernel-osmc depends on the latest kernel image like rbp2-image-4.19.55-6-osmc.
But there's no package that depends on the latest kernel headers like rbp2-headers-4.19.55-6-osmc, as in other distributions.
So, after each kernel upgrade, I have to manually install the matching headers.

This makes it very hard to have dkms-based modules installed, like some Realtek wifi adapters, but it's also an issue outside of dkms.

rbp2-headers currently is a virtual package, maybe it could become a metapackage, or if that's not desired, a different name could be used for the metapackage, e.g. rbp2-headers-osmc.

Thanks!

**Comment by samnazarko** [comment]
﻿
I’m happy to do this but please keep in mind it’s not a magic bullet, even if your goal is to use something like DKMS.

You mentioned in IRC that you are maintaining RTL WiFi drivers. For which chipsets?

On 29 Feb 2020, at 06:20, Alkis Georgopoulos <notifications@github.com> wrote:

﻿

Hi, rbp2-kernel-osmc depends on the latest kernel image like rbp2-image-4.19.55-6-osmc.
But there's no package that depends on the latest kernel headers like rbp2-headers-4.19.55-6-osmc, as in other distributions.
So, after each kernel upgrade, I have to manually install the matching headers.

This makes it very hard to have dkms-based modules installed, like some Realtek wifi adapters, but it's also an issue outside of dkms.

rbp2-headers currently is a virtual package, maybe it could become a metapackage, or if that's not desired, a different name could be used for the metapackage, e.g. rbp2-headers-osmc.

Thanks!

**Comment by alkisg** [comment]
Hi samnazarko, thank you for the feedback,
we've been using 8812au (which you already include a driver for) but then it got kind of old and we replaced it with 88x2bu and 8821cu.

**Comment by samnazarko** [comment]
We will re-add support for some drivers, including RTL8812AU

On 29 Feb 2020, at 18:27, Alkis Georgopoulos <notifications@github.com> wrote:

﻿

Hi samnazarko, thank you for the feedback,
we've been using 8812au (which you already include a driver for) but then it got kind of old and we replaced it with 88x2bu and 8821cu.

**Comment by samnazarko** [comment]
I've made *-image-osmc depend on the relevant headers package, so this will be brought in automatically across updates. I was considering making this a separate metapackage but the dependency is light enough, and likely used enough, that it makes sense to include this by default. 

Obviously DKMS isn't the most reliable, so it'll be on you to ensure that your module sources are compatible.

Cheers

Sam

**Comment by alkisg** [comment]
Great, thank you very much!
