### ISSUE TITLE
"PRETTY_NAME="Open Source Media Center"" - Double Quotes causing issues

### ISSUE THREAD

**Issue by ncsufan8628** [osmc/osmc#553]
Hello,

It seems the double quotes in the linked file here are creating issue when compiling/installing other packages on my RPi.  

`... jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.Release.Value = "PRETTY_NAME="Open Source Media Center""                               
jq: 1 compile error
`

https://github.com/osmc/osmc/blob/master/package/base-files-osmc/files/etc/os-release

Manually editing this file to make the Pretty Name value use '-' or '_' vs spaces removes the need for the double quoting and resolves my compile error.

**Comment by samnazarko** [comment]
It would help to know what program you are compiling.
Distributions usually use double quotes. On Ubuntu, I get:

PRETTY_NAME="Ubuntu 16.04.5 LTS"

**Comment by ncsufan8628** [comment]
Hi Sam,

Unfortunately, I do not remember.  The error was retriggered after running a dist-upgrade.

If I remember correctly, I think it might have been NodeJS.  However, here is the full terminal output from dist-upgrade. 

`osmc@AudioSVR:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  armv7-eventlircd-osmc armv7-network-osmc base-files-osmc icu-devtools libicu-dev libicu57 mediacenter-skin-osmc perftune-osmc rbp-bootloader-osmc rbp2-mediacenter-osmc
10 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 128 MB of archives.
After this operation, 4,231 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://security.debian.org stretch/updates/main armhf libicu-dev armhf 57.1-6+deb9u4 [15.9 MB]
Get:2 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf armv7-network-osmc armhf 1.7.7 [3,910 B]       
Get:3 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf base-files-osmc all 2.8.7 [20.1 kB]
Get:4 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf perftune-osmc all 1.2.5 [2,162 B]
Get:5 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf rbp-bootloader-osmc armhf 3.3.0-1 [2,159 kB]
Get:9 http://security.debian.org stretch/updates/main armhf icu-devtools armhf 57.1-6+deb9u4 [163 kB]
Get:10 http://security.debian.org stretch/updates/main armhf libicu57 armhf 57.1-6+deb9u4 [7,451 kB]
Get:6 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf mediacenter-skin-osmc all 18.2.0-37 [9,268 kB]
Get:7 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf rbp2-mediacenter-osmc armhf 18.6.0-5 [93.2 MB]                                                                                                                           
Get:8 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf armv7-eventlircd-osmc armhf 1.4.3 [36.9 kB]                                                                                                                              
Fetched 128 MB in 28s (4,577 kB/s)                                                                                                                                                                                                
(Reading database ... 64208 files and directories currently installed.)
Preparing to unpack .../0-armv7-network-osmc_1.7.7_armhf.deb ...
Unpacking armv7-network-osmc (1.7.7) over (1.7.6) ...
Preparing to unpack .../1-base-files-osmc_2.8.7_all.deb ...
Unpacking base-files-osmc (2.8.7) over (2.8.6) ...
Preparing to unpack .../2-perftune-osmc_1.2.5_all.deb ...
Unpacking perftune-osmc (1.2.5) over (1.2.4) ...
Preparing to unpack .../3-rbp-bootloader-osmc_3.3.0-1_armhf.deb ...
Unpacking rbp-bootloader-osmc (3.3.0-1) over (3.1.0-1) ...
Preparing to unpack .../4-mediacenter-skin-osmc_18.2.0-37_all.deb ...
Unpacking mediacenter-skin-osmc (18.2.0-37) over (18.2.0-30) ...
Preparing to unpack .../5-rbp2-mediacenter-osmc_18.6.0-5_armhf.deb ...
Unpacking rbp2-mediacenter-osmc (18.6.0-5) over (18.5.0-4) ...
Preparing to unpack .../6-armv7-eventlircd-osmc_1.4.3_armhf.deb ...
Unpacking armv7-eventlircd-osmc (1.4.3) over (1.3.9) ...
Preparing to unpack .../7-libicu-dev_57.1-6+deb9u4_armhf.deb ...
Unpacking libicu-dev (57.1-6+deb9u4) over (57.1-6+deb9u3) ...
Preparing to unpack .../8-icu-devtools_57.1-6+deb9u4_armhf.deb ...
Unpacking icu-devtools (57.1-6+deb9u4) over (57.1-6+deb9u3) ...
Preparing to unpack .../9-libicu57_57.1-6+deb9u4_armhf.deb ...
Unpacking libicu57:armhf (57.1-6+deb9u4) over (57.1-6+deb9u3) ...
Setting up perftune-osmc (1.2.5) ...
Processing triggers for mime-support (3.60) ...
Setting up armv7-eventlircd-osmc (1.4.3) ...
Setting up libicu57:armhf (57.1-6+deb9u4) ...
Setting up base-files-osmc (2.8.7) ...
Fixing permissions on busybox.
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up rbp-bootloader-osmc (3.3.0-1) ...
Setting up mediacenter-skin-osmc (18.2.0-37) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up icu-devtools (57.1-6+deb9u4) ...
Setting up armv7-network-osmc (1.7.7) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Setting up rbp2-mediacenter-osmc (18.6.0-5) ...
Setting up libicu-dev (57.1-6+deb9u4) ...
Updating FireMotD available updates count ... jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.Release.Value = "PRETTY_NAME="Open Source Media Center""                               
jq: 1 compile error

`

**Comment by samnazarko** [comment]
You should take this up with the package maintainer -- the /etc/os-release is compliant.

**Comment by ncsufan8628** [comment]
ok, thanks!
