### ISSUE TITLE
Bluetooth memory leak

### ISSUE THREAD

**Issue by karlkashofer** [osmc/osmc#562]
Hi ! I seem to have a serious memory leak on my Rpi3 running OSMC:
>2020-06-21 09:24:15.252 T:1915995696  NOTICE: Starting Kodi (18.6). Platform: Linux ARM (Thumb) 32-bit
2020-06-21 09:24:15.252 T:1915995696  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-06-21 09:24:15.252 T:1915995696  NOTICE: Kodi compiled 2020-03-20 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.110 (264558)
2020-06-21 09:24:15.252 T:1915995696  NOTICE: Running on Open Source Media Center 2020.03-1, kernel: Linux ARM 32-bit version 4.19.55-6-osmc

I get slow memory creep until the pi finally becomes unresponsive and needs to be restarted:
![memory-week](https://user-images.githubusercontent.com/10479423/85219465-43b27a00-b3a4-11ea-94ad-27c01fb2b6e6.png)

This started when i installed bluetooth support.
Checking the log i find these Warnings:
>2020-06-20 19:34:23.992 T:1601127136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'isBTPlayerActive'
                                            Traceback (most recent call last):
                                              File "/usr/share/kodi/addons/service.osmc.btplayer/service.py", line 195, in onPlayBackStopped
                                                if xbmc.isBTPlayerActive() and self.btPlayer.isPlaying() and self.btPlayer.player:
                                            AttributeError: 'module' object has no attribute 'isBTPlayerActive'
                                            -->End of Python script error report<--

Any idea what could be wrong ?

This is the installed bt app:
>osmc@osmc:~/.kodi/temp$ apt show a2dp-app-osmc
Package: a2dp-app-osmc
Origin: OSMC
Version: 1.1.3
Essential: No
Depends: bluez, pulseaudio, pulseaudio-module-bluetooth, pulseaudio-module-zeroconf
Architecture: all
Maintainer: Sam G Nazarko <email@samnazarko.co.uk>
Priority: required
Section: metapackages
Filename: pool/main/a/a2dp-app-osmc/a2dp-app-osmc_1.1.3_all.deb
Size: 110782
SHA256: 63e9305aafb47d954cb444dcdb3c0cd59cd2b94f034f084e612b7ad7909c9d8e
SHA1: e39d17dbe8367da6a529a426ed6a5d5f0653fe16
MD5sum: db0abc3d4f3bda8ac8f54609895c87a5
Description: A2DP streaming capabilities for OSMC
Description-md5: 7b5dac4a5260bd86b63c1fe69b598dff
Installed-Size: 204

**Comment by samnazarko** [comment]
Did this only occur after installing a2dp-app-osmc? This package is now deprecated and we are moving to Bluez-alsa.

**Comment by karlkashofer** [comment]
Yes, i think so. I have now removed a2dp-app-osmc and its been stable for a while, need to leave it running a few days though. Will report back.

Whats the current state of Bluez-alsa ?

**Comment by samnazarko** [comment]
It’s still a work in progress.
Should be ready over the Summer.

On 21 Jun 2020, at 20:26, karlkashofer <notifications@github.com> wrote:

﻿

Yes, i think so. I have now removed a2dp-app-osmc and its been stable for a while, need to leave it running a few days though. Will report back.

Whats the current state of Bluez-alsa ?

**Comment by karlkashofer** [comment]
Well, it seems its not the bluetooth addon after all:

![memory-day](https://user-images.githubusercontent.com/10479423/85288595-47262e00-b496-11ea-8952-c2b7c8964a66.png)

Kodi eats 64% CPU and 45% Mem of my Pi3, it constantly writes data at a rate of 60-100kb/s with a thread called [LanguageInvoker].

Any idea how to find out what is going on?

**Comment by samnazarko** [comment]
Sounds like a Python add-on causing this then.

On 22 Jun 2020, at 13:44, karlkashofer <notifications@github.com> wrote:

﻿

Well, it seems its not the bluetooth addon after all:

[memory-day]<https://user-images.githubusercontent.com/10479423/85288595-47262e00-b496-11ea-8952-c2b7c8964a66.png>

Kodi eats 64% CPU and 45% Mem of my Pi3, it constantly writes data at a rate of 60-100kb/s with a thread called [LanguageInvoker].

Any idea how to find out what is going on?

**Comment by karlkashofer** [comment]
Ok, will start disabling addons until i find the culprit. 
Any simple way to get log files for/from addons ?

**Comment by samnazarko** [comment]
The details will be in the Kodi.log.

**Comment by karlkashofer** [comment]
Well, I dont see anything else suspicious in kodi.log, so i'll have to go trial-error and disable addons one by one.

I think its time to close this now, sorry for the confusion, thanks for the help.
Cheers,
Karl
