### ISSUE TITLE
sources.list has non-secure (http) URLs

### ISSUE THREAD

**Issue by jorti** [osmc/osmc#591]
The apt repositories in `/etc/apt/sources.list` have all non-secure http URLs.

This is a security problem and these URLs must be on https.

**Comment by samnazarko** [comment]
APT uses a signing mechanism which prevents tampering of binaries in transit. Even with HTTP interception, it’s not possible to force binaries on user’s systems.

While we endeavour to serve APT over HTTPS in the near future, this is not currently possible. This will prevent malicious actors from knowing what versions of a package are running on a system, which will provide some further security.

I would suggest researching how APT works.

On 30 Dec 2020, at 14:20, Juan Orti Alcaine <notifications@github.com> wrote:

﻿

The apt repositories in /etc/apt/sources.list have all non-secure http URLs.

This is a security problem and these URLs must be on https.

**Comment by claudep** [comment]
@samnazarko's answer is confirmed by https://wiki.debian.org/SourcesList. I'd suggest to close this issue.

**Comment by samnazarko** [comment]
We now use HTTPS for all repositories by default for some time, closing as fixed.
Note that this is only the default on relatively new installations.
