### ISSUE TITLE
Question: Microsoft repos being installed on raspbian

### ISSUE THREAD

**Issue by ricardoandren** [osmc/osmc#594]
Does this privacy vulnerability also impact osmc? And are there any plans to add this repo to osmc aswell, I hope not.

https://hothardware.com/news/raspberry-pi-microsoft-repository-phones-home-added-pi-os

**Comment by graham8** [comment]
:rofl:

**Comment by samnazarko** [comment]
OSMC is not based on Raspbian. We use Debian as upstream.

My understanding is that Raspberry Pi have added the Visual Studio Code repository from Microsoft to facilitate easier installation of this package.

As we're a media center OS, we don't plan to include the necessary repositories to install Visual Studio Code. This is an IDE and we don't think this would be beneficial for our primary use case. Of course -- users that wish to do so can do so simply by editing their APT sources.list.

We only include the Debian and OSMC repositories for package management. 

Thanks

Sam
