### ISSUE TITLE
Is script.module.elementtree still useful

### ISSUE THREAD

**Issue by claudep** [osmc/osmc#596]
I can see in the logs that `script.module.elementtree` was removed in 3d39539fef90, and then re-added in da8ed26a3a548. Is there a discussion somewhere about that? Is that module still really useful, as ElementTree is part of the standard Python lib since Python 2.5?

**Comment by anxdpanic** [comment]
This should be removed again(not yet, but is expected to be) as part of the Python 3 rework

**Comment by samnazarko** [comment]
This is now removed.
