### ISSUE TITLE
hifiberry-digi overlay not getting loaded in August update

### ISSUE THREAD

**Issue by banburybill** [osmc/osmc#648]
In MyOSMC Raspberry Pi setup/Hardware, selecting 'hifiberry-digi-overlay` results in `config-user.txt` containing:

`dtoverlay=hifiberry-digi-overlay`

and no overlay gets loaded. The line should be

`dtoverlay=hifiberry-digi`

**Comment by tinwasp** [comment]
Same for other soundcard overlays: there's an erroneous "-overlay" that gets added to config-user.txt when enabling a piece of hardware (DAC, Digiamp...).

**Comment by samnazarko** [comment]
This is already fixed. 

Cheers

Sam
