### ISSUE TITLE
open-iscsi not working with kernel vero364

### ISSUE THREAD

**Issue by imhof-marco** [osmc/osmc#649]
The package open-iscsi can not be installed without error because of missing Kernel-Modules scsi_transport_iscsi, iscsi_tcp and libiscsi.

Can you activate them on kernel vero364 as they are on vero2?

Use Case: Accessing Blue-Ray Device on NAS-System with Vero4k+

**Comment by samnazarko** [comment]
I'd be happy to add this to the kernel config.

Can you please give the exact CONFIG_ options needed?

Many thanks

**Comment by popindavibe** [comment]
Having the same request, just got a Vero 4K+ for myself, but I can't use it :cry:

**Comment by samnazarko** [comment]
Can you let me know the CONFIG_ options needed to enable this? I’ll happily get this included for you

**Comment by popindavibe** [comment]
Unfortunately no, I can't. But if I eventually find out I'll let you know. Quite disappointed if I can't find that information though, I have a nice useless little black box at the moment. The Pi 4 was handling it out of the box.

**Comment by samnazarko** [comment]
Was the Pi 4 running OSMC? I can diff the options.

I can take a stab at supporting this for you and produce some images for you to test for sure, if you’re happy to potentially try a couple of iterations.

**Comment by popindavibe** [comment]
Yes, it was running OSMC. But I lost the Pi 4 unfortunately (which is how I ended up getting a Vero).

I'll see if I can get a hold on another Pi (most likely Pi 2 or 3) and extract the options from it after installing OSMC. It may take some time, but hopefully I should be able to  provide that information eventually.

I have no issues playing beta-tester for that feature.

**Comment by samnazarko** [comment]
Okay, not a problem. Do you mind starting a forum post requesting this? It’ll make it easier to send you some test builds.

I can send you send a test build which you can boot off external media (USB or SD card), so we can rapidly iterate if needed which doesn’t ruin your existing install.

**Comment by samnazarko** [comment]
Hi,

I've prepared some test images.

Please start a forum account so I can share this with you. Referencing this ticket.
