### ISSUE TITLE
Sad face when playing ANY file because MySQL Database is not connected but configured

### ISSUE THREAD

**Issue by jochenpa** [osmc/osmc#666]
Hello

Problem:
I still could browse through my Samba share but when I tried to play ANY file I had a sad face screen.

Solution:
I had problems because of updating my server.
It changes a lot so I needed a few tries to detect my issue.
In the end it was the mysql configuration, after disabling mysql I could play files again.

Please display an error if mysql is the problem, don't stop playing files when mysql is not connecting.
I hope this bug is reproducable without logs or such.

Jochen

**Comment by samnazarko** [comment]
Please start a support request with logs. This is for confirmed bugs only.
