### ISSUE TITLE
Sad face when playing ANY file because MySQL Database is not connected but configured (with Logs)

### ISSUE THREAD

**Issue by jochenpa** [osmc/osmc#667]
Hello

Problem:
I still could browse through my Samba share but when I tried to play ANY file I had a sad face screen.

Solution:
I had problems after updating my server.
It changes a lot so I needed a few tries to detect my issue.
In the end it was the mysql configuration, after disabling mysql on OSMC I could play files again.

Please display an error if mysql is the problem, don't stop playing files when mysql is not connecting.

Logs:
First I stopped my MySQL-Server.
Then I enabled debugging on OSMC and restarted OSMC.
Then I tried playing 2 Files from my Samba Storage.
Both times I did see a sad face immediately when playback should start.
Here the Log:
https://paste.osmc.tv/hukogejumo

Then I started my MySQL-Server.
I restarted OSMC because it didn't work without restart.
After restart I tried to play the same File from my Samba Storage
This time it works fine, I stopped the playback after a few seconds.
I took another Log:
https://paste.osmc.tv/miwibipuxa

If anything is missing again, sorry.
Please state what is missing, I will submit further details very fast ...

Jochen

**Comment by samnazarko** [comment]
This is for confirmed bugs only.
