### ISSUE TITLE
New mirror in Singapore

### ISSUE THREAD

**Issue by karibuTW** [osmc/osmc#688]
Hello
I'm Kari, the admin of de.freedif.org (Germany mirror) and mirror.freedif.org (Singapore)

I'd like to support the project with my Singaporean mirror, on 1 GBPS connection.

Hope you are keen with new mirrors:
https://mirror.freedif.org/osmc/
Refreshing every 4hrs.

My contact (karibu @ freedif.org)

Let me know if you need more information

Thank you

**Comment by samnazarko** [comment]
Hi Kari

I will send you an email shortly.
Do you have an rsync endpoint so we can verify mirror integrity?

Thanks

Sam

**Comment by karibuTW** [comment]
Hello,
Yes
https://mirror.freedif.org/osmc/
rsync://mirror.freedif.org/osmc/ <https://mirror.freedif.org/osmc/>

Let me know if you need more information
Thank you
Kari
-- 
Sent with Tutanota



Apr 20, 2022, 03:33 by ***@***.***:

**Comment by karibuTW** [comment]
Hello @samnazarko  you need something else?

Thank you

**Comment by samnazarko** [comment]
Sorry -- it's been very busy here. I'll send you an email over the weekend and add you in to the mirror rotation system.

**Comment by samnazarko** [comment]
Thanks for your patience. I've now simplified this process to make it easier to onboard newer mirrors. 

Please read the instructions here: https://osmc.tv/wiki/development/mirroring-osmc/

**Comment by samnazarko** [comment]
Your mirror has been added to the rotation.
