### ISSUE TITLE
Please, enable "CONFIG_ZRAM_WRITEBACK" and "CONFIG_ZRAM_MEMORY_TRACKING" when compiling the kernel

### ISSUE THREAD

**Issue by jcea** [osmc/osmc#700]
I am a heavy user of ZRAM in Raspberries PI with 1GB of RAM. This is a kernel module usually used as swap space in order to avoid wearing out the microSD. This module is currently available in OSMC.

Would be nice to be able to use a backing store for idle memory (for example, in a sacrificial USB pendrive). In order to get that functionality, I would need ZRAM to be compiled with "CONFIG_ZRAM_MEMORY_TRACKING".

In order to be able to get statistics and other metadata, would be nice to have also "CONFIG_ZRAM_MEMORY_TRACKING".

I don't think those extras create a significantly bigger module binary, so cost would be minimal.

Thanks.

**Comment by samnazarko** [comment]
Which models of Pi are you using that only have 1GB?

Sam

On 31 May 2022, at 23:43, Jesús Cea ***@***.***> wrote:

﻿

I am a heavy user of ZRAM in Raspberries PI with 1GB of RAM. This is a kernel module usually used as swap space in order to avoid wearing out the microSD. This module is currently available in OSMC.

Would be nice to be able to use a backing store for idle memory (for example, in a sacrificial USB pendrive). In order to get that functionality, I would need ZRAM to be compiled with "CONFIG_ZRAM_MEMORY_TRACKING".

In order to be able to get statistics and other metadata, would be nice to have also "CONFIG_ZRAM_MEMORY_TRACKING".

I don't think those extras create a significantly bigger module binary, so cost would be minimal.

Thanks.

**Comment by jcea** [comment]
Raspberry PI 3B and 3B+

**Comment by samnazarko** [comment]
Hi @jcea -- this isn't forgotten, but I don't think I'll be able to do anything here for a couple of weeks.

**Comment by samnazarko** [comment]
I did have a post drafted earlier with a few questions and cannot remember them all from the top of my head. But what I was curious about:

1. What kind of performance penalty are you getting from using ZRAM?
2. Have you experienced microSD wear out before and found it better using this functionality?
3. How are you configuring ZRAM on your device to optimise conditions (which directories; size etc). 

I ask because we have much more RAM on Pi 4 and I wonder if it makes sense there. Obviously storage is more volatile and we need to consider such a tradeoff

Cheers

Sam

**Comment by jcea** [comment]
"A couple of weeks" delivery would be fine to me, @samnazarko. Take it easy.

Thanks

**Comment by jcea** [comment]
I do use ZRAM as "in ram compressed swap".

>     1. What kind of performance penalty are you getting from using ZRAM?

SWAP trashing. Sending swap to compressed RAM eats RAM. Eventually, you don't have enough RAM.

>     2. Have you experienced microSD wear out before and found it better using this functionality?

Yes, swapping to microSD was killing the card pretty soon. Moving to ZRAM as SWAP helped me to survive an extra year, but the requirements keep growing so swaping to compressed ram alone it not enough.

Compiling ZRAM with the extra functionalities I asked, it can swapout paged unused for a long term to the microSD (or a "sacrificial" USB pendrive). Moreover, ZRAM with those configs allows to configure a "daily limit" of backend writing so you can, for instance, limit the writes to 1 GB/day, for instance. Pretty interesting.

I use ZRAM as swap in my laptop (to increase NVME lifetime and performance) and after A MONTH of regular use, about 30% of the swap used has not been touched at all in the last WEEK. That is, I could move 30% of my in RAM SWAP to the nvme and have 0% penalty in speed and do not wear the nvme at all.

Enabling ZRAM stats in the module allows me to collect those stats for my raspberry. The option is "CONFIG_ZRAM_MEMORY_TRACKING".

Enabling ZRAM backend dumping with "CONFIG_ZRAM_WRITEBACK" I could dump to the microSD (or a "sacrifical" pendrive) only data not touched in the last, lets say, 24 hours., and even limiting the daily write quota to avoid wearing.

>     3. How are you configuring ZRAM on your device to optimise conditions (which directories; size etc).

I use ZRAM as SWAP. Currently:

root@osmcpi:~# free; zramctl; swapon
              total        used        free      shared  buff/cache   available
Mem:         943444      723368      138540         776       81536      177772
Swap:       1048572      883616      164956

NAME       ALGORITHM DISKSIZE   DATA  COMPR  TOTAL STREAMS MOUNTPOINT
/dev/zram0 zstd            1G 862.2M 360.3M 378.6M       4 [SWAP]

NAME       TYPE       SIZE   USED PRIO
/dev/zram0 partition 1024M 862.9M   -2

As you can see I am using ZRAM as swap, that swap is pretty full already and the free memory is running low. In fact the state snapshot I just pasted is "optimistic", the device is usually more overloaded yet.

> I ask because we have much more RAM on Pi 4 and I wonder if it makes sense there. Obviously storage is more volatile and we need to consider such a tradeoff

I manage a small fleet of raspberries for family members & friends. Moving to PI4 is not going to happen for already deployed devices, even more considering that it requires a new full install and most people are not capable enough to write a microSD in their laptops, at all. Tried and burned by this a few times already.

Given that ZRAM stats and backend writeback are just configuration options and runtime performance/memory use penalty is tiny, I think that request is simple to provide, lowcost and... useful to whoever need it and just free to whoever doesn't use it.

**Comment by jcea** [comment]
Just in case, you want to play with this:

```
#!/bin/sh

/sbin/modprobe zram

echo zstd > /sys/block/zram0/comp_algorithm
echo 1G > /sys/block/zram0/disksize

/sbin/mkswap /dev/zram0
/sbin/swapon /dev/zram0
```

**Comment by samnazarko** [comment]
Thanks for your patience.

OK -- so you're swapping to SD/USB outside of a normal workload. I asked because we wouldn't swap by default on a device with your amount of RAM and wondered if you were using in memory ZRAM compression in the past. 

I'll get this in for you. My query is because I'd like to reduce wear (perpetual writing of kodi.log) on devices, and I'm pondering a way to do that. I think it's fine if it's ephemeral in most conditions and we could toggle it to being persistent if a user has an issue that needs troubleshooting.

**Comment by jcea** [comment]
> I ask because we have much more RAM on Pi 4 and I wonder if it makes sense there. Obviously storage is more volatile and we need to consider such a tradeoff

The good thing about SWAP on ZRAM is that an empty swap doesn't consume RAM at all. For instance, in my personal Pi4:

```
jcea@jcea:~$ ssh osmcpi4
Linux osmc 5.10.78-5-osmc #1 SMP PREEMPT Mon Feb 28 01:18:12 UTC 2022 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jun 14 00:25:33 2022 from 10.8.0.244
root@osmc:~# free ; zramctl ; swapon
              total        used        free      shared  buff/cache   available
Mem:        1893276      585288      522472       31144      785516     1174848
Swap:       1048572        5632     1042940
NAME       ALGORITHM DISKSIZE  DATA  COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram0 zstd           1G  4.9M 246.1K  764K       4 [SWAP]
NAME       TYPE       SIZE USED PRIO
/dev/zram0 partition 1024M 5.5M   -2
```
Here I use also ZRAM with a 1GB size for SWAP, but the machine is almost not using that swap and it is taking no memory.

So:

1. Having zram available doesn't take any resource until you enable it.
2. If you enable it, it use resources only when resources are required. You are not taking away 1GB of ram just because you created a 1GB ZRAM.

Details: https://www.kernel.org/doc/Documentation/blockdev/zram.txt

**Comment by jcea** [comment]
> Thanks for your patience.

Thanks for investing your valuable time on this!.

> OK -- so you're swapping to SD/USB outside of a normal workload. I asked because we wouldn't swap by default on a device with your amount of RAM and wondered if you were using in memory ZRAM compression in the past.

I am swapping because my library is huge and Kodi in memory hungry in that situation (requesting ALL films data in the database several times in order to display the estuary home page, for instance), and I run other services in those raspberries like NAS, network backups, and even Tor relays. Some of my family member even run IoT hubs/database/graphers on those PIs.

ZRAM swaping got me some air, but this thing is growing and I need a "swap for the swap". ZRAM provides that if compiled with the requested options.

> I'll get this in for you. My query is because I'd like to reduce wear (perpetual writing of kodi.log) on devices, and I'm pondering a way to do that. I think it's fine if it's ephemeral in most conditions and we could toggle it to being persistent if a user has an issue that needs troubleshooting.

You can have several ZRAM devices. One, for instance, formatted as a 1GB ext4 disk mounted in "temp_ephemeral". When kodi process finish for whatever reason, it could copy the content of that "ramdisk" to "temp", for analysis. Instead of tiny frequent writes, you could have only a huge write from time to time. 1GB of ZRAM doesn't take 1GB of ram, only enough for the data you actually store there.

There are other issues related to microsd wearing:

Rewriting the database every 20 operations was something killing my microSD cards also. This is Kodi suckness. I have code like this running in my systems to avoid it

```
db.execute('update version set '
                               'iCompressCount = -1000000000 '
                               'where idVersion = 119')
```

My database is ~300MB in size. Before this, the (pointless) database compaction was killing my microSD after a few months and kodi was unresponsible for a solid FIVE minutes from (frequent) time to time.

For me, a database compaction every other year, when a new Kodi release arrives, is enough. More than enough, in fact.

But that is another issue to argue about :-)

**Comment by samnazarko** [comment]
It’s late here and the next couple of weeks are going to be busy here. I appreciate the detailed response and will action things soon. 

Cheers

Sam

**Comment by jcea** [comment]
Ping...

**Comment by samnazarko** [comment]
Pong. This is still on my to-do list.

On 12 Jul 2022, at 06:12, Jesús Cea ***@***.***> wrote:

﻿

Ping...

**Comment by samnazarko** [comment]
I should be able to get this in for the end of the week

Thanks for your patience

Sam

**Comment by samnazarko** [comment]
Hi

Took a bit longer than expected but should now be part of the Debian Bullseye testing.

See: https://discourse.osmc.tv/t/testing-debian-11-bullseye/93054

Thanks for your patience.

**Comment by jcea** [comment]
In production for the last couple of weeks. Thanks a lot, @samnazarko

**Comment by samnazarko** [comment]
Thanks for confirming.
