### ISSUE TITLE
SPI not working when enabled through osmc

### ISSUE THREAD

**Issue by DerDorfbewohner** [osmc/osmc#712]
SPI in not working when enabled through osmc.

Possible fix:
When enabled through osmc `dtparam=spi=on` is added to the end of `/boot/config.txt`.
If you set it manually under the `[all]` category it works fine!
Final config:
[config.txt](https://github.com/osmc/osmc/files/9484711/config.txt)

**Comment by samnazarko** [comment]
It should be added to config-user.txt. Can you confirm which version of OSMC you are on and provide logs?

**Comment by DerDorfbewohner** [comment]
Im on version 2022.03-1.
[Logs](https://paste.osmc.tv/bokovokoci)
In config-user.txt is `dtoverlay=spi-bcm2835-overlay` (isnt working).
But when I add `dtparam=spi=on` to the file it works.
