### ISSUE TITLE
Fails to boot on rpi4, using USB boot

### ISSUE THREAD

**Issue by orowith2os** [osmc/osmc#715]
Not much to describe in the way of reproducing;

1. Flash an extracted .img.gz file for the Raspberry Pi 4 from the downloads page to a USB drive
2. Plug drive into the Pi
3. "failed to mount bootfs" on a page with the OSMC logo

I get no issues if I do the same process, but to an SD card

**Comment by samnazarko** [comment]
At this time, you need to use an SD card to boot OSMC.

**Comment by orowith2os** [comment]
Is there any reason why this is? I'd really like to use a USB drive, since all of my SD cards are *really* small.

**Comment by samnazarko** [comment]
You can use an SD card to boot from (you only need a 512MB card) and everything else can sit on USB.

https://github.com/osmc/osmc/pull/702 will facilitate changes, but it's a large and invasive change, so we will introduce it slowly and thoroughly.

**Comment by samnazarko** [comment]
I'm open to PRs to speed up the process.
