### ISSUE TITLE
Feature request: Replacing wpa_supplicant with iwd

### ISSUE THREAD

**Issue by cmonty14** [osmc/osmc#716]
Hello,

this is kind of a feature request:
Replacing wpa_supplicant with [iwd](https://git.kernel.org/pub/scm/network/wireless/iwd.git/).

Advantage of using iwd instead of wpa_supplicant is, that the ping times seem to be much more consistent and the connection seems to be more reliable.

THX

**Comment by samnazarko** [comment]
ConnMan does support ```iwd``` so an integration should be possible?

Can you compare your ping times with wpa_supplicant vs iwd as well as outline the hardware that you are testing on?

**Comment by cmonty14** [comment]
I would test on this hardware: Vero 4K+

Would it be sufficient to run ping test with [mtr](https://www.bitwizard.nl/mtr/)?

There's one issue for using iwd, though.
According to [Arch Linux Wiki](https://wiki.archlinux.org/title/ConnMan#Using_iwd_instead_of_wpa_supplicant) "[...] ConnMan can use iwd to connect to wireless networks. The package which is available in community already supports using iwd for connecting to wireless networks. As connman will start wpa_supplicant when it finds it, it is recommended to uninstall wpa_supplicant."

But wpa_supplicant has several dependencies in OSMC that prevents me from uninstalling it.
```
# apt remove wpasupplicant
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  armv7-bluez-osmc armv7-bluezalsa-osmc armv7-connman-osmc cifs-utils curl iproute2 libbluetooth3 libbpf0 libfdk-aac2 libnl-route-3-200 libnss-myhostname
  libpcsclite1 libpkcs11-helper1 libsbc1 net-tools openvpn wget
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  armv7-network-osmc vero3-device-osmc wpasupplicant
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 2485 kB disk space will be freed.

```

**Comment by cmonty14** [comment]
Unfortunately I cannot connect to any SSID in my network with iwd, means I get this error:
```
# iwctl --passphrase "<password>" station wlan0 connect <ssid>
Operation failed
```

**Comment by samnazarko** [comment]
I’m a bit confused here — are you saying you haven’t tested this on OSMC?

I thought that you had tested things and reported better latency.

**Comment by samnazarko** [comment]
>But wpa_supplicant has several dependencies in OSMC that prevents me from uninstalling it.

You can use an equivs package for testing.

**Comment by cmonty14** [comment]
> > But wpa_supplicant has several dependencies in OSMC that prevents me from uninstalling it.
> 
> You can use an equivs package for testing.

It's impossible to test iwd with OSMC because connman is not working.

**Comment by samnazarko** [comment]
This tracker is for confirmed bugs — you’re in the wrong place.
