### ISSUE TITLE
Composite output still broken

### ISSUE THREAD

**Issue by 03stevensmi** [osmc/osmc#724]
As many have stated here:
https://discourse.osmc.tv/t/rpi3a-new-install-boots-to-sad-face/92278
and Here:
https://discourse.osmc.tv/t/composite-video-broken-after-update-on-rpi-3b/93275
and here:
https://discourse.osmc.tv/t/trying-to-boot-pi-4-via-composite-stuck-on-splash/91311
here:
https://discourse.osmc.tv/t/black-screen-on-composite-output-after-update/92358
here:
https://discourse.osmc.tv/t/rpi2-composite-failure/90011/15
also here:
https://discourse.osmc.tv/t/black-after-splash-composite-video-9-kv-9pt50-tv/90309/4
AND EVEN HERE:
https://github.com/osmc/osmc/issues/687

THE FREKIN COMPOSITE OUTPUT DOES NOT WORK AND HASNT SINCE 2020!!
No excuses for every single mention of this issue (INCLUDING MINE I KNOW IT) GETTING COMPLETELY IGNORED
From the devs every time this comes up anywhere.

Please for the love of god can you if not fix, then just frekin do, something on your keyboard and TYPE A RESPONSE!
Why is this not been fixed, can it be fixed, and is there anything you could (IF ITS NOT TO GOD DAM TROUBLE TO ASK) recommend We can do to that could help get this working again?

This is a bug,
And no I'm not going to,be number 83 out of the 100 posts on the osmc forums to,get ignored in this subject
Wichnis another reason why I am posting this here.

You all probably know,this,
But for,those who don't,
When not,using the HDMI on the raspberry pi as the video output, you have the option to use analog composite video,output after change to the config,txt.
After a 2020 update that doesn't f***ING work with the rapsberry pi 4,
This feature has been broken resulting in it displaying the splash screen... Then nothing but a Black screen.
You can here kodi working when using the remote, so its working with sound but that's it!!

So,
Are we going to,get a response here?
Or,is this just going to be yet another god dam pissing in the wind being completely ignored by the devs!

80% granite this will be Yet again another person brining this up just to,get a hand in my face!

Anything?

**Comment by samnazarko** [comment]
You need to use an older version of OSMC. We have made this very clear.

We support Raspberry Pi for free on a best effort basis. When Pi 4 was announced, Raspberry Pi changed the video stack, not us. We do not work for Raspberry Pi and we support the platform.

Don’t moan like a bitch, do some research and have a good Christmas.

On 23 Dec 2022, at 00:27, 03stevensmi ***@***.***> wrote:

﻿

As many have stated here:
https://discourse.osmc.tv/t/rpi3a-new-install-boots-to-sad-face/92278
and Here:
https://discourse.osmc.tv/t/composite-video-broken-after-update-on-rpi-3b/93275
and here:
https://discourse.osmc.tv/t/trying-to-boot-pi-4-via-composite-stuck-on-splash/91311
here:
https://discourse.osmc.tv/t/black-screen-on-composite-output-after-update/92358
here:
https://discourse.osmc.tv/t/rpi2-composite-failure/90011/15
also here:
https://discourse.osmc.tv/t/black-after-splash-composite-video-9-kv-9pt50-tv/90309/4
AND EVEN HERE:
#687<https://github.com/osmc/osmc/issues/687>

THE FREKIN COMPOSITE OUTPUT DOES NOT WORK AND HASNT SINCE 2020!!
No excuses for every single mention of this issue (INCLUDING MINE I KNOW IT) GETTING COMPLETELY IGNORED
From the devs every time this comes up anywhere.

Please for the love of god can you if not fix, then just frekin do, something on your keyboard and TYPE A RESPONSE!
Why is this not been fixed, can it be fixed, and is there anything you could (IF ITS NOT TO GOD DAM TROUBLE TO ASK) recommend We can do to that could help get this working again?

This is a bug,
And no I'm not going to,be number 83 out of the 100 posts on the osmc forums to,get ignored in this subject
Wichnis another reason why I am posting this here.

You all probably know,this,
But for,those who don't,
When not,using the HDMI on the raspberry pi as the video output, you have the option to use analog composite video,output after change to the config,txt.
After a 2020 update that doesn't f***ING work with the rapsberry pi 4,
This feature has been broken resulting in it displaying the splash screen... Then nothing but a Black screen.
You can here kodi working when using the remote, so its working with sound but that's it!!

So,
Are we going to,get a response here?
Or,is this just going to be yet another god dam pissing in the wind being completely ignored by the devs!

80% granite this will be Yet again another person brining this up just to,get a hand in my face!

Anything?

**Comment by 03stevensmi** [comment]
That basically rased more questions as well as answered them.
I already know about the changes,
I knew all those things.
But what I can't get my head around is the rpi4 composite works great on other distros and even 
Librelec.

So what exactly makes osmc different from the rest.
If incould just useban older version,
I would have.
But can't due to the rpi4 not having a 11.2020 build.

**Comment by samnazarko** [comment]
This was never supported on Pi 4 and we never promised or said that it was.

You have to use an older version of OSMC which supports the old video stack on an older Pi. Pi 4 support did not come out for OSMC until 2021, so this is not a regression or feature pull.

Other distributions / Kodi will be the same. This is not unique to OSMC.

**Comment by samnazarko** [comment]
>But what I can't get my head around is the rpi4 composite works great on other distros and even
Librelec.

So use LibreELEC. It’s a great distribution.
But we aren’t satisfied with the performance currently. If we are in the future, we will reintroduce support.

**Comment by 03stevensmi** [comment]
Wait wait wait wait....
Hold on!/are we talking about the same thing here?
I'm referring to video output via composite.
The other distros don't have the same issue.
I'm using them now. Could you please explain what your referring to when you mention 
About the composite issue with the rpi?

All you do is add this:
enable_tvout=1
to config.txt,
Only for rpi4

**Comment by samnazarko** [comment]
If that’s all you need to add for it to work then I’m glad that this works for you, but it’s not something we intend to enable by default as the setting is very easy to adjust.

>Could you please explain what your referring to when you mention
About the composite issue with the rpi?

Likewise.

**Comment by 03stevensmi** [comment]
Also can't use librelec due to having no apt-get function.

And yes the function on osmc is superiour.
Wich is why I can't get my head around this.

**Comment by 03stevensmi** [comment]
> If that’s all you need to add for it to work then I’m glad that this works for you, but it’s not something we intend to enable by default as the setting is very easy to adjust.
> 
> > Could you please explain what your referring to when you mention
> > About the composite issue with the rpi?
> 
> Likewise.

Ok so I don't need it to be enabled as a feature.
Thats not the issue

The issue is after I add that little bit of code, the distros work with composite
Expect osmc.

Does that make sense?
So like there no difference.
I get the splash screen displayed, but them no picture.
Just sound.

It goes to composite the cuts off back to HDMI.

**Comment by 03stevensmi** [comment]
Anything? So thats it?
Well,there you go then.

Thats another one ended without a result.

I'm out.
Hope you can get this working in the near future,
Then i can hopefully & fully enjoy all the hard work that goes into osmc.
Until,then, guess I'm using raspberry os.
Merry Christmas.

**Comment by samnazarko** [comment]
I am responding..

On 23 Dec 2022, at 01:05, 03stevensmi ***@***.***> wrote:

﻿

Anything? So thats it?
Well,there you go then.

Thats another one ended without a result.

I'm out.
Hope you can get this working in the near future,
Then i can hopefully & fully enjoy all the hard work that goes into osmc.
Until,then, guess I'm using raspberry os.
Merry Christmas.

**Comment by samnazarko** [comment]
It's 1AM here on 23rd December, I think expecting real-time support and responses is unreasonable and somewhat entitled. Obviously we want to make OSMC on Pi the best experience possible. 

You clearly haven't read, as this was covered before. 

I am aware that if you enable composite support, you'll only get a black screen. Changes to give you the Kodi UI were already made available in https://github.com/osmc/osmc/commit/63a5945724388886dc37a78c83d3c6ef0a3bdb8e. 

I don't have sufficient hardware to properly evaluate composite output on Raspberry Pi and don't intend to acquire such hardware. With the next update, composite video output will work when making config.txt changes, but it will not necessarily work as you want. When I did do some testing, I experienced audio drop-outs and other issues. This is why we won't make it configurable via My OSMC until/if it becomes mature. You will likely also experience other performance issues, hence the fact that this was low priority for some time. 

You can monitor the forums or blog for when the next update is released. It will be in the staging repository before the end of the year.

**Comment by samnazarko** [comment]
Take it easy

________________________________

**Comment by 03stevensmi** [comment]
You too

**Comment by harryberlin** [comment]
try this:
add to cmdline.txt:
video=Composite-1:720x576@50ie

add to config.txt:
enable_tvout=1

**Comment by samnazarko** [comment]
The original poster can try the latest changes introduced last week if inclined. 

I'd appreciate it if you could test this and provide feedback before we potentially release this as an update to other users. To test this update:

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Run the following command to add the staging repository:
```echo 'deb http://apt.osmc.tv bullseye-devel main' | sudo tee /etc/apt/sources.list.d/osmc-devel.list```
3. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
4. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you remove ```/etc/apt/sources.list.d/osmc-devel.list``` after updating. 

This will deactivate the staging repository. You can do so with the following command:
```sudo rm /etc/apt/sources.list.d/osmc-devel.list```. 

Please note that we will automatically disable this update channel after 14 days on your device in case you forget to do so to ensure that your system reverts to the stable update channel.

**Comment by 03stevensmi** [comment]
> The original poster can try the latest changes introduced last week if inclined.
> 
> I'd appreciate it if you could test this and provide feedback before we potentially release this as an update to other users. To test this update:
> 
> 1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
> 2. Run the following command to add the staging repository:
>    `echo 'deb http://apt.osmc.tv bullseye-devel main' | sudo tee /etc/apt/sources.list.d/osmc-devel.list`
> 3. Run the following commands to update: `sudo apt-get update && sudo apt-get dist-upgrade && reboot`
> 4. Your system should have have received the update.
> 
> Please see if the issue is resolved.
> 
> I also recommend you remove `/etc/apt/sources.list.d/osmc-devel.list` after updating.
> 
> This will deactivate the staging repository. You can do so with the following command: `sudo rm /etc/apt/sources.list.d/osmc-devel.list`.
> 
> Please note that we will automatically disable this update channel after 14 days on your device in case you forget to do so to ensure that your system reverts to the stable update channel.

Thanks mate, will give it a shot befor this Friday or Saturday. Hopefully beforehand.
Will let you know instantly
Really do appreciate it,
Have a Good Christmas mate.
;)

**Comment by harryberlin** [comment]
I was testing this on Pi3 B+.
USB stopped working.

**Comment by samnazarko** [comment]
Only when enabling composite?

On 26 Dec 2022, at 16:11, harryberlin ***@***.***> wrote:

﻿

I was testing this on Pi3 B+.
USB stopped working.

**Comment by harryberlin** [comment]
only upgrade without additional settings/configs.
i will do some further tests.

**Comment by harryberlin** [comment]
ok, short story
Raspberry Pi 3 B+

Setup new image "OSMC_TGT_rbp2_20221101.img.gz"

after successful install i added these to the txt files
cmdline.txt
video=Composite-1:720x576@50ie
or
video=Composite-1:720x480@60ie

config.txt
dtoverlay=vc4-kms-v3d,composite=1 

got an issue by this entry
after osmc boot logo swapped back back to PAL. commenting out solved the issue.


so i started the devil upgrade

after Upgrade USB is not working anymore. No HID Keyboard, no USB Flash Drive.

after upgrade needed to add to txt files 
cmdline.txt
video=Composite-1:720x576@50ie
or
video=Composite-1:720x480@60ie

config.txt 
dtoverlay=vc4-kms-v3d,composite=1 

composite signal is ok. did not swapped back

https://paste.osmc.tv/mikahokaqu

**Comment by samnazarko** [comment]
Can you please confirm if USB works after installing the latest update before making the composite changes?



On 27 Dec 2022, at 17:31, harryberlin ***@***.***> wrote:

﻿

ok, short story
Raspberry Pi 3 B+

Setup new image "OSMC_TGT_rbp2_20221101.img.gz"

after successful install i added these to the txt files
cmdline.txt
***@***.***
or
***@***.***

config.txt
dtoverlay=vc4-kms-v3d,composite=1

got an issue by this entry
after osmc boot logo swapped back back to PAL. commenting out solved the issue.

so i started the devil upgrade

after Upgrade USB is not working anymore. No HID Keyboard, no USB Flash Drive.

after upgrade needed to add to txt files
cmdline.txt
***@***.***
or
***@***.***

config.txt
dtoverlay=vc4-kms-v3d,composite=1

composite signal is ok. did not swapped back

https://paste.osmc.tv/mikahokaqu

**Comment by harryberlin** [comment]
do you mean the usual update/upgrade without devel?

**Comment by samnazarko** [comment]
No, without composite enabled.

On 27 Dec 2022, at 20:13, harryberlin ***@***.***> wrote:

﻿

do you mean the usual update/upgrade without devel?

**Comment by harryberlin** [comment]
yes, USB issue exist directly after upgrade to devel

**Comment by samnazarko** [comment]
Do you have another RBP you can test on?
We could try download the boot loader to rule that out as an issue.

On 27 Dec 2022, at 20:23, harryberlin ***@***.***> wrote:

﻿

yes, USB issue exist directly after upgrade to devel

**Comment by harryberlin** [comment]
currently i'm testing pi4.
may i can test an other pi3 later.

**Comment by samnazarko** [comment]
try sudo apt-get install rbp-bootloader-osmc=4.1.0-6 (this will restore RPi firmware) to the  previous version and may help.

**Comment by samnazarko** [comment]
USB works here with an OSMC remote connected. Have you tried other ports?

What devices do you have connected that don’t work?

I also checked with another team member and his FLIRC works after upgrading

On 27 Dec 2022, at 20:31, harryberlin ***@***.***> wrote:

﻿

currently i'm testing pi4.
may i can test an other pi3 later.

**Comment by harryberlin** [comment]
for Pi4:
add this to
config.txt
`,composite=1` to `dtoverlay=vc4-kms-v3d,cma-512,composite=1`
`enable_tvout=1`

cmdline.txt
` video=Composite-1:720x480@60ie` for NTSC 
or 
`video=Composite-1:720x576@50ie` for PAL

have seen kodi has an issue by audio sink:
https://paste.osmc.tv/ubiqusudan

in case of Pi3 and usb problem:

all usb ports
my usb device is an wireless HID Keyboard. the other one is a micro sd card reader.
looks like the usb port don't power up.

will try an other Pi3

**Comment by 03stevensmi** [comment]
I have just tested it, and it works great for me.
Also strangely I have no issues with USB or composite pal at all.

Tested with a USB keyboard and memory stick with composite.
Works amazingly.
Thank you.

Rpi4 4gb.
:)

**Comment by harryberlin** [comment]
same issue with the other pi3.
downgrade to rbp-bootloader-osmc=4.1.0-6 did not solve the problem.

Audio Sink issue also

https://paste.osmc.tv/godorowete

**Comment by samnazarko** [comment]
@harryberlin I'd suggest starting a forum post with your issues so I can also point this towards Pi guys.

Sam

**Comment by harryberlin** [comment]
check this thread:
https://discourse.osmc.tv/t/testing-raspberry-pi-3-usb-stopped-working-after-composite-devel-upgrade/94383

**Comment by samnazarko** [comment]
USB issues should be fixed as per that thread.
