### ISSUE TITLE
OSMC (wifi) is completely broken out-of-the-box on retail Pi 4 ?!

### ISSUE THREAD

**Issue by kyle-wendling** [osmc/osmc#728]
repo:
Using latest installer off [OSMC](https://osmc.tv/download/) osmc-installer.dmg --> entered wifi info --> flashed SD --> retail Pi 4 --> installed --> open OSMC --> NO NETWORK

detail: attempt to fix network
OSMC --> 
Programs --> 
select 'My OSMC' in menu (wff #1) --> 
'network icon that's actually the sharing icon in every other app' (using icons instead of text labels for UI now... nice #wtf #2) --> 
'Wireless' -->  select any WIFI network --> 
'Do you want to connect' --> 'yes' (why does UI show a modal, why is 'no' the default, wtf #3) --> 
"OSMC Network Unhandled Exception Caught (see logs for details)" for every WIFI network selected (2.4, 5ghz, every flavor of auth, doesn't matter, same error)-->
pi is now OSMC brick.

No way to 'see logs for details,' no option to load CL? WTF, OSMC can't be this bad? Is bog-standard OSMC, on bog-standard Pi4 completely broken with no straightforward way to even diagnose the issue?

**Comment by samnazarko** [comment]
WiFi works on Pi 4 out of the box. If it didn’t, I think we’d have a lot of reports.

This sounds like a hardware failure. I would try and see if WiFi works under RPI-OS.

Logs can be saved to an SD card or you can attach an Ethernet cable to upload them.

Please note that this issue tracker is for confirmed issues. You should start a support request on the forums instead.

**Comment by varaki** [comment]
#732 Should fix this exact same issue.
