### ISSUE TITLE
sad face when i try to play video

### ISSUE THREAD

**Issue by matlock1980** [osmc/osmc#729]
Hi, When trying to play any video I get a sad face. Either on the external drive or from the youtube add on.
attached log https://paste.osmc.tv/cowozofapo It started out sporadically but now it's for any video I try to play including videos I had already watched yesterday.
Thank you so much

**Comment by samnazarko** [comment]
This issue tracker is for confirmed bugs.
See https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request
