### ISSUE TITLE
OSMC (June update) skin 'Games' category bug

### ISSUE THREAD

**Issue by kurac338** [osmc/osmc#740]
Since OSMC June update (Kodi v20 and later) there seems to be a bug with the OSMC skin.
The issue impacts the **Games** category on the _main screen_. When hovering over the category, it properly displays the installed addons, but when you enter the category (to see the list of installed addons), only the "Add games..." option in displayed.

At the moment I have only one addon, [moonlight-qt](https://github.com/veldenb/plugin.program.moonlight-qt/), and I've checked with the developer to reproduce the issue. We've isolated it to the OSMC skin. When switching to Estuary, everything is displayed properly. Related issue report: https://github.com/veldenb/plugin.program.moonlight-qt/issues/34

**Comment by samnazarko** [comment]
Is this still an issue with 2023.07-1?

**Comment by kurac338** [comment]
Yes.

**Comment by samnazarko** [comment]
Thanks for confirming. One for our skinner to check out when he has a chance.

**Comment by Ch1llb0** [comment]
I can't really see any difference between Estuary's and the OSMC Skin's behaviour:

Estuary's _Games_ home menu entry and the corresponding sub menu of that window:

![screenshot00000](https://github.com/osmc/osmc/assets/36623079/428e4dff-e293-423b-8002-718c6b2aa01f)

![screenshot00003](https://github.com/osmc/osmc/assets/36623079/26f9f901-c8b3-4a58-aea2-3d400bb0f0e7)

The OSMC Skin's _Games_ home menu entry and the corresponding sub menu of that window:

![screenshot00001](https://github.com/osmc/osmc/assets/36623079/4f44e185-6903-4df1-8ca8-77e833757d23)

![screenshot00005](https://github.com/osmc/osmc/assets/36623079/40c3e217-9608-4bb6-abd6-5b35bbe84f07)

This home menu entry has never been meant to point to game _addons_, but games added to Kodi via the _Add games..._ option. So, it all looks fine to me.

Am I misunderstanding the issue?

**Comment by kurac338** [comment]
Thanks for the responses.
I am attaching the images now, to give you a better look at what I mean.
The main menu behaves as expected. It shows that the Moonlight addon is installed and available.
![20230730_105037](https://github.com/osmc/osmc/assets/36849777/26576cf3-946a-4f96-b413-737494d980c0)
But when you enter that menu category, this happens...
![20230730_105054](https://github.com/osmc/osmc/assets/36849777/8b1cddd8-960b-4db0-935e-be8431d31e32)

As you can see I don't have anything except the "Add games.." option under the "Games" main menu category.
And even stranger is that this behavior also happens under the Estuary skin, while previously it behaved correctly when switching skins.

I am running on RPI 4, and keep my system up-to-date (using the latest addon version and OSMC July update).

**Comment by Ch1llb0** [comment]
That's to be expected, as I tried to explain: The main menu entry doesn't open the _Games addon_ section, but the _Games window_. Those things are two different. The home menu widget is only a peak into the _Games add-on_ section and not meant to be representative of (or redundant to) the contents of the home menu entry itself.

The _Games window_ shows locations that contain game ROM files or folders that'll be executed using game emulation addons (thus _Add games..._ works in exactly the same way as adding locations to the video or music library where you also find entries like _Add videos..._, etc.). Game addons are something different and thus expected to be found in a different location (same as video addons, etc.).

**Comment by kurac338** [comment]
Ok, I did not know that. Previous behavior (Kodi v19) was to list both
standalone games and game emulators under the same view, so I thought
something was bugged in newer releases.
Thanks for explaining. Cheers.

**Comment by Ch1llb0** [comment]
You can change where the home menu entry points or even add new entries using our skin's customization options though: https://discourse.osmc.tv/t/howto-customize-the-osmc-skin-main-menu/86030
