### ISSUE TITLE
Can't disable dns proxy via connman.prefs

### ISSUE THREAD

**Issue by rizerzero** [osmc/osmc#746]
Hi, 
I have installed Debian 11 with XFCE desktop and I wanted to add a DNS server, but I found out that connman was using port 53, I found online that there was a configuration file in /etc/connman.prefs to disable it, but it seems like it's not used anymore by the service, is there any reason why this was deleted and also how can I disable the DNS proxy, so I can use port 53 for my dns server. 

Here is the service file I have 

_* I also found out that the old way of doing this was to edit the service file to add an argument to the ExecStart command, which works, but I'm not sure it's the best way to configure a service._  

Thank you.
```
[Unit]
Description=Connection service
DefaultDependencies=false
Conflicts=shutdown.target
RequiresMountsFor=/var/lib/connman
After=dbus.service network-pre.target systemd-sysusers.service
Before=network.target multi-user.target shutdown.target
Wants=network.target

[Service]
Type=dbus
BusName=net.connman
Restart=on-failure
ExecStart=/usr/sbin/connmand -n
StandardOutput=null
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SYS_TIME CAP_SYS_MODULE
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target

**Comment by samnazarko** [comment]
It’s still used, but it looks like you installed a different ConnMan package than the OSMC one

On 7 Sep 2023, at 11:40, Juba B ***@***.***> wrote:

﻿

Hi,
I have installed Debian 11 with XFCE desktop and I wanted to add a DNS server, but I found out that connman was using port 53, I found online that there was a configuration file in /etc/connman.prefs to disable it, but it seems like it's not used anymore by the service, is there any reason why this was deleted and also how can I disable the DNS proxy, so I can use port 53 for my dns server.

Here is the service file I have

Description=Connection service
DefaultDependencies=false
Conflicts=shutdown.target
RequiresMountsFor=/var/lib/connman
After=dbus.service network-pre.target systemd-sysusers.service
Before=network.target multi-user.target shutdown.target
Wants=network.target

[Service]
Type=dbus
BusName=net.connman
Restart=on-failure
ExecStart=/usr/sbin/connmand -n
StandardOutput=null
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SYS_TIME CAP_SYS_MODULE
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target```

Thank you.

**Comment by rizerzero** [comment]
Hi @samnazarko, sorry i was not aware that there were different ConnMan packages, I think mine was installed with the XFC desktop,I thinks it's this one https://packages.debian.org/buster/connman, 
Thank you !

**Comment by samnazarko** [comment]
You should stick with the OSMC one

On 7 Sep 2023, at 12:21, Juba B ***@***.***> wrote:

﻿

Hi @samnazarko<https://github.com/samnazarko>, sorry i was not aware that there were different ConnMan packages, I think mine was installed with the XFC desktop,I thinks it's this one https://packages.debian.org/buster/connman,
Thank you !

**Comment by samnazarko** [comment]
Why would you install the upstream version of ConnMan when you already have the OSMC version, then expect it to follow preferences under the /etc/osmc directory? If you want to use upstream ConnMan you need to disable DNS proxying manually..

________________________________

**Comment by rizerzero** [comment]
Thank you !
