### ISSUE TITLE
OSMC Preseed Wifi settings not working

### ISSUE THREAD

**Issue by arminpkathrein** [osmc/osmc#747]
Hi,

I've seen in the past multiple issues about preseed wifi settings. I have not found any report that this has been fixed 100% and i'm also having issues.
Currently have a Raspberry pi zero 2 W and can't connect with a LAN Cable, so preseeding is crucial for me.
The log file shows that it found the preseed file: "Thu Jan 1 00:00:16 1970 Preseed file found, will attempt to parse".
But even if i configure the wifi without password, it just won't connect during initial install.
Is there an older version of OSMC where this is working that i can use?

**Comment by samnazarko** [comment]
WiFi isn't meant to connect during installation. It will connect after booting OSMC.
This issue tracker is for confirmed issues only, so I suggest you post on the forums so we can resolve your problem promptly.

**Comment by arminpkathrein** [comment]
Thanks for the response.
I'm actually talking after the OSMC has booted up. So when i see the language select screen, this means that OSMC has already booted right? But WiFI still won't connect.
Or is that screen still part of the initial setup and osmc is not fully "booted up"?
