### ISSUE TITLE
Video playback after very long pause skips and fast forwards unless stoped and replayed

### ISSUE THREAD

**Issue by Arndorferd** [osmc/osmc#749]
Youtube Add-on Version: 7.0.2.2
Kodi Version: 20.2
Operating System: OSMC

After a long pause of a video the playback skips ahead in a Fast Forward kind of way when you press play again. Have to press stop and restart video to get normal playback

Tried reporting at https://github.com/anxdpanic/plugin.video.youtube/issues/533 was told to report with OSMC.

Here's a (very long) log of the whole time the video was paused and played again:

https://zerobin.net/?348c225dfa1b3db3#PwcehjUkeLmO0+i9jsEQCAOwTGDGGiH5xYTS/EXeXoI=

**Comment by samnazarko** [comment]
Need an OSMC log -- not even sure what device you are running OSMC on. 
See https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/. 

This issue tracker is for confirmed issues only. I'd suggest starting a post on the forums so we can investigate this properly

Cheers

Sam
