### ISSUE TITLE
Support for Raspberry Pi 5

### ISSUE THREAD

**Issue by fenjen** [osmc/osmc#751]
Currently, OSMC and the OSMC installer lack support for Raspberry Pi 5. Adding `os_check=0` to `config.txt` does not help.

**Comment by samnazarko** [comment]
It’s all outlined on the blog.
Team will be testing internally within a couple of days

On 4 Dec 2023, at 09:54, fenjen ***@***.***> wrote:

﻿

I thought this ticket was a handy way to be kept up to date (for everyone).
