### ISSUE TITLE
Network name lookup Case Sensitive

### ISSUE THREAD

**Issue by deelkar** [osmc/osmc#758]
After updating to the latest OSMC on Raspberry pi 4, suddenly I cannot access any smb shares off my server.
Log file reveals a lot of 
 `error <general>: Unable to lookup host: 'SERVER'`
entries.
if I log in via SSH and try the command
`host server`
the ip address is resolved correctly, however the command
`host SERVER`
results in
`Host SERVER not found: 3(NXDOMAIN)`

to the best of my knowledge hostname resolution _must_ be case _in_sensitve i.e. any capitalisation of the hostname must result in the same ip address.

**Comment by samnazarko** [comment]
Can you please start a forum post with logs?
See https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/.

This GitHub is for confirmed issues only.
