### ISSUE TITLE
HiFi DiGi DAC sampling rate to be 48kHz by default (instead of a value up to 384kHz)

### ISSUE THREAD

**Issue by tvass** [osmc/osmc#764]
Hi there,
When you install a DAC (eg: PCM5122 Chip I2S Interface HiFi DiGi DAC) on a `RPi4` and configure it in OSMC from the GUI, the sampling rate is by default configured at `48000` (48kHz):

```
$ cat /proc/asound/sndrpihifiberry/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 2400
buffer_size: 9600
```

This hardware can go up to `384kHz` (I know that, there is likely not a human who can hear the difference).
However, I compared with my `VERO V` which is using `HDMI` for audio out, the sampling rate is `192000`  (192kHz).

```
$ cat card0/pcm2p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 192000 (192000/1)
period_size: 8192
buffer_size: 32768
```

So I believe, we could improve the default settings to avoid downsampling with common Hi Res audio (eg: files from [HDtracks](https://www.hdtracks.com/#/album/641c71bb68d8361f057849f0)).
I successfully played FLAC 96 kHz as an example by forcing a configuration in Alsa (manually created the `/etc/asound.conf`).

```
pcm.!default {
    type hw
    card 2
    device 0
    rate 384000
}
``` 
After a reboot, we can see the good rate.
```
$ cat /proc/asound/sndrpihifiberry/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 384000 (384000/1)
period_size: 16384
buffer_size: 65536
```

![20240319_215035](https://github.com/osmc/osmc/assets/1489618/553db361-24c1-47fa-a373-d81c8f93f955)

**Comment by graham8** [comment]
Is this just for information or are you suggesting the alsa config is changed by default?

By the way, you should use a ~/.asoundrc file to avoid your conf getting overwritten by a distro upgrade.

**Comment by tvass** [comment]
Thanks for your comment. While investigating on your comment, I found that we can configure the `max sampling rate` in the GUI. 

Closing the issue as it is not valid.
